// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 玩家所有活动任务通知
type MsgGS2CLPlayerAllActivityNotice struct {
	Infos          []*PlayerActivityInfo          `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	Rewarded       []*PlayerActivityRewarded      `protobuf:"bytes,2,rep,name=rewarded" json:"rewarded,omitempty"`
	DropInfos      []*PlayerActivityDropInfo      `protobuf:"bytes,3,rep,name=drop_infos,json=dropInfos" json:"drop_infos,omitempty"`
	ExchangeInfos  []*PlayerActivityExchangeInfo  `protobuf:"bytes,4,rep,name=exchange_infos,json=exchangeInfos" json:"exchange_infos,omitempty"`
	TurntableInfos []*PlayerActivityTurntableInfo `protobuf:"bytes,5,rep,name=turntable_infos,json=turntableInfos" json:"turntable_infos,omitempty"`
	BeadInfos      []*PlayerActivityBeadInfo      `protobuf:"bytes,6,rep,name=bead_infos,json=beadInfos" json:"bead_infos,omitempty"`
	CleanDayInfos  []*PlayerActivityCleanDayInfo  `protobuf:"bytes,8,rep,name=clean_day_infos,json=cleanDayInfos" json:"clean_day_infos,omitempty"`
	RetainedInfo   []*PlayerActivityRetainedInfo  `protobuf:"bytes,9,rep,name=retained_info,json=retainedInfo" json:"retained_info,omitempty"`
	LoginInfo      []*PlayerLoginActivityInfo     `protobuf:"bytes,10,rep,name=login_info,json=loginInfo" json:"login_info,omitempty"`
}

func (m *MsgGS2CLPlayerAllActivityNotice) Reset()                    { *m = MsgGS2CLPlayerAllActivityNotice{} }
func (m *MsgGS2CLPlayerAllActivityNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerAllActivityNotice) ProtoMessage()               {}
func (*MsgGS2CLPlayerAllActivityNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MsgGS2CLPlayerAllActivityNotice) GetInfos() []*PlayerActivityInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetRewarded() []*PlayerActivityRewarded {
	if m != nil {
		return m.Rewarded
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetDropInfos() []*PlayerActivityDropInfo {
	if m != nil {
		return m.DropInfos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetExchangeInfos() []*PlayerActivityExchangeInfo {
	if m != nil {
		return m.ExchangeInfos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetTurntableInfos() []*PlayerActivityTurntableInfo {
	if m != nil {
		return m.TurntableInfos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetBeadInfos() []*PlayerActivityBeadInfo {
	if m != nil {
		return m.BeadInfos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetCleanDayInfos() []*PlayerActivityCleanDayInfo {
	if m != nil {
		return m.CleanDayInfos
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetRetainedInfo() []*PlayerActivityRetainedInfo {
	if m != nil {
		return m.RetainedInfo
	}
	return nil
}

func (m *MsgGS2CLPlayerAllActivityNotice) GetLoginInfo() []*PlayerLoginActivityInfo {
	if m != nil {
		return m.LoginInfo
	}
	return nil
}

// 玩家已领阶段奖励通知
type MsgGS2CLPlayerActivityRewardedNotice struct {
	Rewarded *PlayerActivityRewarded `protobuf:"bytes,1,opt,name=rewarded" json:"rewarded,omitempty"`
}

func (m *MsgGS2CLPlayerActivityRewardedNotice) Reset()         { *m = MsgGS2CLPlayerActivityRewardedNotice{} }
func (m *MsgGS2CLPlayerActivityRewardedNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityRewardedNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityRewardedNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1}
}

func (m *MsgGS2CLPlayerActivityRewardedNotice) GetRewarded() *PlayerActivityRewarded {
	if m != nil {
		return m.Rewarded
	}
	return nil
}

// 玩家单个活动通知
type MsgGS2CLPlayerActivityNotice struct {
	Info *PlayerActivityInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityNotice) Reset()                    { *m = MsgGS2CLPlayerActivityNotice{} }
func (m *MsgGS2CLPlayerActivityNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityNotice) ProtoMessage()               {}
func (*MsgGS2CLPlayerActivityNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *MsgGS2CLPlayerActivityNotice) GetInfo() *PlayerActivityInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 玩家单个掉落活动通知
type MsgGS2CLPlayerActivityDropNotice struct {
	DropInfo *PlayerActivityDropInfo `protobuf:"bytes,1,opt,name=drop_info,json=dropInfo" json:"drop_info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityDropNotice) Reset()         { *m = MsgGS2CLPlayerActivityDropNotice{} }
func (m *MsgGS2CLPlayerActivityDropNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityDropNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityDropNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{3}
}

func (m *MsgGS2CLPlayerActivityDropNotice) GetDropInfo() *PlayerActivityDropInfo {
	if m != nil {
		return m.DropInfo
	}
	return nil
}

// 玩家单个兑换活动通知
type MsgGS2CLPlayerActivityExchangeNotice struct {
	Info *PlayerActivityExchangeInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityExchangeNotice) Reset()         { *m = MsgGS2CLPlayerActivityExchangeNotice{} }
func (m *MsgGS2CLPlayerActivityExchangeNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityExchangeNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityExchangeNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{4}
}

func (m *MsgGS2CLPlayerActivityExchangeNotice) GetInfo() *PlayerActivityExchangeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 玩家单个转盘活动通知
type MsgGS2CLPlayerActivityTurntableNotice struct {
	Info *PlayerActivityTurntableInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityTurntableNotice) Reset()         { *m = MsgGS2CLPlayerActivityTurntableNotice{} }
func (m *MsgGS2CLPlayerActivityTurntableNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityTurntableNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityTurntableNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{5}
}

func (m *MsgGS2CLPlayerActivityTurntableNotice) GetInfo() *PlayerActivityTurntableInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 玩家单个点灯活动通知
type MsgGS2CLPlayerActivityBeadNotice struct {
	Info *PlayerActivityBeadInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityBeadNotice) Reset()         { *m = MsgGS2CLPlayerActivityBeadNotice{} }
func (m *MsgGS2CLPlayerActivityBeadNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityBeadNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityBeadNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6}
}

func (m *MsgGS2CLPlayerActivityBeadNotice) GetInfo() *PlayerActivityBeadInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 玩家单个任务通知
type MsgGS2CLPlayerActivityTaskUpdateNotice struct {
	MainTask   *TaskData `protobuf:"bytes,1,opt,name=main_task,json=mainTask" json:"main_task,omitempty"`
	ActivityId uint32    `protobuf:"varint,2,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      uint32    `protobuf:"varint,3,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
}

func (m *MsgGS2CLPlayerActivityTaskUpdateNotice) Reset() {
	*m = MsgGS2CLPlayerActivityTaskUpdateNotice{}
}
func (m *MsgGS2CLPlayerActivityTaskUpdateNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityTaskUpdateNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityTaskUpdateNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{7}
}

func (m *MsgGS2CLPlayerActivityTaskUpdateNotice) GetMainTask() *TaskData {
	if m != nil {
		return m.MainTask
	}
	return nil
}

func (m *MsgGS2CLPlayerActivityTaskUpdateNotice) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLPlayerActivityTaskUpdateNotice) GetSubId() uint32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

// 活动积分通知
type MsgGS2CLPlayerActivityScoreNotice struct {
	ActivityId int32  `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      int32  `protobuf:"varint,2,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
	Score      uint64 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
}

func (m *MsgGS2CLPlayerActivityScoreNotice) Reset()         { *m = MsgGS2CLPlayerActivityScoreNotice{} }
func (m *MsgGS2CLPlayerActivityScoreNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityScoreNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityScoreNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8}
}

func (m *MsgGS2CLPlayerActivityScoreNotice) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLPlayerActivityScoreNotice) GetSubId() int32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

func (m *MsgGS2CLPlayerActivityScoreNotice) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

// 玩家清洁日活动通知
type MsgGS2CLPlayerActivityCleanDayNotice struct {
	Info *PlayerActivityCleanDayInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerActivityCleanDayNotice) Reset()         { *m = MsgGS2CLPlayerActivityCleanDayNotice{} }
func (m *MsgGS2CLPlayerActivityCleanDayNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerActivityCleanDayNotice) ProtoMessage()    {}
func (*MsgGS2CLPlayerActivityCleanDayNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{9}
}

func (m *MsgGS2CLPlayerActivityCleanDayNotice) GetInfo() *PlayerActivityCleanDayInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 请求领取活动任务奖励
type MsgCL2GSActivityTaskAwardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      uint32 `protobuf:"varint,2,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
	TaskId     uint32 `protobuf:"varint,3,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *MsgCL2GSActivityTaskAwardRequest) Reset()         { *m = MsgCL2GSActivityTaskAwardRequest{} }
func (m *MsgCL2GSActivityTaskAwardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityTaskAwardRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityTaskAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{10}
}

func (m *MsgCL2GSActivityTaskAwardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityTaskAwardRequest) GetSubId() uint32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

func (m *MsgCL2GSActivityTaskAwardRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type MsgCL2GSActivityTaskAwardReply struct {
	TaskId     uint32      `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Awards     []*Resource `protobuf:"bytes,2,rep,name=awards" json:"awards,omitempty"`
	ActivityId uint32      `protobuf:"varint,3,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      uint32      `protobuf:"varint,4,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityTaskAwardReply) Reset()                    { *m = MsgCL2GSActivityTaskAwardReply{} }
func (m *MsgCL2GSActivityTaskAwardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityTaskAwardReply) ProtoMessage()               {}
func (*MsgCL2GSActivityTaskAwardReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *MsgCL2GSActivityTaskAwardReply) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *MsgCL2GSActivityTaskAwardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityTaskAwardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityTaskAwardReply) GetSubId() uint32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

func (m *MsgCL2GSActivityTaskAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求领取活动进度奖励
type MsgCL2GSActivityIndexAwardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index      uint32 `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
}

func (m *MsgCL2GSActivityIndexAwardRequest) Reset()         { *m = MsgCL2GSActivityIndexAwardRequest{} }
func (m *MsgCL2GSActivityIndexAwardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityIndexAwardRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityIndexAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{12}
}

func (m *MsgCL2GSActivityIndexAwardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityIndexAwardRequest) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type MsgCL2GSActivityIndexAwardReply struct {
	Index        uint32      `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Awards       []*Resource `protobuf:"bytes,2,rep,name=awards" json:"awards,omitempty"`
	ActivityId   uint32      `protobuf:"varint,3,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	VipReward    bool        `protobuf:"varint,4,opt,name=vip_reward,json=vipReward" json:"vip_reward,omitempty"`
	NormalReward bool        `protobuf:"varint,5,opt,name=normal_reward,json=normalReward" json:"normal_reward,omitempty"`
	ErrorCode    int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityIndexAwardReply) Reset()         { *m = MsgCL2GSActivityIndexAwardReply{} }
func (m *MsgCL2GSActivityIndexAwardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityIndexAwardReply) ProtoMessage()    {}
func (*MsgCL2GSActivityIndexAwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{13}
}

func (m *MsgCL2GSActivityIndexAwardReply) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MsgCL2GSActivityIndexAwardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityIndexAwardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityIndexAwardReply) GetVipReward() bool {
	if m != nil {
		return m.VipReward
	}
	return false
}

func (m *MsgCL2GSActivityIndexAwardReply) GetNormalReward() bool {
	if m != nil {
		return m.NormalReward
	}
	return false
}

func (m *MsgCL2GSActivityIndexAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求兑换
type MsgCL2GSActivityExchangeRequest struct {
	ActivityId uint32                 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Request    []*ExchangeRequestData `protobuf:"bytes,2,rep,name=request" json:"request,omitempty"`
}

func (m *MsgCL2GSActivityExchangeRequest) Reset()         { *m = MsgCL2GSActivityExchangeRequest{} }
func (m *MsgCL2GSActivityExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityExchangeRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{14}
}

func (m *MsgCL2GSActivityExchangeRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityExchangeRequest) GetRequest() []*ExchangeRequestData {
	if m != nil {
		return m.Request
	}
	return nil
}

type MsgCL2GSActivityExchangeReply struct {
	Awards     []*Resource            `protobuf:"bytes,2,rep,name=awards" json:"awards,omitempty"`
	ActivityId uint32                 `protobuf:"varint,3,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Request    []*ExchangeRequestData `protobuf:"bytes,4,rep,name=request" json:"request,omitempty"`
	ErrorCode  int32                  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityExchangeReply) Reset()                    { *m = MsgCL2GSActivityExchangeReply{} }
func (m *MsgCL2GSActivityExchangeReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityExchangeReply) ProtoMessage()               {}
func (*MsgCL2GSActivityExchangeReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *MsgCL2GSActivityExchangeReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityExchangeReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityExchangeReply) GetRequest() []*ExchangeRequestData {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *MsgCL2GSActivityExchangeReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 转盘抽奖请求
type MsgCL2GSActivityTurntableRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Type       int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
}

func (m *MsgCL2GSActivityTurntableRequest) Reset()         { *m = MsgCL2GSActivityTurntableRequest{} }
func (m *MsgCL2GSActivityTurntableRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityTurntableRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityTurntableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{16}
}

func (m *MsgCL2GSActivityTurntableRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityTurntableRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// 转盘抽奖回应
type MsgCL2GSActivityTurntableReply struct {
	ActivityId uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Type       int32       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Awards     []*Resource `protobuf:"bytes,3,rep,name=awards" json:"awards,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityTurntableReply) Reset()                    { *m = MsgCL2GSActivityTurntableReply{} }
func (m *MsgCL2GSActivityTurntableReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityTurntableReply) ProtoMessage()               {}
func (*MsgCL2GSActivityTurntableReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *MsgCL2GSActivityTurntableReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityTurntableReply) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MsgCL2GSActivityTurntableReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityTurntableReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取转盘阶段奖励请求
type MsgCL2GSActivityTurntableStageRewardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Count      uint32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *MsgCL2GSActivityTurntableStageRewardRequest) Reset() {
	*m = MsgCL2GSActivityTurntableStageRewardRequest{}
}
func (m *MsgCL2GSActivityTurntableStageRewardRequest) String() string {
	return proto.CompactTextString(m)
}
func (*MsgCL2GSActivityTurntableStageRewardRequest) ProtoMessage() {}
func (*MsgCL2GSActivityTurntableStageRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{18}
}

func (m *MsgCL2GSActivityTurntableStageRewardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityTurntableStageRewardRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 领取转盘阶段奖励回应
type MsgGS2CLActivityTurntableStageRewardReply struct {
	ActivityId uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Count      uint32      `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Awards     []*Resource `protobuf:"bytes,3,rep,name=awards" json:"awards,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLActivityTurntableStageRewardReply) Reset() {
	*m = MsgGS2CLActivityTurntableStageRewardReply{}
}
func (m *MsgGS2CLActivityTurntableStageRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityTurntableStageRewardReply) ProtoMessage()    {}
func (*MsgGS2CLActivityTurntableStageRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{19}
}

func (m *MsgGS2CLActivityTurntableStageRewardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLActivityTurntableStageRewardReply) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MsgGS2CLActivityTurntableStageRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgGS2CLActivityTurntableStageRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取点灯任务奖励请求
type MsgCL2GSActivityBeadTaskRewardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	TaskId     uint32 `protobuf:"varint,2,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *MsgCL2GSActivityBeadTaskRewardRequest) Reset()         { *m = MsgCL2GSActivityBeadTaskRewardRequest{} }
func (m *MsgCL2GSActivityBeadTaskRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadTaskRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadTaskRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{20}
}

func (m *MsgCL2GSActivityBeadTaskRewardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadTaskRewardRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

// 领取点灯任务奖励回应
type MsgCL2GSActivityBeadTaskRewardReply struct {
	ActivityId uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	TaskId     uint32      `protobuf:"varint,2,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Awards     []*Resource `protobuf:"bytes,3,rep,name=awards" json:"awards,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityBeadTaskRewardReply) Reset()         { *m = MsgCL2GSActivityBeadTaskRewardReply{} }
func (m *MsgCL2GSActivityBeadTaskRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadTaskRewardReply) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadTaskRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{21}
}

func (m *MsgCL2GSActivityBeadTaskRewardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadTaskRewardReply) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadTaskRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityBeadTaskRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取点灯奖励请求
type MsgCL2GSActivityBeadRewardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index      int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *MsgCL2GSActivityBeadRewardRequest) Reset()         { *m = MsgCL2GSActivityBeadRewardRequest{} }
func (m *MsgCL2GSActivityBeadRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{22}
}

func (m *MsgCL2GSActivityBeadRewardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadRewardRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

// 领取点灯奖励回应
type MsgCL2GSActivityBeadRewardReply struct {
	ActivityId uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index      int32       `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Awards     []*Resource `protobuf:"bytes,3,rep,name=awards" json:"awards,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityBeadRewardReply) Reset()         { *m = MsgCL2GSActivityBeadRewardReply{} }
func (m *MsgCL2GSActivityBeadRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadRewardReply) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{23}
}

func (m *MsgCL2GSActivityBeadRewardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadRewardReply) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MsgCL2GSActivityBeadRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityBeadRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取点灯最终大奖请求
type MsgCL2GSActivityBeadFinalRewardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *MsgCL2GSActivityBeadFinalRewardRequest) Reset() {
	*m = MsgCL2GSActivityBeadFinalRewardRequest{}
}
func (m *MsgCL2GSActivityBeadFinalRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadFinalRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadFinalRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{24}
}

func (m *MsgCL2GSActivityBeadFinalRewardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

// 领取点灯最终大奖回应
type MsgCL2GSActivityBeadFinalRewardReply struct {
	ActivityId uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Awards     []*Resource `protobuf:"bytes,2,rep,name=awards" json:"awards,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSActivityBeadFinalRewardReply) Reset()         { *m = MsgCL2GSActivityBeadFinalRewardReply{} }
func (m *MsgCL2GSActivityBeadFinalRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityBeadFinalRewardReply) ProtoMessage()    {}
func (*MsgCL2GSActivityBeadFinalRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{25}
}

func (m *MsgCL2GSActivityBeadFinalRewardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityBeadFinalRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSActivityBeadFinalRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MsgCL2GSQuestionBankRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *MsgCL2GSQuestionBankRequest) Reset()                    { *m = MsgCL2GSQuestionBankRequest{} }
func (m *MsgCL2GSQuestionBankRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSQuestionBankRequest) ProtoMessage()               {}
func (*MsgCL2GSQuestionBankRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *MsgCL2GSQuestionBankRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

type MsgGS2CLQuestionBankReply struct {
	QuestionsBank *MsgGS2CLQuestionBankNotice `protobuf:"bytes,1,opt,name=questions_bank,json=questionsBank" json:"questions_bank,omitempty"`
}

func (m *MsgGS2CLQuestionBankReply) Reset()                    { *m = MsgGS2CLQuestionBankReply{} }
func (m *MsgGS2CLQuestionBankReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLQuestionBankReply) ProtoMessage()               {}
func (*MsgGS2CLQuestionBankReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *MsgGS2CLQuestionBankReply) GetQuestionsBank() *MsgGS2CLQuestionBankNotice {
	if m != nil {
		return m.QuestionsBank
	}
	return nil
}

// 知识广场(线上同步，0点同步)
type MsgGS2CLQuestionBankNotice struct {
	CompleteState  AnswerQuestionComplteState `protobuf:"varint,1,opt,name=complete_state,json=completeState,enum=protomsg.AnswerQuestionComplteState" json:"complete_state,omitempty"`
	Questions      []*QuestionBankInfo        `protobuf:"bytes,2,rep,name=questions" json:"questions,omitempty"`
	CurQuestionsId uint32                     `protobuf:"varint,3,opt,name=cur_questions_id,json=curQuestionsId" json:"cur_questions_id,omitempty"`
	CorrectCnt     uint32                     `protobuf:"varint,4,opt,name=correct_cnt,json=correctCnt" json:"correct_cnt,omitempty"`
	HelpCnt        uint32                     `protobuf:"varint,5,opt,name=help_cnt,json=helpCnt" json:"help_cnt,omitempty"`
	IsDayReset     bool                       `protobuf:"varint,6,opt,name=is_day_reset,json=isDayReset" json:"is_day_reset,omitempty"`
	ActivityId     uint32                     `protobuf:"varint,7,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	HelpInfo       []*QuestionBankHelpInfo    `protobuf:"bytes,8,rep,name=help_info,json=helpInfo" json:"help_info,omitempty"`
	ErrorCode      int32                      `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLQuestionBankNotice) Reset()                    { *m = MsgGS2CLQuestionBankNotice{} }
func (m *MsgGS2CLQuestionBankNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLQuestionBankNotice) ProtoMessage()               {}
func (*MsgGS2CLQuestionBankNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *MsgGS2CLQuestionBankNotice) GetCompleteState() AnswerQuestionComplteState {
	if m != nil {
		return m.CompleteState
	}
	return AnswerQuestionComplteState_kAnswerQuestionComplteState_None
}

func (m *MsgGS2CLQuestionBankNotice) GetQuestions() []*QuestionBankInfo {
	if m != nil {
		return m.Questions
	}
	return nil
}

func (m *MsgGS2CLQuestionBankNotice) GetCurQuestionsId() uint32 {
	if m != nil {
		return m.CurQuestionsId
	}
	return 0
}

func (m *MsgGS2CLQuestionBankNotice) GetCorrectCnt() uint32 {
	if m != nil {
		return m.CorrectCnt
	}
	return 0
}

func (m *MsgGS2CLQuestionBankNotice) GetHelpCnt() uint32 {
	if m != nil {
		return m.HelpCnt
	}
	return 0
}

func (m *MsgGS2CLQuestionBankNotice) GetIsDayReset() bool {
	if m != nil {
		return m.IsDayReset
	}
	return false
}

func (m *MsgGS2CLQuestionBankNotice) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLQuestionBankNotice) GetHelpInfo() []*QuestionBankHelpInfo {
	if m != nil {
		return m.HelpInfo
	}
	return nil
}

func (m *MsgGS2CLQuestionBankNotice) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 知识广场(cl->gs  请求答题)
type MsgCL2GSAnswerQuestionsRequest struct {
	AnswersId  uint32 `protobuf:"varint,1,opt,name=answers_id,json=answersId" json:"answers_id,omitempty"`
	ActivityId uint32 `protobuf:"varint,2,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *MsgCL2GSAnswerQuestionsRequest) Reset()                    { *m = MsgCL2GSAnswerQuestionsRequest{} }
func (m *MsgCL2GSAnswerQuestionsRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSAnswerQuestionsRequest) ProtoMessage()               {}
func (*MsgCL2GSAnswerQuestionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *MsgCL2GSAnswerQuestionsRequest) GetAnswersId() uint32 {
	if m != nil {
		return m.AnswersId
	}
	return 0
}

func (m *MsgCL2GSAnswerQuestionsRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

// 知识广场(gs->cl 回复答题)
type MsgGS2CLAnswerQuestionsReply struct {
	QuestionsId     uint32                     `protobuf:"varint,1,opt,name=questions_id,json=questionsId" json:"questions_id,omitempty"`
	IsCorrect       bool                       `protobuf:"varint,2,opt,name=is_correct,json=isCorrect" json:"is_correct,omitempty"`
	NextQuestionsId uint32                     `protobuf:"varint,3,opt,name=next_questions_id,json=nextQuestionsId" json:"next_questions_id,omitempty"`
	CompleteState   AnswerQuestionComplteState `protobuf:"varint,4,opt,name=complete_state,json=completeState,enum=protomsg.AnswerQuestionComplteState" json:"complete_state,omitempty"`
	ActivityId      uint32                     `protobuf:"varint,5,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	ErrorCode       int32                      `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLAnswerQuestionsReply) Reset()                    { *m = MsgGS2CLAnswerQuestionsReply{} }
func (m *MsgGS2CLAnswerQuestionsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLAnswerQuestionsReply) ProtoMessage()               {}
func (*MsgGS2CLAnswerQuestionsReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *MsgGS2CLAnswerQuestionsReply) GetQuestionsId() uint32 {
	if m != nil {
		return m.QuestionsId
	}
	return 0
}

func (m *MsgGS2CLAnswerQuestionsReply) GetIsCorrect() bool {
	if m != nil {
		return m.IsCorrect
	}
	return false
}

func (m *MsgGS2CLAnswerQuestionsReply) GetNextQuestionsId() uint32 {
	if m != nil {
		return m.NextQuestionsId
	}
	return 0
}

func (m *MsgGS2CLAnswerQuestionsReply) GetCompleteState() AnswerQuestionComplteState {
	if m != nil {
		return m.CompleteState
	}
	return AnswerQuestionComplteState_kAnswerQuestionComplteState_None
}

func (m *MsgGS2CLAnswerQuestionsReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLAnswerQuestionsReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 知识广场(cl->gs 请求放弃答题)
type MsgCL2GSGiveupAnswerQuestionsRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *MsgCL2GSGiveupAnswerQuestionsRequest) Reset()         { *m = MsgCL2GSGiveupAnswerQuestionsRequest{} }
func (m *MsgCL2GSGiveupAnswerQuestionsRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSGiveupAnswerQuestionsRequest) ProtoMessage()    {}
func (*MsgCL2GSGiveupAnswerQuestionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{31}
}

func (m *MsgCL2GSGiveupAnswerQuestionsRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

// 知识广场(gs->cl 放弃答题回复)
type MsgGS2CLGiveupAnswerQuestionsReply struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLGiveupAnswerQuestionsReply) Reset()         { *m = MsgGS2CLGiveupAnswerQuestionsReply{} }
func (m *MsgGS2CLGiveupAnswerQuestionsReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLGiveupAnswerQuestionsReply) ProtoMessage()    {}
func (*MsgGS2CLGiveupAnswerQuestionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{32}
}

func (m *MsgGS2CLGiveupAnswerQuestionsReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLGiveupAnswerQuestionsReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 知识广场(cl->gs 分享成功发送)
type MsgCL2GSHelpAnswerQuestionRequest struct {
	ActivityId  uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	QuestionsId uint32 `protobuf:"varint,2,opt,name=questions_id,json=questionsId" json:"questions_id,omitempty"`
}

func (m *MsgCL2GSHelpAnswerQuestionRequest) Reset()         { *m = MsgCL2GSHelpAnswerQuestionRequest{} }
func (m *MsgCL2GSHelpAnswerQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSHelpAnswerQuestionRequest) ProtoMessage()    {}
func (*MsgCL2GSHelpAnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{33}
}

func (m *MsgCL2GSHelpAnswerQuestionRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSHelpAnswerQuestionRequest) GetQuestionsId() uint32 {
	if m != nil {
		return m.QuestionsId
	}
	return 0
}

// 知识广场(gs->cl 回复分享成功发送)
type MsgGS2CLHelpAnswerQuestionReply struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLHelpAnswerQuestionReply) Reset()         { *m = MsgGS2CLHelpAnswerQuestionReply{} }
func (m *MsgGS2CLHelpAnswerQuestionReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLHelpAnswerQuestionReply) ProtoMessage()    {}
func (*MsgGS2CLHelpAnswerQuestionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{34}
}

func (m *MsgGS2CLHelpAnswerQuestionReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLHelpAnswerQuestionReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 谁帮助答题请求
type MsgCL2GSWhoHelpAnswerQuestionRequest struct {
	ActivityId  uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	QuestionsId uint32 `protobuf:"varint,2,opt,name=questions_id,json=questionsId" json:"questions_id,omitempty"`
	PlayerId    uint64 `protobuf:"varint,3,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgCL2GSWhoHelpAnswerQuestionRequest) Reset()         { *m = MsgCL2GSWhoHelpAnswerQuestionRequest{} }
func (m *MsgCL2GSWhoHelpAnswerQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSWhoHelpAnswerQuestionRequest) ProtoMessage()    {}
func (*MsgCL2GSWhoHelpAnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{35}
}

func (m *MsgCL2GSWhoHelpAnswerQuestionRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSWhoHelpAnswerQuestionRequest) GetQuestionsId() uint32 {
	if m != nil {
		return m.QuestionsId
	}
	return 0
}

func (m *MsgCL2GSWhoHelpAnswerQuestionRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type MsgGS2CLWhoHelpAnswerQuestionReply struct {
	ActivityId  uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	QuestionsId uint32 `protobuf:"varint,2,opt,name=questions_id,json=questionsId" json:"questions_id,omitempty"`
	PlayerId    uint64 `protobuf:"varint,3,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ErrorCode   int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLWhoHelpAnswerQuestionReply) Reset()         { *m = MsgGS2CLWhoHelpAnswerQuestionReply{} }
func (m *MsgGS2CLWhoHelpAnswerQuestionReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLWhoHelpAnswerQuestionReply) ProtoMessage()    {}
func (*MsgGS2CLWhoHelpAnswerQuestionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{36}
}

func (m *MsgGS2CLWhoHelpAnswerQuestionReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLWhoHelpAnswerQuestionReply) GetQuestionsId() uint32 {
	if m != nil {
		return m.QuestionsId
	}
	return 0
}

func (m *MsgGS2CLWhoHelpAnswerQuestionReply) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2CLWhoHelpAnswerQuestionReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 清洁日领取奖励
type MsgCL2GSCleanDayGetRewardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	RewardId   uint32 `protobuf:"varint,2,opt,name=reward_id,json=rewardId" json:"reward_id,omitempty"`
}

func (m *MsgCL2GSCleanDayGetRewardRequest) Reset()         { *m = MsgCL2GSCleanDayGetRewardRequest{} }
func (m *MsgCL2GSCleanDayGetRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSCleanDayGetRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSCleanDayGetRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{37}
}

func (m *MsgCL2GSCleanDayGetRewardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSCleanDayGetRewardRequest) GetRewardId() uint32 {
	if m != nil {
		return m.RewardId
	}
	return 0
}

type MsgGS2CLCleanDayGetRewardReply struct {
	ActivityId uint32   `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	RewardIds  []uint32 `protobuf:"varint,2,rep,packed,name=reward_ids,json=rewardIds" json:"reward_ids,omitempty"`
	ErrorCode  int32    `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLCleanDayGetRewardReply) Reset()                    { *m = MsgGS2CLCleanDayGetRewardReply{} }
func (m *MsgGS2CLCleanDayGetRewardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLCleanDayGetRewardReply) ProtoMessage()               {}
func (*MsgGS2CLCleanDayGetRewardReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{38} }

func (m *MsgGS2CLCleanDayGetRewardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLCleanDayGetRewardReply) GetRewardIds() []uint32 {
	if m != nil {
		return m.RewardIds
	}
	return nil
}

func (m *MsgGS2CLCleanDayGetRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 获取活动期数
type MsgCL2GSActivityPeriodRequest struct {
	ActivityIds []uint32 `protobuf:"varint,1,rep,packed,name=activity_ids,json=activityIds" json:"activity_ids,omitempty"`
}

func (m *MsgCL2GSActivityPeriodRequest) Reset()                    { *m = MsgCL2GSActivityPeriodRequest{} }
func (m *MsgCL2GSActivityPeriodRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityPeriodRequest) ProtoMessage()               {}
func (*MsgCL2GSActivityPeriodRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{39} }

func (m *MsgCL2GSActivityPeriodRequest) GetActivityIds() []uint32 {
	if m != nil {
		return m.ActivityIds
	}
	return nil
}

type MsgGS2CLActivityPeriodReply struct {
	Datas     []*ActivityPeriodData `protobuf:"bytes,1,rep,name=datas" json:"datas,omitempty"`
	ErrorCode int32                 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLActivityPeriodReply) Reset()                    { *m = MsgGS2CLActivityPeriodReply{} }
func (m *MsgGS2CLActivityPeriodReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityPeriodReply) ProtoMessage()               {}
func (*MsgGS2CLActivityPeriodReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{40} }

func (m *MsgGS2CLActivityPeriodReply) GetDatas() []*ActivityPeriodData {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *MsgGS2CLActivityPeriodReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 留存活动（这个消息，活动开启，抽奖完毕之后进行进行通知，而奖励的通知MsgGS2CLPlayerActivityRewardedNotice这个）
type MsgGS2CLActivityRetainedNotice struct {
	Info *PlayerActivityRetainedInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLActivityRetainedNotice) Reset()                    { *m = MsgGS2CLActivityRetainedNotice{} }
func (m *MsgGS2CLActivityRetainedNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityRetainedNotice) ProtoMessage()               {}
func (*MsgGS2CLActivityRetainedNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{41} }

func (m *MsgGS2CLActivityRetainedNotice) GetInfo() *PlayerActivityRetainedInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 抽奖（请求）
type MsgCL2GSActivityRetainedLotteryRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
}

func (m *MsgCL2GSActivityRetainedLotteryRequest) Reset() {
	*m = MsgCL2GSActivityRetainedLotteryRequest{}
}
func (m *MsgCL2GSActivityRetainedLotteryRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSActivityRetainedLotteryRequest) ProtoMessage()    {}
func (*MsgCL2GSActivityRetainedLotteryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{42}
}

func (m *MsgCL2GSActivityRetainedLotteryRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

// 发送奖励返回
type MsgGS2CLActivityRetainedLotteryReply struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	LotteryId  uint32 `protobuf:"varint,2,opt,name=lottery_id,json=lotteryId" json:"lottery_id,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLActivityRetainedLotteryReply) Reset()         { *m = MsgGS2CLActivityRetainedLotteryReply{} }
func (m *MsgGS2CLActivityRetainedLotteryReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityRetainedLotteryReply) ProtoMessage()    {}
func (*MsgGS2CLActivityRetainedLotteryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{43}
}

func (m *MsgGS2CLActivityRetainedLotteryReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLActivityRetainedLotteryReply) GetLotteryId() uint32 {
	if m != nil {
		return m.LotteryId
	}
	return 0
}

func (m *MsgGS2CLActivityRetainedLotteryReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取奖励
type MsgCL2GSActivityRetainedReceiveAwardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index      int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *MsgCL2GSActivityRetainedReceiveAwardRequest) Reset() {
	*m = MsgCL2GSActivityRetainedReceiveAwardRequest{}
}
func (m *MsgCL2GSActivityRetainedReceiveAwardRequest) String() string {
	return proto.CompactTextString(m)
}
func (*MsgCL2GSActivityRetainedReceiveAwardRequest) ProtoMessage() {}
func (*MsgCL2GSActivityRetainedReceiveAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{44}
}

func (m *MsgCL2GSActivityRetainedReceiveAwardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSActivityRetainedReceiveAwardRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

//
type MsgGS2CLActivityRetainedReceiveAwardReply struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	ItemId     uint32 `protobuf:"varint,2,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	Index      int32  `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLActivityRetainedReceiveAwardReply) Reset() {
	*m = MsgGS2CLActivityRetainedReceiveAwardReply{}
}
func (m *MsgGS2CLActivityRetainedReceiveAwardReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityRetainedReceiveAwardReply) ProtoMessage()    {}
func (*MsgGS2CLActivityRetainedReceiveAwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{45}
}

func (m *MsgGS2CLActivityRetainedReceiveAwardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLActivityRetainedReceiveAwardReply) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *MsgGS2CLActivityRetainedReceiveAwardReply) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MsgGS2CLActivityRetainedReceiveAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 玩家七日登录活动
type MsgGS2CLLoginActivityNotice struct {
	Notice *PlayerLoginActivityInfo `protobuf:"bytes,1,opt,name=notice" json:"notice,omitempty"`
}

func (m *MsgGS2CLLoginActivityNotice) Reset()                    { *m = MsgGS2CLLoginActivityNotice{} }
func (m *MsgGS2CLLoginActivityNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLLoginActivityNotice) ProtoMessage()               {}
func (*MsgGS2CLLoginActivityNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{46} }

func (m *MsgGS2CLLoginActivityNotice) GetNotice() *PlayerLoginActivityInfo {
	if m != nil {
		return m.Notice
	}
	return nil
}

// 领取奖励
type MsgCL2GSLLoginActivityReceiveAwardRequest struct {
	ActivityId uint32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index      int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
}

func (m *MsgCL2GSLLoginActivityReceiveAwardRequest) Reset() {
	*m = MsgCL2GSLLoginActivityReceiveAwardRequest{}
}
func (m *MsgCL2GSLLoginActivityReceiveAwardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSLLoginActivityReceiveAwardRequest) ProtoMessage()    {}
func (*MsgCL2GSLLoginActivityReceiveAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{47}
}

func (m *MsgCL2GSLLoginActivityReceiveAwardRequest) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgCL2GSLLoginActivityReceiveAwardRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

//
type MsgGS2CLLoginActivityReceiveAwardReply struct {
	ActivityId     uint32      `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	Index          int32       `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	RewardResource []*Resource `protobuf:"bytes,3,rep,name=reward_resource,json=rewardResource" json:"reward_resource,omitempty"`
	ErrorCode      int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLLoginActivityReceiveAwardReply) Reset() {
	*m = MsgGS2CLLoginActivityReceiveAwardReply{}
}
func (m *MsgGS2CLLoginActivityReceiveAwardReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLLoginActivityReceiveAwardReply) ProtoMessage()    {}
func (*MsgGS2CLLoginActivityReceiveAwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{48}
}

func (m *MsgGS2CLLoginActivityReceiveAwardReply) GetActivityId() uint32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLLoginActivityReceiveAwardReply) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *MsgGS2CLLoginActivityReceiveAwardReply) GetRewardResource() []*Resource {
	if m != nil {
		return m.RewardResource
	}
	return nil
}

func (m *MsgGS2CLLoginActivityReceiveAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 所有活动通知
type MsgGS2CLAllActivityNotice struct {
	Infos *ActivityInfos `protobuf:"bytes,1,opt,name=infos" json:"infos,omitempty"`
}

func (m *MsgGS2CLAllActivityNotice) Reset()                    { *m = MsgGS2CLAllActivityNotice{} }
func (m *MsgGS2CLAllActivityNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLAllActivityNotice) ProtoMessage()               {}
func (*MsgGS2CLAllActivityNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{49} }

func (m *MsgGS2CLAllActivityNotice) GetInfos() *ActivityInfos {
	if m != nil {
		return m.Infos
	}
	return nil
}

// 单个活动状态通知
type MsgGS2CLActivityStatusNotice struct {
	ActivityId int32          `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      int32          `protobuf:"varint,2,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
	TimeBegin  uint64         `protobuf:"varint,3,opt,name=time_begin,json=timeBegin" json:"time_begin,omitempty"`
	TimeEnd    uint64         `protobuf:"varint,4,opt,name=time_end,json=timeEnd" json:"time_end,omitempty"`
	Status     ActivityStatus `protobuf:"varint,5,opt,name=status,enum=protomsg.ActivityStatus" json:"status,omitempty"`
	Period     uint64         `protobuf:"varint,6,opt,name=period" json:"period,omitempty"`
}

func (m *MsgGS2CLActivityStatusNotice) Reset()                    { *m = MsgGS2CLActivityStatusNotice{} }
func (m *MsgGS2CLActivityStatusNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityStatusNotice) ProtoMessage()               {}
func (*MsgGS2CLActivityStatusNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{50} }

func (m *MsgGS2CLActivityStatusNotice) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLActivityStatusNotice) GetSubId() int32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

func (m *MsgGS2CLActivityStatusNotice) GetTimeBegin() uint64 {
	if m != nil {
		return m.TimeBegin
	}
	return 0
}

func (m *MsgGS2CLActivityStatusNotice) GetTimeEnd() uint64 {
	if m != nil {
		return m.TimeEnd
	}
	return 0
}

func (m *MsgGS2CLActivityStatusNotice) GetStatus() ActivityStatus {
	if m != nil {
		return m.Status
	}
	return ActivityStatus_kActivityStatuNone
}

func (m *MsgGS2CLActivityStatusNotice) GetPeriod() uint64 {
	if m != nil {
		return m.Period
	}
	return 0
}

// 移除活动状态通知
type MsgGS2CLActivityRemoveNotice struct {
	ActivityId int32 `protobuf:"varint,1,opt,name=activity_id,json=activityId" json:"activity_id,omitempty"`
	SubId      int32 `protobuf:"varint,2,opt,name=sub_id,json=subId" json:"sub_id,omitempty"`
}

func (m *MsgGS2CLActivityRemoveNotice) Reset()                    { *m = MsgGS2CLActivityRemoveNotice{} }
func (m *MsgGS2CLActivityRemoveNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLActivityRemoveNotice) ProtoMessage()               {}
func (*MsgGS2CLActivityRemoveNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{51} }

func (m *MsgGS2CLActivityRemoveNotice) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *MsgGS2CLActivityRemoveNotice) GetSubId() int32 {
	if m != nil {
		return m.SubId
	}
	return 0
}

// 公会活动通知
type MsgGS2CLGuildActivityNotice struct {
	CleanDayInfos []*GuildActivityCleanDayInfo `protobuf:"bytes,1,rep,name=clean_day_infos,json=cleanDayInfos" json:"clean_day_infos,omitempty"`
}

func (m *MsgGS2CLGuildActivityNotice) Reset()                    { *m = MsgGS2CLGuildActivityNotice{} }
func (m *MsgGS2CLGuildActivityNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLGuildActivityNotice) ProtoMessage()               {}
func (*MsgGS2CLGuildActivityNotice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{52} }

func (m *MsgGS2CLGuildActivityNotice) GetCleanDayInfos() []*GuildActivityCleanDayInfo {
	if m != nil {
		return m.CleanDayInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgGS2CLPlayerAllActivityNotice)(nil), "protomsg.MsgGS2CLPlayerAllActivityNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityRewardedNotice)(nil), "protomsg.MsgGS2CLPlayerActivityRewardedNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityNotice)(nil), "protomsg.MsgGS2CLPlayerActivityNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityDropNotice)(nil), "protomsg.MsgGS2CLPlayerActivityDropNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityExchangeNotice)(nil), "protomsg.MsgGS2CLPlayerActivityExchangeNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityTurntableNotice)(nil), "protomsg.MsgGS2CLPlayerActivityTurntableNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityBeadNotice)(nil), "protomsg.MsgGS2CLPlayerActivityBeadNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityTaskUpdateNotice)(nil), "protomsg.MsgGS2CLPlayerActivityTaskUpdateNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityScoreNotice)(nil), "protomsg.MsgGS2CLPlayerActivityScoreNotice")
	proto.RegisterType((*MsgGS2CLPlayerActivityCleanDayNotice)(nil), "protomsg.MsgGS2CLPlayerActivityCleanDayNotice")
	proto.RegisterType((*MsgCL2GSActivityTaskAwardRequest)(nil), "protomsg.MsgCL2GSActivityTaskAwardRequest")
	proto.RegisterType((*MsgCL2GSActivityTaskAwardReply)(nil), "protomsg.MsgCL2GSActivityTaskAwardReply")
	proto.RegisterType((*MsgCL2GSActivityIndexAwardRequest)(nil), "protomsg.MsgCL2GSActivityIndexAwardRequest")
	proto.RegisterType((*MsgCL2GSActivityIndexAwardReply)(nil), "protomsg.MsgCL2GSActivityIndexAwardReply")
	proto.RegisterType((*MsgCL2GSActivityExchangeRequest)(nil), "protomsg.MsgCL2GSActivityExchangeRequest")
	proto.RegisterType((*MsgCL2GSActivityExchangeReply)(nil), "protomsg.MsgCL2GSActivityExchangeReply")
	proto.RegisterType((*MsgCL2GSActivityTurntableRequest)(nil), "protomsg.MsgCL2GSActivityTurntableRequest")
	proto.RegisterType((*MsgCL2GSActivityTurntableReply)(nil), "protomsg.MsgCL2GSActivityTurntableReply")
	proto.RegisterType((*MsgCL2GSActivityTurntableStageRewardRequest)(nil), "protomsg.MsgCL2GSActivityTurntableStageRewardRequest")
	proto.RegisterType((*MsgGS2CLActivityTurntableStageRewardReply)(nil), "protomsg.MsgGS2CLActivityTurntableStageRewardReply")
	proto.RegisterType((*MsgCL2GSActivityBeadTaskRewardRequest)(nil), "protomsg.MsgCL2GSActivityBeadTaskRewardRequest")
	proto.RegisterType((*MsgCL2GSActivityBeadTaskRewardReply)(nil), "protomsg.MsgCL2GSActivityBeadTaskRewardReply")
	proto.RegisterType((*MsgCL2GSActivityBeadRewardRequest)(nil), "protomsg.MsgCL2GSActivityBeadRewardRequest")
	proto.RegisterType((*MsgCL2GSActivityBeadRewardReply)(nil), "protomsg.MsgCL2GSActivityBeadRewardReply")
	proto.RegisterType((*MsgCL2GSActivityBeadFinalRewardRequest)(nil), "protomsg.MsgCL2GSActivityBeadFinalRewardRequest")
	proto.RegisterType((*MsgCL2GSActivityBeadFinalRewardReply)(nil), "protomsg.MsgCL2GSActivityBeadFinalRewardReply")
	proto.RegisterType((*MsgCL2GSQuestionBankRequest)(nil), "protomsg.MsgCL2GSQuestionBankRequest")
	proto.RegisterType((*MsgGS2CLQuestionBankReply)(nil), "protomsg.MsgGS2CLQuestionBankReply")
	proto.RegisterType((*MsgGS2CLQuestionBankNotice)(nil), "protomsg.MsgGS2CLQuestionBankNotice")
	proto.RegisterType((*MsgCL2GSAnswerQuestionsRequest)(nil), "protomsg.MsgCL2GSAnswerQuestionsRequest")
	proto.RegisterType((*MsgGS2CLAnswerQuestionsReply)(nil), "protomsg.MsgGS2CLAnswerQuestionsReply")
	proto.RegisterType((*MsgCL2GSGiveupAnswerQuestionsRequest)(nil), "protomsg.MsgCL2GSGiveupAnswerQuestionsRequest")
	proto.RegisterType((*MsgGS2CLGiveupAnswerQuestionsReply)(nil), "protomsg.MsgGS2CLGiveupAnswerQuestionsReply")
	proto.RegisterType((*MsgCL2GSHelpAnswerQuestionRequest)(nil), "protomsg.MsgCL2GSHelpAnswerQuestionRequest")
	proto.RegisterType((*MsgGS2CLHelpAnswerQuestionReply)(nil), "protomsg.MsgGS2CLHelpAnswerQuestionReply")
	proto.RegisterType((*MsgCL2GSWhoHelpAnswerQuestionRequest)(nil), "protomsg.MsgCL2GSWhoHelpAnswerQuestionRequest")
	proto.RegisterType((*MsgGS2CLWhoHelpAnswerQuestionReply)(nil), "protomsg.MsgGS2CLWhoHelpAnswerQuestionReply")
	proto.RegisterType((*MsgCL2GSCleanDayGetRewardRequest)(nil), "protomsg.MsgCL2GSCleanDayGetRewardRequest")
	proto.RegisterType((*MsgGS2CLCleanDayGetRewardReply)(nil), "protomsg.MsgGS2CLCleanDayGetRewardReply")
	proto.RegisterType((*MsgCL2GSActivityPeriodRequest)(nil), "protomsg.MsgCL2GSActivityPeriodRequest")
	proto.RegisterType((*MsgGS2CLActivityPeriodReply)(nil), "protomsg.MsgGS2CLActivityPeriodReply")
	proto.RegisterType((*MsgGS2CLActivityRetainedNotice)(nil), "protomsg.MsgGS2CLActivityRetainedNotice")
	proto.RegisterType((*MsgCL2GSActivityRetainedLotteryRequest)(nil), "protomsg.MsgCL2GSActivityRetainedLotteryRequest")
	proto.RegisterType((*MsgGS2CLActivityRetainedLotteryReply)(nil), "protomsg.MsgGS2CLActivityRetainedLotteryReply")
	proto.RegisterType((*MsgCL2GSActivityRetainedReceiveAwardRequest)(nil), "protomsg.MsgCL2GSActivityRetainedReceiveAwardRequest")
	proto.RegisterType((*MsgGS2CLActivityRetainedReceiveAwardReply)(nil), "protomsg.MsgGS2CLActivityRetainedReceiveAwardReply")
	proto.RegisterType((*MsgGS2CLLoginActivityNotice)(nil), "protomsg.MsgGS2CLLoginActivityNotice")
	proto.RegisterType((*MsgCL2GSLLoginActivityReceiveAwardRequest)(nil), "protomsg.MsgCL2GSLLoginActivityReceiveAwardRequest")
	proto.RegisterType((*MsgGS2CLLoginActivityReceiveAwardReply)(nil), "protomsg.MsgGS2CLLoginActivityReceiveAwardReply")
	proto.RegisterType((*MsgGS2CLAllActivityNotice)(nil), "protomsg.MsgGS2CLAllActivityNotice")
	proto.RegisterType((*MsgGS2CLActivityStatusNotice)(nil), "protomsg.MsgGS2CLActivityStatusNotice")
	proto.RegisterType((*MsgGS2CLActivityRemoveNotice)(nil), "protomsg.MsgGS2CLActivityRemoveNotice")
	proto.RegisterType((*MsgGS2CLGuildActivityNotice)(nil), "protomsg.MsgGS2CLGuildActivityNotice")
}

func init() { proto.RegisterFile("activity.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x59, 0x4b, 0x73, 0x1b, 0x45,
	0x10, 0xae, 0xb5, 0x25, 0x59, 0xdb, 0xb6, 0xe4, 0xb0, 0x95, 0x10, 0xc7, 0x89, 0x13, 0x7b, 0x93,
	0x50, 0x21, 0x14, 0x21, 0x65, 0xa8, 0x22, 0x54, 0x78, 0xf9, 0x11, 0x8c, 0x88, 0x49, 0x85, 0x35,
	0x90, 0x14, 0x17, 0x65, 0xb4, 0x3b, 0xb1, 0x17, 0x4b, 0xbb, 0xf2, 0xce, 0xc8, 0xb1, 0x8a, 0x03,
	0x27, 0x8a, 0x13, 0x07, 0xb8, 0xc1, 0x89, 0x2a, 0x38, 0x50, 0x54, 0xf1, 0x0b, 0xe0, 0xc8, 0xaf,
	0xe0, 0x0f, 0xf0, 0x37, 0xa8, 0x79, 0xed, 0x43, 0xda, 0x97, 0x62, 0x71, 0x92, 0x66, 0xb6, 0xfb,
	0xeb, 0xee, 0x6f, 0x7a, 0x7b, 0x7a, 0x66, 0xa1, 0x89, 0x6c, 0xea, 0x1e, 0xbb, 0x74, 0x78, 0xab,
	0x1f, 0xf8, 0xd4, 0x37, 0xea, 0xfc, 0xa7, 0x47, 0xf6, 0x97, 0xcf, 0xf4, 0xc8, 0x7e, 0xdb, 0xf6,
	0x7b, 0x3d, 0xdf, 0x13, 0xcf, 0x96, 0xcf, 0x45, 0x33, 0x6d, 0x8a, 0xc8, 0xa1, 0x9c, 0xbe, 0x10,
	0x9b, 0x4e, 0xa2, 0x99, 0xdf, 0x55, 0xe1, 0xca, 0xc7, 0x64, 0x7f, 0x67, 0x6f, 0x7d, 0x6b, 0xf7,
	0x61, 0x17, 0x0d, 0x71, 0xb0, 0xd1, 0xed, 0x6e, 0x48, 0x99, 0x07, 0x3e, 0x75, 0x6d, 0x6c, 0xac,
	0x43, 0xd5, 0xf5, 0x9e, 0xfa, 0x64, 0x49, 0x5b, 0x9d, 0xbd, 0x31, 0xbf, 0x7e, 0xe9, 0x96, 0xf2,
	0xe0, 0x96, 0xd4, 0x90, 0xe2, 0x2d, 0xef, 0xa9, 0x6f, 0x09, 0x51, 0xe3, 0x6d, 0xa8, 0x07, 0xf8,
	0x19, 0x0a, 0x1c, 0xec, 0x2c, 0xcd, 0x70, 0xb5, 0xd5, 0x2c, 0x35, 0x4b, 0xca, 0x59, 0xa1, 0x86,
	0xf1, 0x1e, 0x80, 0x13, 0xf8, 0xfd, 0xb6, 0x30, 0x3b, 0x9b, 0xaf, 0xbf, 0x1d, 0xf8, 0x7d, 0x6e,
	0x5a, 0x77, 0xe4, 0x3f, 0x62, 0xdc, 0x87, 0x26, 0x3e, 0xb1, 0x0f, 0x90, 0xb7, 0x8f, 0x25, 0x48,
	0x85, 0x83, 0x5c, 0xcb, 0x02, 0xb9, 0x27, 0xa5, 0x39, 0x50, 0x03, 0xc7, 0x46, 0xc4, 0x78, 0x00,
	0x8b, 0x74, 0x10, 0x78, 0x14, 0x75, 0xba, 0x0a, 0xad, 0xca, 0xd1, 0xae, 0x67, 0xa1, 0x7d, 0xaa,
	0xc4, 0x39, 0x5c, 0x93, 0xc6, 0x87, 0x84, 0x45, 0xd7, 0xc1, 0xc8, 0x91, 0x50, 0xb5, 0xfc, 0xe8,
	0x36, 0x31, 0x72, 0x44, 0x74, 0x1d, 0xf9, 0x8f, 0x18, 0xbb, 0xb0, 0x68, 0x77, 0x31, 0xf2, 0xda,
	0x0e, 0x1a, 0x4a, 0x94, 0x7a, 0x7e, 0x78, 0x5b, 0x4c, 0x7c, 0x1b, 0x89, 0x25, 0x6a, 0xd8, 0xb1,
	0x11, 0x31, 0x5a, 0xd0, 0x08, 0x30, 0x45, 0xae, 0x87, 0x85, 0x4b, 0x4b, 0x7a, 0x3e, 0x96, 0x25,
	0x85, 0x39, 0xd6, 0x42, 0x10, 0x1b, 0x19, 0xef, 0x03, 0x74, 0xfd, 0x7d, 0xd7, 0x13, 0x38, 0xc0,
	0x71, 0xd6, 0x46, 0x71, 0x76, 0x99, 0x44, 0x22, 0x67, 0x74, 0xae, 0xc4, 0xfe, 0x9a, 0x0e, 0x5c,
	0x1b, 0x49, 0xc7, 0x91, 0x2c, 0x91, 0x39, 0x19, 0xcf, 0x2f, 0x6d, 0x55, 0x9b, 0x2c, 0xbf, 0xcc,
	0x87, 0x70, 0x29, 0xdd, 0x8a, 0x44, 0xbf, 0x0d, 0x15, 0x1e, 0x81, 0x40, 0xce, 0x4f, 0x78, 0x2e,
	0x69, 0x22, 0x58, 0x4d, 0x47, 0x64, 0xd9, 0x29, 0x51, 0xdf, 0x01, 0x3d, 0xcc, 0xea, 0x22, 0xa7,
	0xc3, 0xa4, 0xae, 0xab, 0xa4, 0x36, 0x9f, 0x64, 0x51, 0xa3, 0x72, 0x57, 0x9a, 0xb9, 0x93, 0x70,
	0xbe, 0x5c, 0xc6, 0x8b, 0x20, 0x3a, 0x70, 0x3d, 0xdd, 0x42, 0x98, 0xcf, 0xd2, 0xc4, 0x5b, 0x09,
	0x13, 0x25, 0x5f, 0x03, 0x61, 0xe3, 0x71, 0x16, 0x51, 0x2c, 0xd1, 0x25, 0xfc, 0x1b, 0x09, 0xf8,
	0xe2, 0x57, 0x43, 0x20, 0x7f, 0xaf, 0xc1, 0x4b, 0x19, 0xee, 0x23, 0x72, 0xf8, 0x59, 0xdf, 0x41,
	0x54, 0xf9, 0xff, 0x1a, 0xe8, 0x3d, 0xe4, 0x8a, 0x1a, 0x29, 0xad, 0x18, 0x91, 0x15, 0x26, 0xbe,
	0x8d, 0x28, 0xb2, 0xea, 0x4c, 0x88, 0x8d, 0x8c, 0x2b, 0x30, 0xaf, 0x0a, 0x67, 0xdb, 0x65, 0x15,
	0x4d, 0xbb, 0xd1, 0xb0, 0x40, 0x4d, 0xb5, 0x1c, 0xe3, 0x1c, 0xd4, 0xc8, 0xa0, 0xc3, 0x9e, 0xcd,
	0xf2, 0x67, 0x55, 0x32, 0xe8, 0xb4, 0x1c, 0xf3, 0x08, 0xd6, 0xd2, 0x5d, 0xda, 0xb3, 0xfd, 0x40,
	0x79, 0x33, 0x02, 0xce, 0xfc, 0xa9, 0x66, 0x80, 0xcf, 0xf0, 0x67, 0x02, 0xdc, 0x38, 0x0b, 0x55,
	0xc2, 0x60, 0xb8, 0xc9, 0x8a, 0x25, 0x06, 0xd9, 0x69, 0xa2, 0x6a, 0xc0, 0x64, 0x69, 0x92, 0xa8,
	0x1c, 0x82, 0x68, 0xc2, 0x97, 0x70, 0x6b, 0x77, 0x7d, 0x67, 0x2f, 0xce, 0xf0, 0x06, 0x7b, 0xb9,
	0x2c, 0x7c, 0x34, 0xc0, 0x84, 0xa6, 0xc5, 0xd4, 0xc8, 0x89, 0x49, 0x11, 0x66, 0x9c, 0x87, 0x39,
	0xb6, 0x28, 0x11, 0x91, 0x35, 0x36, 0x6c, 0x39, 0xe6, 0x5f, 0x1a, 0x5c, 0xce, 0xb1, 0xda, 0xef,
	0x0e, 0xe3, 0xba, 0x5a, 0x5c, 0xd7, 0xb8, 0x09, 0x35, 0xc4, 0xc4, 0x88, 0xdc, 0x8a, 0x62, 0x6b,
	0x6d, 0x61, 0xe2, 0x0f, 0x02, 0x1b, 0x5b, 0x52, 0x62, 0xd4, 0xf1, 0xd9, 0x1c, 0xc7, 0x2b, 0x71,
	0xc7, 0x57, 0x00, 0x70, 0x10, 0xf8, 0x41, 0xdb, 0xf6, 0x1d, 0xbc, 0x64, 0xf3, 0x75, 0xd2, 0xf9,
	0xcc, 0x96, 0xef, 0x60, 0xf3, 0x0b, 0x9e, 0x08, 0x09, 0xef, 0x5b, 0x9e, 0x83, 0x4f, 0x26, 0x23,
	0xed, 0x2c, 0xdb, 0x89, 0x1d, 0x7c, 0xa2, 0x92, 0x8c, 0x0f, 0xcc, 0x7f, 0x35, 0xbe, 0x87, 0x67,
	0x82, 0x33, 0x6e, 0x42, 0x4d, 0x2d, 0xa6, 0x39, 0x5d, 0x62, 0x56, 0x00, 0x8e, 0xdd, 0x7e, 0x5b,
	0x14, 0x59, 0x4e, 0x4e, 0xdd, 0xd2, 0x8f, 0xdd, 0xbe, 0xa8, 0xbf, 0xc6, 0x55, 0x68, 0x78, 0x7e,
	0xd0, 0x43, 0x5d, 0x25, 0x51, 0xe5, 0x12, 0x0b, 0x62, 0x52, 0x0a, 0x15, 0xb0, 0xf8, 0xd5, 0x78,
	0xa0, 0xaa, 0x8c, 0x95, 0xe6, 0xf0, 0x4d, 0x98, 0x0b, 0x84, 0xac, 0x0c, 0x7a, 0x25, 0x0a, 0x7a,
	0x04, 0x8c, 0x17, 0x01, 0x25, 0x6d, 0xfe, 0xad, 0xc1, 0x4a, 0xb6, 0x75, 0x46, 0xf2, 0x54, 0xe9,
	0x8c, 0xf9, 0x59, 0x99, 0xc4, 0xcf, 0x22, 0x0e, 0x1f, 0xa5, 0xbc, 0xbd, 0xaa, 0x4e, 0x97, 0x26,
	0xd1, 0x80, 0x0a, 0x1d, 0xf6, 0xb1, 0xac, 0x47, 0xfc, 0xbf, 0xf9, 0x73, 0xda, 0x1b, 0x1a, 0x21,
	0x33, 0x82, 0x9e, 0x07, 0x37, 0xc6, 0xea, 0x6c, 0x21, 0xab, 0x05, 0xb1, 0x3b, 0xf0, 0x4a, 0xa6,
	0x87, 0x7b, 0x14, 0x31, 0x42, 0x27, 0x7d, 0x1f, 0x6d, 0x7f, 0xe0, 0x51, 0x55, 0xc3, 0xf8, 0xc0,
	0xfc, 0x43, 0x83, 0x97, 0x55, 0x09, 0xce, 0x37, 0x53, 0x8a, 0x93, 0x54, 0x23, 0xd3, 0x64, 0x05,
	0xf1, 0x6d, 0x3f, 0xc1, 0x0a, 0xdb, 0x5a, 0x59, 0x75, 0x9d, 0x90, 0x8f, 0x58, 0x05, 0x9e, 0x49,
	0x54, 0xef, 0xdf, 0x35, 0xb8, 0x5a, 0x64, 0xa3, 0x14, 0x19, 0x59, 0x16, 0xa6, 0xc9, 0x47, 0x4a,
	0xad, 0x66, 0xbe, 0x4e, 0x9e, 0x1b, 0xa2, 0xe2, 0xca, 0x3d, 0x5b, 0xd4, 0xea, 0x5f, 0x52, 0x6a,
	0x75, 0x1c, 0xbc, 0x6c, 0x46, 0x8c, 0x43, 0x4f, 0x93, 0x81, 0x16, 0xef, 0xa4, 0xc6, 0x9c, 0xfc,
	0xc0, 0xf5, 0x54, 0xa5, 0x2e, 0x4b, 0x83, 0xf9, 0x83, 0xc6, 0xfb, 0x91, 0x7c, 0xac, 0x52, 0x51,
	0x4f, 0x52, 0x5d, 0x0b, 0xe2, 0x7b, 0x17, 0x2e, 0x2a, 0x9f, 0x3e, 0x61, 0x61, 0xb8, 0xbe, 0xb7,
	0x89, 0xbc, 0xc3, 0xd2, 0x41, 0x1d, 0xc0, 0x05, 0xf5, 0x82, 0x27, 0xf5, 0x59, 0x20, 0xf7, 0xa1,
	0x79, 0x24, 0x27, 0x49, 0xbb, 0x83, 0xbc, 0xc3, 0xf1, 0x16, 0x2b, 0x4d, 0x59, 0xb4, 0x65, 0x56,
	0x23, 0xd4, 0x65, 0x93, 0xe6, 0x6f, 0xb3, 0xb0, 0x9c, 0x2d, 0xcd, 0x6c, 0xd9, 0x7e, 0xaf, 0xdf,
	0xc5, 0x14, 0xb7, 0x09, 0x45, 0x14, 0x73, 0x5b, 0xcd, 0xb8, 0xad, 0x0d, 0x8f, 0x3c, 0xc3, 0x81,
	0xd2, 0xdd, 0x62, 0xd2, 0x94, 0x55, 0x21, 0x8a, 0xad, 0x86, 0xd2, 0xe5, 0x43, 0xe3, 0x0e, 0xe8,
	0xa1, 0x71, 0xc9, 0xf1, 0x72, 0x84, 0x13, 0xb7, 0x2e, 0x4e, 0x6d, 0xa1, 0xb0, 0x71, 0x03, 0xce,
	0xd8, 0x83, 0xa0, 0x1d, 0x85, 0x1d, 0xee, 0x68, 0x4d, 0x7b, 0x10, 0xda, 0x26, 0x2d, 0x87, 0x51,
	0x6b, 0xfb, 0x41, 0x80, 0x6d, 0xda, 0xb6, 0x3d, 0x2a, 0x5b, 0x28, 0x90, 0x53, 0x5b, 0x1e, 0x35,
	0x2e, 0x40, 0xfd, 0x00, 0x77, 0xfb, 0xfc, 0x69, 0x95, 0x3f, 0x9d, 0x63, 0x63, 0xf6, 0x68, 0x15,
	0x16, 0x5c, 0xc2, 0xcf, 0xbc, 0x01, 0x26, 0x98, 0x2e, 0xd5, 0x78, 0x03, 0x01, 0x2e, 0xd9, 0x46,
	0x43, 0x8b, 0xcd, 0x8c, 0x2e, 0xdc, 0xdc, 0x58, 0x0e, 0xdd, 0x05, 0x9d, 0xa3, 0xf3, 0xce, 0x57,
	0x9c, 0x99, 0x2f, 0xa7, 0x87, 0xf8, 0x21, 0xee, 0xca, 0x03, 0xd8, 0x81, 0xfc, 0x57, 0x94, 0x54,
	0x4f, 0x62, 0xdb, 0x5f, 0x82, 0x73, 0x62, 0x45, 0x3b, 0x33, 0xe2, 0x4f, 0x48, 0x94, 0x56, 0xba,
	0x9c, 0x11, 0xdc, 0xe4, 0x1e, 0x32, 0xcc, 0x1f, 0x67, 0xa2, 0x73, 0xeb, 0x98, 0x09, 0x96, 0x7a,
	0x6b, 0xb0, 0x90, 0x58, 0x03, 0x61, 0x62, 0xfe, 0x28, 0xb6, 0x00, 0x2b, 0x00, 0x2e, 0x69, 0x4b,
	0xc2, 0xb9, 0x8d, 0xba, 0xa5, 0xbb, 0x64, 0x4b, 0x4c, 0x18, 0x37, 0xe1, 0x05, 0x0f, 0x9f, 0xd0,
	0xb4, 0xa5, 0x5c, 0x64, 0x0f, 0xe2, 0x6b, 0x39, 0x9e, 0x7c, 0x95, 0xe7, 0x4f, 0xbe, 0x91, 0xe0,
	0xab, 0x69, 0xed, 0x65, 0x1e, 0xfb, 0x3b, 0x51, 0x99, 0xd9, 0x71, 0x8f, 0xf1, 0xa0, 0x9f, 0xb1,
	0x06, 0x85, 0xef, 0xb6, 0x03, 0xa6, 0xe2, 0x38, 0x03, 0xa8, 0x54, 0xb5, 0x2a, 0x70, 0x77, 0x3f,
	0xda, 0x63, 0x58, 0xa6, 0x25, 0x6d, 0x94, 0xde, 0x63, 0x46, 0xd7, 0x7b, 0x66, 0x6c, 0xbd, 0x4d,
	0x14, 0xdd, 0xef, 0xa5, 0x19, 0x9a, 0x46, 0x2c, 0xdf, 0xc6, 0x4a, 0xfc, 0xa3, 0x03, 0xff, 0x7f,
	0x8d, 0xc7, 0xb8, 0x08, 0x7a, 0x9f, 0x1f, 0x50, 0x55, 0x62, 0x56, 0xac, 0xba, 0x98, 0x68, 0x39,
	0xe6, 0xaf, 0x5a, 0xb4, 0x78, 0x19, 0x9e, 0x94, 0x0a, 0xf8, 0x94, 0x7e, 0x14, 0x57, 0x8a, 0xb0,
	0x05, 0x57, 0xc7, 0xeb, 0x1d, 0x4c, 0x27, 0xec, 0x2f, 0x2e, 0x82, 0x2e, 0x0e, 0x52, 0x91, 0x83,
	0xf2, 0x82, 0xab, 0xe5, 0x98, 0x5f, 0xf3, 0x5a, 0xc4, 0x79, 0x48, 0xb1, 0x50, 0x76, 0xd1, 0x43,
	0x7c, 0xb1, 0x1d, 0x34, 0x2c, 0x5d, 0x19, 0x28, 0xdc, 0x61, 0x37, 0xc7, 0xcf, 0x4a, 0x0f, 0x71,
	0xe0, 0xfa, 0x61, 0x7c, 0x6b, 0xb0, 0x10, 0xb3, 0x2f, 0xee, 0x96, 0x1b, 0xd6, 0x7c, 0xe4, 0x00,
	0x31, 0xfb, 0x7c, 0x97, 0x4e, 0xb4, 0xd1, 0x0a, 0x83, 0x45, 0xb0, 0x0e, 0x55, 0x07, 0x51, 0x94,
	0x72, 0x2d, 0x9d, 0x94, 0xe6, 0xa7, 0x23, 0x21, 0x5a, 0xdc, 0xf9, 0x5d, 0x1e, 0xb5, 0xa8, 0x6e,
	0x3b, 0x27, 0xbb, 0x35, 0x49, 0xdc, 0x91, 0x8a, 0x5b, 0x93, 0x94, 0x9e, 0x4a, 0x49, 0xed, 0xfa,
	0x94, 0xe2, 0x60, 0x58, 0xba, 0x44, 0x7d, 0xa3, 0x45, 0x77, 0x3c, 0x99, 0x58, 0x65, 0x17, 0xb9,
	0x2b, 0x14, 0xa2, 0x2c, 0xd2, 0xe5, 0x4c, 0x71, 0x1e, 0xa7, 0x1c, 0xa7, 0x94, 0x1b, 0x16, 0xb6,
	0xb1, 0x7b, 0x8c, 0x37, 0xa6, 0xd0, 0x32, 0xff, 0x94, 0x72, 0x9c, 0x4a, 0x37, 0x53, 0xf6, 0x04,
	0xe1, 0x52, 0xdc, 0x8b, 0x9d, 0x20, 0xd8, 0x70, 0xf4, 0x72, 0x25, 0xec, 0xaa, 0x0b, 0x28, 0x78,
	0x1c, 0xe5, 0x68, 0xe2, 0x5e, 0x3b, 0xbc, 0x28, 0xad, 0x79, 0xfc, 0x9f, 0x4c, 0x98, 0x12, 0x97,
	0xe1, 0x52, 0xc1, 0xec, 0xf0, 0xa8, 0x39, 0xb9, 0x49, 0xe8, 0x29, 0x52, 0xfb, 0x67, 0xec, 0xca,
	0x34, 0xc7, 0xc6, 0x29, 0x0e, 0x25, 0x77, 0x61, 0x51, 0x56, 0x91, 0x40, 0xf6, 0xe8, 0x39, 0xa7,
	0x93, 0x66, 0x20, 0x0b, 0x94, 0x18, 0x17, 0x71, 0xff, 0x51, 0xd4, 0x85, 0x8f, 0x7f, 0xb4, 0x7a,
	0x35, 0xfa, 0x68, 0xc5, 0x88, 0x3f, 0x3f, 0x5e, 0x1d, 0xf8, 0xd7, 0x0f, 0xf9, 0xbd, 0xca, 0xfc,
	0x47, 0x8b, 0xb5, 0x56, 0xea, 0x8e, 0x96, 0x22, 0x3a, 0x20, 0xa7, 0xbc, 0xa4, 0x5d, 0x01, 0xa0,
	0x6e, 0x0f, 0xb7, 0x3b, 0x78, 0xdf, 0xf5, 0xe4, 0x46, 0xa1, 0xb3, 0x99, 0x4d, 0x36, 0xc1, 0xda,
	0x5d, 0xfe, 0x18, 0x7b, 0xe2, 0xca, 0xac, 0x62, 0xcd, 0xb1, 0xf1, 0x3d, 0xcf, 0x31, 0x6e, 0x43,
	0x8d, 0x70, 0x0f, 0x78, 0x33, 0xd4, 0x5c, 0x5f, 0x1a, 0x0f, 0x41, 0x78, 0x68, 0x49, 0x39, 0xe3,
	0x45, 0xa8, 0xf5, 0x79, 0xc9, 0xe3, 0xad, 0x71, 0xc5, 0x92, 0x23, 0xf3, 0xf3, 0xf1, 0xd8, 0x2c,
	0xdc, 0xf3, 0x8f, 0x4f, 0x79, 0x01, 0x6d, 0x7e, 0x19, 0x25, 0xff, 0xce, 0xc0, 0xed, 0x3a, 0x23,
	0x4b, 0x70, 0x7f, 0xfc, 0x33, 0x95, 0x28, 0xd5, 0x57, 0xa3, 0x48, 0x12, 0x7a, 0x39, 0x5f, 0xa9,
	0x3a, 0x35, 0xae, 0xf2, 0xfa, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x23, 0x1d, 0x11, 0x0f,
	0x1d, 0x00, 0x00,
}
