// Code generated by protoc-gen-go. DO NOT EDIT.
// source: army.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ---------------------------------客户端协议--------------------------------- //
// 所有兵种通知
type MsgGS2CLAllArmyNotice struct {
	Infos                   []*ArmyInfoData `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	UnlockFeatureSpecialIds []uint32        `protobuf:"varint,2,rep,packed,name=unlock_feature_special_ids,json=unlockFeatureSpecialIds" json:"unlock_feature_special_ids,omitempty"`
	UseFeatureSpecialIds    []uint32        `protobuf:"varint,3,rep,packed,name=use_feature_special_ids,json=useFeatureSpecialIds" json:"use_feature_special_ids,omitempty"`
	UseFeatureSpecialCd     int64           `protobuf:"varint,4,opt,name=use_feature_special_cd,json=useFeatureSpecialCd" json:"use_feature_special_cd,omitempty"`
}

func (m *MsgGS2CLAllArmyNotice) Reset()                    { *m = MsgGS2CLAllArmyNotice{} }
func (m *MsgGS2CLAllArmyNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLAllArmyNotice) ProtoMessage()               {}
func (*MsgGS2CLAllArmyNotice) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *MsgGS2CLAllArmyNotice) GetInfos() []*ArmyInfoData {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *MsgGS2CLAllArmyNotice) GetUnlockFeatureSpecialIds() []uint32 {
	if m != nil {
		return m.UnlockFeatureSpecialIds
	}
	return nil
}

func (m *MsgGS2CLAllArmyNotice) GetUseFeatureSpecialIds() []uint32 {
	if m != nil {
		return m.UseFeatureSpecialIds
	}
	return nil
}

func (m *MsgGS2CLAllArmyNotice) GetUseFeatureSpecialCd() int64 {
	if m != nil {
		return m.UseFeatureSpecialCd
	}
	return 0
}

// 更新兵种通知
type MsgGS2CLUpdateArmyNotice struct {
	Info *ArmyInfoData `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLUpdateArmyNotice) Reset()                    { *m = MsgGS2CLUpdateArmyNotice{} }
func (m *MsgGS2CLUpdateArmyNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLUpdateArmyNotice) ProtoMessage()               {}
func (*MsgGS2CLUpdateArmyNotice) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *MsgGS2CLUpdateArmyNotice) GetInfo() *ArmyInfoData {
	if m != nil {
		return m.Info
	}
	return nil
}

// 更新训练通知
type MsgGS2CLUpdateTrainNotice struct {
	Work            *TrainWorkInfo `protobuf:"bytes,1,opt,name=work" json:"work,omitempty"`
	TrainCount      uint64         `protobuf:"varint,2,opt,name=train_count,json=trainCount" json:"train_count,omitempty"`
	UpdateTrainTime uint64         `protobuf:"varint,3,opt,name=update_train_time,json=updateTrainTime" json:"update_train_time,omitempty"`
}

func (m *MsgGS2CLUpdateTrainNotice) Reset()                    { *m = MsgGS2CLUpdateTrainNotice{} }
func (m *MsgGS2CLUpdateTrainNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLUpdateTrainNotice) ProtoMessage()               {}
func (*MsgGS2CLUpdateTrainNotice) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *MsgGS2CLUpdateTrainNotice) GetWork() *TrainWorkInfo {
	if m != nil {
		return m.Work
	}
	return nil
}

func (m *MsgGS2CLUpdateTrainNotice) GetTrainCount() uint64 {
	if m != nil {
		return m.TrainCount
	}
	return 0
}

func (m *MsgGS2CLUpdateTrainNotice) GetUpdateTrainTime() uint64 {
	if m != nil {
		return m.UpdateTrainTime
	}
	return 0
}

// 请求训练
type MsgCL2GSTrainRequest struct {
	Army      *ArmyInfo `protobuf:"bytes,1,opt,name=army" json:"army,omitempty"`
	BarrackId uint32    `protobuf:"varint,2,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSTrainRequest) Reset()                    { *m = MsgCL2GSTrainRequest{} }
func (m *MsgCL2GSTrainRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSTrainRequest) ProtoMessage()               {}
func (*MsgCL2GSTrainRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *MsgCL2GSTrainRequest) GetArmy() *ArmyInfo {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *MsgCL2GSTrainRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLTrainReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLTrainReply) Reset()                    { *m = MsgGS2CLTrainReply{} }
func (m *MsgGS2CLTrainReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLTrainReply) ProtoMessage()               {}
func (*MsgGS2CLTrainReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *MsgGS2CLTrainReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 取消训练
type MsgCL2GSCancelTrainRequest struct {
	BarrackId uint32 `protobuf:"varint,1,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSCancelTrainRequest) Reset()                    { *m = MsgCL2GSCancelTrainRequest{} }
func (m *MsgCL2GSCancelTrainRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSCancelTrainRequest) ProtoMessage()               {}
func (*MsgCL2GSCancelTrainRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *MsgCL2GSCancelTrainRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLCancelTrainReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLCancelTrainReply) Reset()                    { *m = MsgGS2CLCancelTrainReply{} }
func (m *MsgGS2CLCancelTrainReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLCancelTrainReply) ProtoMessage()               {}
func (*MsgGS2CLCancelTrainReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *MsgGS2CLCancelTrainReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 进阶
type MsgCL2GSUpRankRequest struct {
	Army      *ArmyInfo `protobuf:"bytes,1,opt,name=army" json:"army,omitempty"`
	BarrackId uint32    `protobuf:"varint,2,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSUpRankRequest) Reset()                    { *m = MsgCL2GSUpRankRequest{} }
func (m *MsgCL2GSUpRankRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSUpRankRequest) ProtoMessage()               {}
func (*MsgCL2GSUpRankRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *MsgCL2GSUpRankRequest) GetArmy() *ArmyInfo {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *MsgCL2GSUpRankRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLUpRankReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLUpRankReply) Reset()                    { *m = MsgGS2CLUpRankReply{} }
func (m *MsgGS2CLUpRankReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLUpRankReply) ProtoMessage()               {}
func (*MsgGS2CLUpRankReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *MsgGS2CLUpRankReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 解散
type MsgCL2GSDisbandRequest struct {
	Army *ArmyInfo `protobuf:"bytes,1,opt,name=army" json:"army,omitempty"`
}

func (m *MsgCL2GSDisbandRequest) Reset()                    { *m = MsgCL2GSDisbandRequest{} }
func (m *MsgCL2GSDisbandRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSDisbandRequest) ProtoMessage()               {}
func (*MsgCL2GSDisbandRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *MsgCL2GSDisbandRequest) GetArmy() *ArmyInfo {
	if m != nil {
		return m.Army
	}
	return nil
}

type MsgGS2CLDisbandReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLDisbandReply) Reset()                    { *m = MsgGS2CLDisbandReply{} }
func (m *MsgGS2CLDisbandReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLDisbandReply) ProtoMessage()               {}
func (*MsgGS2CLDisbandReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *MsgGS2CLDisbandReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 立即训练
type MsgCL2GSInstantTrainRequest struct {
	Army      *ArmyInfo `protobuf:"bytes,1,opt,name=army" json:"army,omitempty"`
	BarrackId uint32    `protobuf:"varint,2,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSInstantTrainRequest) Reset()                    { *m = MsgCL2GSInstantTrainRequest{} }
func (m *MsgCL2GSInstantTrainRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSInstantTrainRequest) ProtoMessage()               {}
func (*MsgCL2GSInstantTrainRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{11} }

func (m *MsgCL2GSInstantTrainRequest) GetArmy() *ArmyInfo {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *MsgCL2GSInstantTrainRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLInstantTrainReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLInstantTrainReply) Reset()                    { *m = MsgGS2CLInstantTrainReply{} }
func (m *MsgGS2CLInstantTrainReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLInstantTrainReply) ProtoMessage()               {}
func (*MsgGS2CLInstantTrainReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{12} }

func (m *MsgGS2CLInstantTrainReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 收割
type MsgCL2GSDealArmyRequest struct {
	BarrackId uint32 `protobuf:"varint,1,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSDealArmyRequest) Reset()                    { *m = MsgCL2GSDealArmyRequest{} }
func (m *MsgCL2GSDealArmyRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSDealArmyRequest) ProtoMessage()               {}
func (*MsgCL2GSDealArmyRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{13} }

func (m *MsgCL2GSDealArmyRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLDealArmyReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLDealArmyReply) Reset()                    { *m = MsgGS2CLDealArmyReply{} }
func (m *MsgGS2CLDealArmyReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLDealArmyReply) ProtoMessage()               {}
func (*MsgGS2CLDealArmyReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{14} }

func (m *MsgGS2CLDealArmyReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 立即进阶
type MsgCL2GSInstantUpRankRequest struct {
	Army      *ArmyInfo `protobuf:"bytes,1,opt,name=army" json:"army,omitempty"`
	BarrackId uint32    `protobuf:"varint,2,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSInstantUpRankRequest) Reset()                    { *m = MsgCL2GSInstantUpRankRequest{} }
func (m *MsgCL2GSInstantUpRankRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSInstantUpRankRequest) ProtoMessage()               {}
func (*MsgCL2GSInstantUpRankRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{15} }

func (m *MsgCL2GSInstantUpRankRequest) GetArmy() *ArmyInfo {
	if m != nil {
		return m.Army
	}
	return nil
}

func (m *MsgCL2GSInstantUpRankRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLInstantUpRankReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLInstantUpRankReply) Reset()                    { *m = MsgGS2CLInstantUpRankReply{} }
func (m *MsgGS2CLInstantUpRankReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLInstantUpRankReply) ProtoMessage()               {}
func (*MsgGS2CLInstantUpRankReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{16} }

func (m *MsgGS2CLInstantUpRankReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 立即加速完成
type MsgCL2GSInstantSpeedUpRequest struct {
	BarrackId uint32 `protobuf:"varint,1,opt,name=barrack_id,json=barrackId" json:"barrack_id,omitempty"`
}

func (m *MsgCL2GSInstantSpeedUpRequest) Reset()                    { *m = MsgCL2GSInstantSpeedUpRequest{} }
func (m *MsgCL2GSInstantSpeedUpRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSInstantSpeedUpRequest) ProtoMessage()               {}
func (*MsgCL2GSInstantSpeedUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{17} }

func (m *MsgCL2GSInstantSpeedUpRequest) GetBarrackId() uint32 {
	if m != nil {
		return m.BarrackId
	}
	return 0
}

type MsgGS2CLInstantSpeedUpReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLInstantSpeedUpReply) Reset()                    { *m = MsgGS2CLInstantSpeedUpReply{} }
func (m *MsgGS2CLInstantSpeedUpReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLInstantSpeedUpReply) ProtoMessage()               {}
func (*MsgGS2CLInstantSpeedUpReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{18} }

func (m *MsgGS2CLInstantSpeedUpReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 解锁特种兵
type MsgCL2GSDeblockingFeatureTroopRequest struct {
	SpecialId uint32 `protobuf:"varint,1,opt,name=special_id,json=specialId" json:"special_id,omitempty"`
}

func (m *MsgCL2GSDeblockingFeatureTroopRequest) Reset()         { *m = MsgCL2GSDeblockingFeatureTroopRequest{} }
func (m *MsgCL2GSDeblockingFeatureTroopRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSDeblockingFeatureTroopRequest) ProtoMessage()    {}
func (*MsgCL2GSDeblockingFeatureTroopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{19}
}

func (m *MsgCL2GSDeblockingFeatureTroopRequest) GetSpecialId() uint32 {
	if m != nil {
		return m.SpecialId
	}
	return 0
}

type MsgGS2CLDeblockingFeatureTroopReply struct {
	SpecialId uint32 `protobuf:"varint,1,opt,name=special_id,json=specialId" json:"special_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLDeblockingFeatureTroopReply) Reset()         { *m = MsgGS2CLDeblockingFeatureTroopReply{} }
func (m *MsgGS2CLDeblockingFeatureTroopReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLDeblockingFeatureTroopReply) ProtoMessage()    {}
func (*MsgGS2CLDeblockingFeatureTroopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{20}
}

func (m *MsgGS2CLDeblockingFeatureTroopReply) GetSpecialId() uint32 {
	if m != nil {
		return m.SpecialId
	}
	return 0
}

func (m *MsgGS2CLDeblockingFeatureTroopReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 选择使用特种兵
type MsgCL2GSUseFeatureToopRequest struct {
	SpecialId uint32 `protobuf:"varint,1,opt,name=special_id,json=specialId" json:"special_id,omitempty"`
}

func (m *MsgCL2GSUseFeatureToopRequest) Reset()                    { *m = MsgCL2GSUseFeatureToopRequest{} }
func (m *MsgCL2GSUseFeatureToopRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSUseFeatureToopRequest) ProtoMessage()               {}
func (*MsgCL2GSUseFeatureToopRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{21} }

func (m *MsgCL2GSUseFeatureToopRequest) GetSpecialId() uint32 {
	if m != nil {
		return m.SpecialId
	}
	return 0
}

type MsgGS2CLUseFeatureToopReply struct {
	SpecialId uint32 `protobuf:"varint,1,opt,name=special_id,json=specialId" json:"special_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLUseFeatureToopReply) Reset()                    { *m = MsgGS2CLUseFeatureToopReply{} }
func (m *MsgGS2CLUseFeatureToopReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLUseFeatureToopReply) ProtoMessage()               {}
func (*MsgGS2CLUseFeatureToopReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{22} }

func (m *MsgGS2CLUseFeatureToopReply) GetSpecialId() uint32 {
	if m != nil {
		return m.SpecialId
	}
	return 0
}

func (m *MsgGS2CLUseFeatureToopReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgGS2CLAllArmyNotice)(nil), "protomsg.MsgGS2CLAllArmyNotice")
	proto.RegisterType((*MsgGS2CLUpdateArmyNotice)(nil), "protomsg.MsgGS2CLUpdateArmyNotice")
	proto.RegisterType((*MsgGS2CLUpdateTrainNotice)(nil), "protomsg.MsgGS2CLUpdateTrainNotice")
	proto.RegisterType((*MsgCL2GSTrainRequest)(nil), "protomsg.MsgCL2GSTrainRequest")
	proto.RegisterType((*MsgGS2CLTrainReply)(nil), "protomsg.MsgGS2CLTrainReply")
	proto.RegisterType((*MsgCL2GSCancelTrainRequest)(nil), "protomsg.MsgCL2GSCancelTrainRequest")
	proto.RegisterType((*MsgGS2CLCancelTrainReply)(nil), "protomsg.MsgGS2CLCancelTrainReply")
	proto.RegisterType((*MsgCL2GSUpRankRequest)(nil), "protomsg.MsgCL2GSUpRankRequest")
	proto.RegisterType((*MsgGS2CLUpRankReply)(nil), "protomsg.MsgGS2CLUpRankReply")
	proto.RegisterType((*MsgCL2GSDisbandRequest)(nil), "protomsg.MsgCL2GSDisbandRequest")
	proto.RegisterType((*MsgGS2CLDisbandReply)(nil), "protomsg.MsgGS2CLDisbandReply")
	proto.RegisterType((*MsgCL2GSInstantTrainRequest)(nil), "protomsg.MsgCL2GSInstantTrainRequest")
	proto.RegisterType((*MsgGS2CLInstantTrainReply)(nil), "protomsg.MsgGS2CLInstantTrainReply")
	proto.RegisterType((*MsgCL2GSDealArmyRequest)(nil), "protomsg.MsgCL2GSDealArmyRequest")
	proto.RegisterType((*MsgGS2CLDealArmyReply)(nil), "protomsg.MsgGS2CLDealArmyReply")
	proto.RegisterType((*MsgCL2GSInstantUpRankRequest)(nil), "protomsg.MsgCL2GSInstantUpRankRequest")
	proto.RegisterType((*MsgGS2CLInstantUpRankReply)(nil), "protomsg.MsgGS2CLInstantUpRankReply")
	proto.RegisterType((*MsgCL2GSInstantSpeedUpRequest)(nil), "protomsg.MsgCL2GSInstantSpeedUpRequest")
	proto.RegisterType((*MsgGS2CLInstantSpeedUpReply)(nil), "protomsg.MsgGS2CLInstantSpeedUpReply")
	proto.RegisterType((*MsgCL2GSDeblockingFeatureTroopRequest)(nil), "protomsg.MsgCL2GSDeblockingFeatureTroopRequest")
	proto.RegisterType((*MsgGS2CLDeblockingFeatureTroopReply)(nil), "protomsg.MsgGS2CLDeblockingFeatureTroopReply")
	proto.RegisterType((*MsgCL2GSUseFeatureToopRequest)(nil), "protomsg.MsgCL2GSUseFeatureToopRequest")
	proto.RegisterType((*MsgGS2CLUseFeatureToopReply)(nil), "protomsg.MsgGS2CLUseFeatureToopReply")
}

func init() { proto.RegisterFile("army.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xef, 0x6b, 0xd3, 0x4e,
	0x18, 0x27, 0x6b, 0xf7, 0xe5, 0xbb, 0x67, 0x0c, 0x35, 0x9b, 0x6b, 0x9c, 0x0e, 0x43, 0x44, 0x29,
	0x53, 0xfa, 0xa2, 0x75, 0xa2, 0x4e, 0xc4, 0x91, 0xd1, 0x51, 0xd8, 0x7c, 0x91, 0xb6, 0xf8, 0x42,
	0x34, 0x5c, 0x73, 0xd7, 0x12, 0x9a, 0xdc, 0xc5, 0xbb, 0x0b, 0xb2, 0x3f, 0xc4, 0x7f, 0xd3, 0xbf,
	0x41, 0x72, 0x49, 0x7a, 0xfd, 0xc5, 0x48, 0xd1, 0xbd, 0x0a, 0x3c, 0xf7, 0x7c, 0x7e, 0x3c, 0x3f,
	0xf2, 0x00, 0x20, 0x1e, 0xdf, 0xb4, 0x12, 0xce, 0x24, 0x33, 0xff, 0x57, 0x9f, 0x58, 0x4c, 0x8e,
	0xee, 0xc7, 0x62, 0xe2, 0x07, 0x2c, 0x8e, 0x19, 0xcd, 0xdf, 0x9c, 0xdf, 0x06, 0x3c, 0xbc, 0x16,
	0x93, 0xcb, 0x7e, 0xdb, 0xbd, 0x3a, 0x8f, 0xa2, 0x73, 0x1e, 0xdf, 0x7c, 0x66, 0x32, 0x0c, 0x88,
	0xf9, 0x0a, 0xb6, 0x43, 0x3a, 0x66, 0xc2, 0x32, 0xec, 0x5a, 0x73, 0xb7, 0x7d, 0xd8, 0x2a, 0x59,
	0x5a, 0x59, 0x52, 0x8f, 0x8e, 0xd9, 0x05, 0x92, 0xc8, 0xcb, 0x93, 0xcc, 0x33, 0x38, 0x4a, 0x69,
	0xc4, 0x82, 0xa9, 0x3f, 0x26, 0x48, 0xa6, 0x9c, 0xf8, 0x22, 0x21, 0x41, 0x88, 0x22, 0x3f, 0xc4,
	0xc2, 0xda, 0xb2, 0x6b, 0xcd, 0x3d, 0xaf, 0x91, 0x67, 0x74, 0xf3, 0x84, 0x7e, 0xfe, 0xde, 0xc3,
	0xc2, 0x3c, 0x85, 0x46, 0x2a, 0xc8, 0x5a, 0x64, 0x4d, 0x21, 0x0f, 0x52, 0x41, 0x56, 0x61, 0x1d,
	0x38, 0x5c, 0x07, 0x0b, 0xb0, 0x55, 0xb7, 0x8d, 0x66, 0xcd, 0xdb, 0x5f, 0x41, 0xb9, 0xd8, 0xe9,
	0x82, 0x55, 0xd6, 0x3b, 0x4c, 0x30, 0x92, 0x64, 0xae, 0xe4, 0x13, 0xa8, 0x67, 0xd5, 0x58, 0x86,
	0x6d, 0xdc, 0x52, 0xb1, 0xca, 0x71, 0x7e, 0x19, 0xf0, 0x68, 0x91, 0x68, 0xc0, 0x51, 0x48, 0x0b,
	0xa6, 0x97, 0x50, 0xff, 0xc9, 0xf8, 0xb4, 0x60, 0x6a, 0x68, 0x26, 0x95, 0xf4, 0x85, 0xf1, 0x69,
	0x46, 0xe7, 0xa9, 0x24, 0xf3, 0x29, 0xec, 0xca, 0x2c, 0xec, 0x07, 0x2c, 0xa5, 0xd2, 0xda, 0xb2,
	0x8d, 0x66, 0xdd, 0x03, 0x15, 0x72, 0xb3, 0x88, 0x79, 0x02, 0x0f, 0x52, 0x25, 0xe1, 0xe7, 0x79,
	0x32, 0x8c, 0x89, 0x55, 0x53, 0x69, 0xf7, 0x52, 0xad, 0x3d, 0x08, 0x63, 0xe2, 0x7c, 0x83, 0x83,
	0x6b, 0x31, 0x71, 0xaf, 0xda, 0x97, 0x7d, 0x15, 0xf4, 0xc8, 0x8f, 0x94, 0x08, 0x69, 0xbe, 0x80,
	0x7a, 0xb6, 0x12, 0x85, 0x23, 0x73, 0xb5, 0x36, 0x4f, 0xbd, 0x9b, 0xc7, 0x00, 0x23, 0xc4, 0x39,
	0x0a, 0xa6, 0x7e, 0x88, 0x95, 0x97, 0x3d, 0x6f, 0xa7, 0x88, 0xf4, 0xb0, 0xd3, 0x01, 0xb3, 0xac,
	0xba, 0xa0, 0x4f, 0x22, 0x05, 0x22, 0x9c, 0x33, 0xee, 0x07, 0x0c, 0x13, 0x2b, 0xb0, 0x8d, 0xe6,
	0xb6, 0xb7, 0xa3, 0x22, 0x2e, 0xc3, 0xc4, 0x39, 0x83, 0xa3, 0xd2, 0x93, 0x8b, 0x68, 0x40, 0xa2,
	0x05, 0x67, 0x8b, 0x8a, 0xc6, 0xb2, 0xe2, 0x3b, 0x3d, 0xb0, 0x05, 0x70, 0x05, 0xdd, 0xef, 0x6a,
	0xb7, 0x95, 0xee, 0x30, 0xf1, 0x10, 0x9d, 0xfe, 0xe3, 0x66, 0xbc, 0x86, 0x7d, 0xbd, 0x02, 0x39,
	0x7f, 0x05, 0x57, 0x9f, 0xe0, 0xb0, 0x74, 0x75, 0x11, 0x8a, 0x11, 0xa2, 0x78, 0x43, 0x5b, 0xce,
	0xa9, 0x9a, 0xb1, 0xd2, 0x9d, 0x31, 0x54, 0x10, 0xc6, 0xf0, 0xb8, 0x14, 0xee, 0x51, 0x21, 0x11,
	0x95, 0x77, 0xb1, 0x21, 0xef, 0xf5, 0x7f, 0xb1, 0xa8, 0x52, 0xc1, 0xe1, 0x5b, 0x68, 0xcc, 0x5a,
	0x43, 0x90, 0xba, 0x46, 0x15, 0xb7, 0xe4, 0x8d, 0x3e, 0x63, 0x1a, 0x59, 0x41, 0x91, 0xc0, 0x93,
	0xa5, 0x9e, 0xdc, 0xc9, 0xa6, 0xe4, 0x7f, 0xc0, 0x7c, 0x53, 0x36, 0x58, 0x98, 0x8f, 0x70, 0xbc,
	0xe4, 0xb1, 0x9f, 0x10, 0x82, 0x87, 0x49, 0xc5, 0xde, 0x7c, 0x50, 0x73, 0x9f, 0x17, 0x9f, 0xe1,
	0x2b, 0xa8, 0x77, 0xe1, 0xb9, 0x9e, 0xc9, 0x28, 0x3b, 0xe0, 0x21, 0x9d, 0x14, 0x67, 0x75, 0xc0,
	0x19, 0x9b, 0x77, 0xa1, 0x2f, 0x77, 0xe9, 0x42, 0x94, 0xe7, 0xda, 0x09, 0xe0, 0x99, 0x9e, 0xd0,
	0x7a, 0x9e, 0xc2, 0xcd, 0x2d, 0x2c, 0x1b, 0xb4, 0x6a, 0x38, 0x3b, 0xfe, 0x83, 0xea, 0x26, 0xbf,
	0xea, 0x56, 0x2d, 0xe3, 0xff, 0xda, 0xdc, 0xe8, 0x3f, 0xb5, 0x3c, 0x9d, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x6e, 0x2e, 0x13, 0x61, 0x9c, 0x07, 0x00, 0x00,
}
