// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ClientLocalDataType int32

const (
	ClientLocalDataType_ClientLocalDataType_None               ClientLocalDataType = 0
	ClientLocalDataType_ClientLocalDataType_CastleShowRecorder ClientLocalDataType = 1
	ClientLocalDataType_ClientLocalDataType_Max                ClientLocalDataType = 2
)

var ClientLocalDataType_name = map[int32]string{
	0: "ClientLocalDataType_None",
	1: "ClientLocalDataType_CastleShowRecorder",
	2: "ClientLocalDataType_Max",
}
var ClientLocalDataType_value = map[string]int32{
	"ClientLocalDataType_None":               0,
	"ClientLocalDataType_CastleShowRecorder": 1,
	"ClientLocalDataType_Max":                2,
}

func (x ClientLocalDataType) String() string {
	return proto.EnumName(ClientLocalDataType_name, int32(x))
}
func (ClientLocalDataType) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type MsgGS2CLPlayerBaseNotice struct {
	PlayerId           uint64    `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Name               string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level              uint32    `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Exp                uint32    `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Oil                uint64    `protobuf:"varint,8,opt,name=oil" json:"oil,omitempty"`
	Emoney             uint64    `protobuf:"varint,9,opt,name=emoney" json:"emoney,omitempty"`
	Language           uint32    `protobuf:"varint,10,opt,name=language" json:"language,omitempty"`
	ClientLocalDatas   []string  `protobuf:"bytes,11,rep,name=client_local_datas,json=clientLocalDatas" json:"client_local_datas,omitempty"`
	AreaId             uint32    `protobuf:"varint,12,opt,name=area_id,json=areaId" json:"area_id,omitempty"`
	Currencies         []uint64  `protobuf:"varint,13,rep,packed,name=currencies" json:"currencies,omitempty"`
	Food               uint64    `protobuf:"varint,14,opt,name=food" json:"food,omitempty"`
	Wood               uint64    `protobuf:"varint,15,opt,name=wood" json:"wood,omitempty"`
	Steel              uint64    `protobuf:"varint,16,opt,name=steel" json:"steel,omitempty"`
	Displayphotos      []uint32  `protobuf:"varint,117,rep,packed,name=displayphotos" json:"displayphotos,omitempty"`
	Head               string    `protobuf:"bytes,18,opt,name=head" json:"head,omitempty"`
	Power              uint64    `protobuf:"varint,19,opt,name=power" json:"power,omitempty"`
	DisplayPhotoFrame  []uint32  `protobuf:"varint,120,rep,packed,name=display_photo_frame,json=displayPhotoFrame" json:"display_photo_frame,omitempty"`
	CollectionCount    uint64    `protobuf:"varint,21,opt,name=collection_count,json=collectionCount" json:"collection_count,omitempty"`
	KillCount          uint64    `protobuf:"varint,22,opt,name=kill_count,json=killCount" json:"kill_count,omitempty"`
	CastlePos          *Vector2D `protobuf:"bytes,23,opt,name=castle_pos,json=castlePos" json:"castle_pos,omitempty"`
	ServerStartTime    uint64    `protobuf:"varint,24,opt,name=server_start_time,json=serverStartTime" json:"server_start_time,omitempty"`
	CampId             uint32    `protobuf:"varint,25,opt,name=camp_id,json=campId" json:"camp_id,omitempty"`
	OriginalCampId     uint32    `protobuf:"varint,26,opt,name=original_camp_id,json=originalCampId" json:"original_camp_id,omitempty"`
	KingdomTitle       uint32    `protobuf:"varint,27,opt,name=kingdom_title,json=kingdomTitle" json:"kingdom_title,omitempty"`
	RegisterTime       int64     `protobuf:"varint,28,opt,name=register_time,json=registerTime" json:"register_time,omitempty"`
	EnterKingdomTime   int64     `protobuf:"varint,29,opt,name=enter_kingdom_time,json=enterKingdomTime" json:"enter_kingdom_time,omitempty"`
	Evaluation         bool      `protobuf:"varint,30,opt,name=evaluation" json:"evaluation,omitempty"`
	FirstJoinGuildTime int64     `protobuf:"varint,31,opt,name=first_join_guild_time,json=firstJoinGuildTime" json:"first_join_guild_time,omitempty"`
	CreateAccountDay   uint32    `protobuf:"varint,32,opt,name=create_account_day,json=createAccountDay" json:"create_account_day,omitempty"`
	SafeOil            uint64    `protobuf:"varint,33,opt,name=safe_oil,json=safeOil" json:"safe_oil,omitempty"`
	SafeFood           uint64    `protobuf:"varint,34,opt,name=safe_food,json=safeFood" json:"safe_food,omitempty"`
	SafeWood           uint64    `protobuf:"varint,35,opt,name=safe_wood,json=safeWood" json:"safe_wood,omitempty"`
	SafeSteel          uint64    `protobuf:"varint,36,opt,name=safe_steel,json=safeSteel" json:"safe_steel,omitempty"`
}

func (m *MsgGS2CLPlayerBaseNotice) Reset()                    { *m = MsgGS2CLPlayerBaseNotice{} }
func (m *MsgGS2CLPlayerBaseNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerBaseNotice) ProtoMessage()               {}
func (*MsgGS2CLPlayerBaseNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *MsgGS2CLPlayerBaseNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgGS2CLPlayerBaseNotice) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetOil() uint64 {
	if m != nil {
		return m.Oil
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetEmoney() uint64 {
	if m != nil {
		return m.Emoney
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetLanguage() uint32 {
	if m != nil {
		return m.Language
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetClientLocalDatas() []string {
	if m != nil {
		return m.ClientLocalDatas
	}
	return nil
}

func (m *MsgGS2CLPlayerBaseNotice) GetAreaId() uint32 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetCurrencies() []uint64 {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *MsgGS2CLPlayerBaseNotice) GetFood() uint64 {
	if m != nil {
		return m.Food
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetWood() uint64 {
	if m != nil {
		return m.Wood
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetSteel() uint64 {
	if m != nil {
		return m.Steel
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetDisplayphotos() []uint32 {
	if m != nil {
		return m.Displayphotos
	}
	return nil
}

func (m *MsgGS2CLPlayerBaseNotice) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *MsgGS2CLPlayerBaseNotice) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetDisplayPhotoFrame() []uint32 {
	if m != nil {
		return m.DisplayPhotoFrame
	}
	return nil
}

func (m *MsgGS2CLPlayerBaseNotice) GetCollectionCount() uint64 {
	if m != nil {
		return m.CollectionCount
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetKillCount() uint64 {
	if m != nil {
		return m.KillCount
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetCastlePos() *Vector2D {
	if m != nil {
		return m.CastlePos
	}
	return nil
}

func (m *MsgGS2CLPlayerBaseNotice) GetServerStartTime() uint64 {
	if m != nil {
		return m.ServerStartTime
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetCampId() uint32 {
	if m != nil {
		return m.CampId
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetOriginalCampId() uint32 {
	if m != nil {
		return m.OriginalCampId
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetKingdomTitle() uint32 {
	if m != nil {
		return m.KingdomTitle
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetRegisterTime() int64 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetEnterKingdomTime() int64 {
	if m != nil {
		return m.EnterKingdomTime
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetEvaluation() bool {
	if m != nil {
		return m.Evaluation
	}
	return false
}

func (m *MsgGS2CLPlayerBaseNotice) GetFirstJoinGuildTime() int64 {
	if m != nil {
		return m.FirstJoinGuildTime
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetCreateAccountDay() uint32 {
	if m != nil {
		return m.CreateAccountDay
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetSafeOil() uint64 {
	if m != nil {
		return m.SafeOil
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetSafeFood() uint64 {
	if m != nil {
		return m.SafeFood
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetSafeWood() uint64 {
	if m != nil {
		return m.SafeWood
	}
	return 0
}

func (m *MsgGS2CLPlayerBaseNotice) GetSafeSteel() uint64 {
	if m != nil {
		return m.SafeSteel
	}
	return 0
}

type MsgCL2GSRenameRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	UseMoney bool   `protobuf:"varint,2,opt,name=use_money,json=useMoney" json:"use_money,omitempty"`
}

func (m *MsgCL2GSRenameRequest) Reset()                    { *m = MsgCL2GSRenameRequest{} }
func (m *MsgCL2GSRenameRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSRenameRequest) ProtoMessage()               {}
func (*MsgCL2GSRenameRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *MsgCL2GSRenameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCL2GSRenameRequest) GetUseMoney() bool {
	if m != nil {
		return m.UseMoney
	}
	return false
}

type MsgGS2CLRenameReply struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLRenameReply) Reset()                    { *m = MsgGS2CLRenameReply{} }
func (m *MsgGS2CLRenameReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLRenameReply) ProtoMessage()               {}
func (*MsgGS2CLRenameReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *MsgGS2CLRenameReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgGS2CLRenameReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 心跳包
type MsgCL2GSKeepLiveRequest struct {
}

func (m *MsgCL2GSKeepLiveRequest) Reset()                    { *m = MsgCL2GSKeepLiveRequest{} }
func (m *MsgCL2GSKeepLiveRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSKeepLiveRequest) ProtoMessage()               {}
func (*MsgCL2GSKeepLiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

type MsgGS2CLKeepLiveReply struct {
}

func (m *MsgGS2CLKeepLiveReply) Reset()                    { *m = MsgGS2CLKeepLiveReply{} }
func (m *MsgGS2CLKeepLiveReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLKeepLiveReply) ProtoMessage()               {}
func (*MsgGS2CLKeepLiveReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

// 服务器时间同步通知
type MsgGS2CLServerTimeNotice struct {
	ServerTime int64 `protobuf:"varint,1,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
}

func (m *MsgGS2CLServerTimeNotice) Reset()                    { *m = MsgGS2CLServerTimeNotice{} }
func (m *MsgGS2CLServerTimeNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLServerTimeNotice) ProtoMessage()               {}
func (*MsgGS2CLServerTimeNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *MsgGS2CLServerTimeNotice) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

// 每天第一次登陆通知
type MsgGS2CLDayResetNotice struct {
	LoginDays uint32 `protobuf:"varint,1,opt,name=login_days,json=loginDays" json:"login_days,omitempty"`
}

func (m *MsgGS2CLDayResetNotice) Reset()                    { *m = MsgGS2CLDayResetNotice{} }
func (m *MsgGS2CLDayResetNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLDayResetNotice) ProtoMessage()               {}
func (*MsgGS2CLDayResetNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *MsgGS2CLDayResetNotice) GetLoginDays() uint32 {
	if m != nil {
		return m.LoginDays
	}
	return 0
}

type PlayerAttribute struct {
	Type    uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	SubType uint32 `protobuf:"varint,2,opt,name=sub_type,json=subType" json:"sub_type,omitempty"`
	Value   uint64 `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *PlayerAttribute) Reset()                    { *m = PlayerAttribute{} }
func (m *PlayerAttribute) String() string            { return proto.CompactTextString(m) }
func (*PlayerAttribute) ProtoMessage()               {}
func (*PlayerAttribute) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *PlayerAttribute) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PlayerAttribute) GetSubType() uint32 {
	if m != nil {
		return m.SubType
	}
	return 0
}

func (m *PlayerAttribute) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 玩家属性变化通知
type MsgGS2CLPlayerAttribute struct {
	Attributes []*PlayerAttribute `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty"`
}

func (m *MsgGS2CLPlayerAttribute) Reset()                    { *m = MsgGS2CLPlayerAttribute{} }
func (m *MsgGS2CLPlayerAttribute) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerAttribute) ProtoMessage()               {}
func (*MsgGS2CLPlayerAttribute) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *MsgGS2CLPlayerAttribute) GetAttributes() []*PlayerAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// 行动力信息
type MsgGS2CLPlayerAPData struct {
	Ap          uint32 `protobuf:"varint,1,opt,name=ap" json:"ap,omitempty"`
	LastAddTime int64  `protobuf:"varint,2,opt,name=last_add_time,json=lastAddTime" json:"last_add_time,omitempty"`
}

func (m *MsgGS2CLPlayerAPData) Reset()                    { *m = MsgGS2CLPlayerAPData{} }
func (m *MsgGS2CLPlayerAPData) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerAPData) ProtoMessage()               {}
func (*MsgGS2CLPlayerAPData) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *MsgGS2CLPlayerAPData) GetAp() uint32 {
	if m != nil {
		return m.Ap
	}
	return 0
}

func (m *MsgGS2CLPlayerAPData) GetLastAddTime() int64 {
	if m != nil {
		return m.LastAddTime
	}
	return 0
}

// 设置语言请求
type MsgCL2GSSetLanguageTypeRequest struct {
	LanguageType uint32 `protobuf:"varint,1,opt,name=language_type,json=languageType" json:"language_type,omitempty"`
}

func (m *MsgCL2GSSetLanguageTypeRequest) Reset()                    { *m = MsgCL2GSSetLanguageTypeRequest{} }
func (m *MsgCL2GSSetLanguageTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSSetLanguageTypeRequest) ProtoMessage()               {}
func (*MsgCL2GSSetLanguageTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *MsgCL2GSSetLanguageTypeRequest) GetLanguageType() uint32 {
	if m != nil {
		return m.LanguageType
	}
	return 0
}

// 设置语言响应
type MsgGS2CLSetLanguageTypeReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLSetLanguageTypeReply) Reset()                    { *m = MsgGS2CLSetLanguageTypeReply{} }
func (m *MsgGS2CLSetLanguageTypeReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLSetLanguageTypeReply) ProtoMessage()               {}
func (*MsgGS2CLSetLanguageTypeReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *MsgGS2CLSetLanguageTypeReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MsgCL2GSUpdateClientLocalDataRequest struct {
	Type ClientLocalDataType `protobuf:"varint,1,opt,name=type,enum=protomsg.ClientLocalDataType" json:"type,omitempty"`
	Data string              `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *MsgCL2GSUpdateClientLocalDataRequest) Reset()         { *m = MsgCL2GSUpdateClientLocalDataRequest{} }
func (m *MsgCL2GSUpdateClientLocalDataRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSUpdateClientLocalDataRequest) ProtoMessage()    {}
func (*MsgCL2GSUpdateClientLocalDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{12}
}

func (m *MsgCL2GSUpdateClientLocalDataRequest) GetType() ClientLocalDataType {
	if m != nil {
		return m.Type
	}
	return ClientLocalDataType_ClientLocalDataType_None
}

func (m *MsgCL2GSUpdateClientLocalDataRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// 设置头像请求
type MsgCL2GSSetDisplayPhotoRequest struct {
	Displayphoto uint32 `protobuf:"varint,1,opt,name=displayphoto" json:"displayphoto,omitempty"`
}

func (m *MsgCL2GSSetDisplayPhotoRequest) Reset()                    { *m = MsgCL2GSSetDisplayPhotoRequest{} }
func (m *MsgCL2GSSetDisplayPhotoRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSSetDisplayPhotoRequest) ProtoMessage()               {}
func (*MsgCL2GSSetDisplayPhotoRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *MsgCL2GSSetDisplayPhotoRequest) GetDisplayphoto() uint32 {
	if m != nil {
		return m.Displayphoto
	}
	return 0
}

// 设置头像响应
type MsgGS2CLSetDisplayPhotoReply struct {
	Head      string `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLSetDisplayPhotoReply) Reset()                    { *m = MsgGS2CLSetDisplayPhotoReply{} }
func (m *MsgGS2CLSetDisplayPhotoReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLSetDisplayPhotoReply) ProtoMessage()               {}
func (*MsgGS2CLSetDisplayPhotoReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *MsgGS2CLSetDisplayPhotoReply) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *MsgGS2CLSetDisplayPhotoReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 设置头像框请求
type MsgCL2GSSetDisplayPhotoFrameRequest struct {
	DisplayPhotoFrame uint32 `protobuf:"varint,1,opt,name=display_photo_frame,json=displayPhotoFrame" json:"display_photo_frame,omitempty"`
}

func (m *MsgCL2GSSetDisplayPhotoFrameRequest) Reset()         { *m = MsgCL2GSSetDisplayPhotoFrameRequest{} }
func (m *MsgCL2GSSetDisplayPhotoFrameRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSSetDisplayPhotoFrameRequest) ProtoMessage()    {}
func (*MsgCL2GSSetDisplayPhotoFrameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{15}
}

func (m *MsgCL2GSSetDisplayPhotoFrameRequest) GetDisplayPhotoFrame() uint32 {
	if m != nil {
		return m.DisplayPhotoFrame
	}
	return 0
}

// 设置头像框响应
type MsgGS2CLSetDisplayPhotoFrameReply struct {
	Head      string `protobuf:"bytes,1,opt,name=head" json:"head,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLSetDisplayPhotoFrameReply) Reset()         { *m = MsgGS2CLSetDisplayPhotoFrameReply{} }
func (m *MsgGS2CLSetDisplayPhotoFrameReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLSetDisplayPhotoFrameReply) ProtoMessage()    {}
func (*MsgGS2CLSetDisplayPhotoFrameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{16}
}

func (m *MsgGS2CLSetDisplayPhotoFrameReply) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *MsgGS2CLSetDisplayPhotoFrameReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 击杀详情请求
type MsgCL2GSKillRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgCL2GSKillRequest) Reset()                    { *m = MsgCL2GSKillRequest{} }
func (m *MsgCL2GSKillRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSKillRequest) ProtoMessage()               {}
func (*MsgCL2GSKillRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *MsgCL2GSKillRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 击杀详情响应
type MsgGS2CLKillReply struct {
	KillArmyCount *KillArmyCountInfo `protobuf:"bytes,1,opt,name=kill_army_count,json=killArmyCount" json:"kill_army_count,omitempty"`
	PlayerId      uint64             `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ErrorCode     int32              `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLKillReply) Reset()                    { *m = MsgGS2CLKillReply{} }
func (m *MsgGS2CLKillReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLKillReply) ProtoMessage()               {}
func (*MsgGS2CLKillReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *MsgGS2CLKillReply) GetKillArmyCount() *KillArmyCountInfo {
	if m != nil {
		return m.KillArmyCount
	}
	return nil
}

func (m *MsgGS2CLKillReply) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2CLKillReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 查看其他玩家领主信息
type MsgCL2GSQueryPlayerLordInfoRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgCL2GSQueryPlayerLordInfoRequest) Reset()         { *m = MsgCL2GSQueryPlayerLordInfoRequest{} }
func (m *MsgCL2GSQueryPlayerLordInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSQueryPlayerLordInfoRequest) ProtoMessage()    {}
func (*MsgCL2GSQueryPlayerLordInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{19}
}

func (m *MsgCL2GSQueryPlayerLordInfoRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type MsgGS2CLQueryPlayerLordInfoReply struct {
	Info      *PlayerLordInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	ErrorCode int32           `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLQueryPlayerLordInfoReply) Reset()         { *m = MsgGS2CLQueryPlayerLordInfoReply{} }
func (m *MsgGS2CLQueryPlayerLordInfoReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLQueryPlayerLordInfoReply) ProtoMessage()    {}
func (*MsgGS2CLQueryPlayerLordInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{20}
}

func (m *MsgGS2CLQueryPlayerLordInfoReply) GetInfo() *PlayerLordInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MsgGS2CLQueryPlayerLordInfoReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 战斗统计请求
type MsgCL2GSBattleStatisticsRequest struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgCL2GSBattleStatisticsRequest) Reset()         { *m = MsgCL2GSBattleStatisticsRequest{} }
func (m *MsgCL2GSBattleStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSBattleStatisticsRequest) ProtoMessage()    {}
func (*MsgCL2GSBattleStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{21}
}

func (m *MsgCL2GSBattleStatisticsRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type MsgGS2CLBattleStatisticsReply struct {
	BattleStatistics *BattleStatistics `protobuf:"bytes,1,opt,name=battle_statistics,json=battleStatistics" json:"battle_statistics,omitempty"`
	PlayerId         uint64            `protobuf:"varint,2,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ErrorCode        int32             `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLBattleStatisticsReply) Reset()                    { *m = MsgGS2CLBattleStatisticsReply{} }
func (m *MsgGS2CLBattleStatisticsReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLBattleStatisticsReply) ProtoMessage()               {}
func (*MsgGS2CLBattleStatisticsReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{22} }

func (m *MsgGS2CLBattleStatisticsReply) GetBattleStatistics() *BattleStatistics {
	if m != nil {
		return m.BattleStatistics
	}
	return nil
}

func (m *MsgGS2CLBattleStatisticsReply) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2CLBattleStatisticsReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 新增头像框通知
type MsgGS2CLDisplayPhotoFrameNotice struct {
	DisplayPhotoFrame uint32 `protobuf:"varint,1,opt,name=display_photo_frame,json=displayPhotoFrame" json:"display_photo_frame,omitempty"`
}

func (m *MsgGS2CLDisplayPhotoFrameNotice) Reset()         { *m = MsgGS2CLDisplayPhotoFrameNotice{} }
func (m *MsgGS2CLDisplayPhotoFrameNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLDisplayPhotoFrameNotice) ProtoMessage()    {}
func (*MsgGS2CLDisplayPhotoFrameNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{23}
}

func (m *MsgGS2CLDisplayPhotoFrameNotice) GetDisplayPhotoFrame() uint32 {
	if m != nil {
		return m.DisplayPhotoFrame
	}
	return 0
}

// 新增头像通知
type MsgGS2CLDisplayPhotoNotice struct {
	Displayphoto uint32 `protobuf:"varint,1,opt,name=displayphoto" json:"displayphoto,omitempty"`
}

func (m *MsgGS2CLDisplayPhotoNotice) Reset()                    { *m = MsgGS2CLDisplayPhotoNotice{} }
func (m *MsgGS2CLDisplayPhotoNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLDisplayPhotoNotice) ProtoMessage()               {}
func (*MsgGS2CLDisplayPhotoNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{24} }

func (m *MsgGS2CLDisplayPhotoNotice) GetDisplayphoto() uint32 {
	if m != nil {
		return m.Displayphoto
	}
	return 0
}

// Emoney兑换资源
type MsgCL2GSGemToResource struct {
	Resources []*MsgCL2GSGemToResource_BuyResource `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *MsgCL2GSGemToResource) Reset()                    { *m = MsgCL2GSGemToResource{} }
func (m *MsgCL2GSGemToResource) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSGemToResource) ProtoMessage()               {}
func (*MsgCL2GSGemToResource) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{25} }

func (m *MsgCL2GSGemToResource) GetResources() []*MsgCL2GSGemToResource_BuyResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

// 购买资源信息
type MsgCL2GSGemToResource_BuyResource struct {
	Type CurrencyType `protobuf:"varint,1,opt,name=type,enum=protomsg.CurrencyType" json:"type,omitempty"`
	Num  uint64       `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
}

func (m *MsgCL2GSGemToResource_BuyResource) Reset()         { *m = MsgCL2GSGemToResource_BuyResource{} }
func (m *MsgCL2GSGemToResource_BuyResource) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSGemToResource_BuyResource) ProtoMessage()    {}
func (*MsgCL2GSGemToResource_BuyResource) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{25, 0}
}

func (m *MsgCL2GSGemToResource_BuyResource) GetType() CurrencyType {
	if m != nil {
		return m.Type
	}
	return CurrencyType_kCurrencyTypeNone
}

func (m *MsgCL2GSGemToResource_BuyResource) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

// 服务器兑换资源回应
type MsgGS2CLGemToResourceReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLGemToResourceReply) Reset()                    { *m = MsgGS2CLGemToResourceReply{} }
func (m *MsgGS2CLGemToResourceReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLGemToResourceReply) ProtoMessage()               {}
func (*MsgGS2CLGemToResourceReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{26} }

func (m *MsgGS2CLGemToResourceReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 更改阵营
type MsgCL2GSChangeCampRequest struct {
	CampId uint32 `protobuf:"varint,1,opt,name=camp_id,json=campId" json:"camp_id,omitempty"`
}

func (m *MsgCL2GSChangeCampRequest) Reset()                    { *m = MsgCL2GSChangeCampRequest{} }
func (m *MsgCL2GSChangeCampRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSChangeCampRequest) ProtoMessage()               {}
func (*MsgCL2GSChangeCampRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{27} }

func (m *MsgCL2GSChangeCampRequest) GetCampId() uint32 {
	if m != nil {
		return m.CampId
	}
	return 0
}

type MsgGS2CLChangeCampReply struct {
	CampId    uint32 `protobuf:"varint,1,opt,name=camp_id,json=campId" json:"camp_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLChangeCampReply) Reset()                    { *m = MsgGS2CLChangeCampReply{} }
func (m *MsgGS2CLChangeCampReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLChangeCampReply) ProtoMessage()               {}
func (*MsgGS2CLChangeCampReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{28} }

func (m *MsgGS2CLChangeCampReply) GetCampId() uint32 {
	if m != nil {
		return m.CampId
	}
	return 0
}

func (m *MsgGS2CLChangeCampReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type PlayerPropertyInfo struct {
	Type    PlayerPropertyNoticeType `protobuf:"varint,1,opt,name=type,enum=protomsg.PlayerPropertyNoticeType" json:"type,omitempty"`
	SubType uint32                   `protobuf:"varint,2,opt,name=sub_type,json=subType" json:"sub_type,omitempty"`
	Value   int64                    `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *PlayerPropertyInfo) Reset()                    { *m = PlayerPropertyInfo{} }
func (m *PlayerPropertyInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerPropertyInfo) ProtoMessage()               {}
func (*PlayerPropertyInfo) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{29} }

func (m *PlayerPropertyInfo) GetType() PlayerPropertyNoticeType {
	if m != nil {
		return m.Type
	}
	return PlayerPropertyNoticeType_kPlayerPropertyNone
}

func (m *PlayerPropertyInfo) GetSubType() uint32 {
	if m != nil {
		return m.SubType
	}
	return 0
}

func (m *PlayerPropertyInfo) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

// 玩家信息通知
type MsgGS2CLPlayerPropertyNotice struct {
	Info *PlayerPropertyInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGS2CLPlayerPropertyNotice) Reset()                    { *m = MsgGS2CLPlayerPropertyNotice{} }
func (m *MsgGS2CLPlayerPropertyNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPlayerPropertyNotice) ProtoMessage()               {}
func (*MsgGS2CLPlayerPropertyNotice) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{30} }

func (m *MsgGS2CLPlayerPropertyNotice) GetInfo() *PlayerPropertyInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 游戏评级请求
type MsgCL2GSGameEvaluationRequest struct {
	Evaluation bool `protobuf:"varint,1,opt,name=evaluation" json:"evaluation,omitempty"`
}

func (m *MsgCL2GSGameEvaluationRequest) Reset()                    { *m = MsgCL2GSGameEvaluationRequest{} }
func (m *MsgCL2GSGameEvaluationRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSGameEvaluationRequest) ProtoMessage()               {}
func (*MsgCL2GSGameEvaluationRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{31} }

func (m *MsgCL2GSGameEvaluationRequest) GetEvaluation() bool {
	if m != nil {
		return m.Evaluation
	}
	return false
}

// 游戏评级回复
type MsgGS2CLGameEvaluationReply struct {
	Awards     []*Resource `protobuf:"bytes,1,rep,name=awards" json:"awards,omitempty"`
	Evaluation bool        `protobuf:"varint,2,opt,name=evaluation" json:"evaluation,omitempty"`
	ErrorCode  int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLGameEvaluationReply) Reset()                    { *m = MsgGS2CLGameEvaluationReply{} }
func (m *MsgGS2CLGameEvaluationReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLGameEvaluationReply) ProtoMessage()               {}
func (*MsgGS2CLGameEvaluationReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{32} }

func (m *MsgGS2CLGameEvaluationReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgGS2CLGameEvaluationReply) GetEvaluation() bool {
	if m != nil {
		return m.Evaluation
	}
	return false
}

func (m *MsgGS2CLGameEvaluationReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgGS2CLPlayerBaseNotice)(nil), "protomsg.MsgGS2CLPlayerBaseNotice")
	proto.RegisterType((*MsgCL2GSRenameRequest)(nil), "protomsg.MsgCL2GSRenameRequest")
	proto.RegisterType((*MsgGS2CLRenameReply)(nil), "protomsg.MsgGS2CLRenameReply")
	proto.RegisterType((*MsgCL2GSKeepLiveRequest)(nil), "protomsg.MsgCL2GSKeepLiveRequest")
	proto.RegisterType((*MsgGS2CLKeepLiveReply)(nil), "protomsg.MsgGS2CLKeepLiveReply")
	proto.RegisterType((*MsgGS2CLServerTimeNotice)(nil), "protomsg.MsgGS2CLServerTimeNotice")
	proto.RegisterType((*MsgGS2CLDayResetNotice)(nil), "protomsg.MsgGS2CLDayResetNotice")
	proto.RegisterType((*PlayerAttribute)(nil), "protomsg.PlayerAttribute")
	proto.RegisterType((*MsgGS2CLPlayerAttribute)(nil), "protomsg.MsgGS2CLPlayerAttribute")
	proto.RegisterType((*MsgGS2CLPlayerAPData)(nil), "protomsg.MsgGS2CLPlayerAPData")
	proto.RegisterType((*MsgCL2GSSetLanguageTypeRequest)(nil), "protomsg.MsgCL2GSSetLanguageTypeRequest")
	proto.RegisterType((*MsgGS2CLSetLanguageTypeReply)(nil), "protomsg.MsgGS2CLSetLanguageTypeReply")
	proto.RegisterType((*MsgCL2GSUpdateClientLocalDataRequest)(nil), "protomsg.MsgCL2GSUpdateClientLocalDataRequest")
	proto.RegisterType((*MsgCL2GSSetDisplayPhotoRequest)(nil), "protomsg.MsgCL2GSSetDisplayPhotoRequest")
	proto.RegisterType((*MsgGS2CLSetDisplayPhotoReply)(nil), "protomsg.MsgGS2CLSetDisplayPhotoReply")
	proto.RegisterType((*MsgCL2GSSetDisplayPhotoFrameRequest)(nil), "protomsg.MsgCL2GSSetDisplayPhotoFrameRequest")
	proto.RegisterType((*MsgGS2CLSetDisplayPhotoFrameReply)(nil), "protomsg.MsgGS2CLSetDisplayPhotoFrameReply")
	proto.RegisterType((*MsgCL2GSKillRequest)(nil), "protomsg.MsgCL2GSKillRequest")
	proto.RegisterType((*MsgGS2CLKillReply)(nil), "protomsg.MsgGS2CLKillReply")
	proto.RegisterType((*MsgCL2GSQueryPlayerLordInfoRequest)(nil), "protomsg.MsgCL2GSQueryPlayerLordInfoRequest")
	proto.RegisterType((*MsgGS2CLQueryPlayerLordInfoReply)(nil), "protomsg.MsgGS2CLQueryPlayerLordInfoReply")
	proto.RegisterType((*MsgCL2GSBattleStatisticsRequest)(nil), "protomsg.MsgCL2GSBattleStatisticsRequest")
	proto.RegisterType((*MsgGS2CLBattleStatisticsReply)(nil), "protomsg.MsgGS2CLBattleStatisticsReply")
	proto.RegisterType((*MsgGS2CLDisplayPhotoFrameNotice)(nil), "protomsg.MsgGS2CLDisplayPhotoFrameNotice")
	proto.RegisterType((*MsgGS2CLDisplayPhotoNotice)(nil), "protomsg.MsgGS2CLDisplayPhotoNotice")
	proto.RegisterType((*MsgCL2GSGemToResource)(nil), "protomsg.MsgCL2GSGemToResource")
	proto.RegisterType((*MsgCL2GSGemToResource_BuyResource)(nil), "protomsg.MsgCL2GSGemToResource.BuyResource")
	proto.RegisterType((*MsgGS2CLGemToResourceReply)(nil), "protomsg.MsgGS2CLGemToResourceReply")
	proto.RegisterType((*MsgCL2GSChangeCampRequest)(nil), "protomsg.MsgCL2GSChangeCampRequest")
	proto.RegisterType((*MsgGS2CLChangeCampReply)(nil), "protomsg.MsgGS2CLChangeCampReply")
	proto.RegisterType((*PlayerPropertyInfo)(nil), "protomsg.PlayerPropertyInfo")
	proto.RegisterType((*MsgGS2CLPlayerPropertyNotice)(nil), "protomsg.MsgGS2CLPlayerPropertyNotice")
	proto.RegisterType((*MsgCL2GSGameEvaluationRequest)(nil), "protomsg.MsgCL2GSGameEvaluationRequest")
	proto.RegisterType((*MsgGS2CLGameEvaluationReply)(nil), "protomsg.MsgGS2CLGameEvaluationReply")
	proto.RegisterEnum("protomsg.ClientLocalDataType", ClientLocalDataType_name, ClientLocalDataType_value)
}

func init() { proto.RegisterFile("base.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 1522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x5f, 0x53, 0xe3, 0xc8,
	0x11, 0x8f, 0x6c, 0x96, 0xb5, 0x1b, 0x0c, 0x66, 0xd8, 0x05, 0xf1, 0x6f, 0xd7, 0x27, 0xb6, 0x52,
	0x0e, 0xd9, 0xa2, 0xb2, 0x24, 0x95, 0x54, 0xea, 0x2a, 0x7f, 0x58, 0x73, 0xc7, 0x71, 0x0b, 0x17,
	0x90, 0xb9, 0xcb, 0xa3, 0x6a, 0x90, 0x1a, 0xa3, 0xac, 0xa4, 0x71, 0xa4, 0x11, 0xac, 0xab, 0x92,
	0xf7, 0x7c, 0x80, 0x7c, 0x84, 0xbc, 0xe7, 0x31, 0x5f, 0x2f, 0xd5, 0x33, 0x1a, 0x4b, 0x36, 0x66,
	0x21, 0xb9, 0x27, 0xcd, 0xfc, 0xba, 0xa7, 0xa7, 0xff, 0xf7, 0x08, 0xe0, 0x8a, 0x67, 0xb8, 0x3f,
	0x4c, 0x85, 0x14, 0xac, 0xa1, 0x3e, 0x71, 0x36, 0xd8, 0x6c, 0xc7, 0xd9, 0xc0, 0xf3, 0x45, 0x1c,
	0x8b, 0x44, 0xd3, 0x9c, 0xff, 0x34, 0xc0, 0x3e, 0xcb, 0x06, 0xc7, 0xfd, 0x83, 0xde, 0xe9, 0x79,
	0xc4, 0x47, 0x98, 0xbe, 0xe7, 0x19, 0x7e, 0x27, 0x64, 0xe8, 0x23, 0xdb, 0x82, 0xe6, 0x50, 0x61,
	0x5e, 0x18, 0xd8, 0x56, 0xc7, 0xea, 0xce, 0xb9, 0x0d, 0x0d, 0x9c, 0x04, 0x8c, 0xc1, 0x5c, 0xc2,
	0x63, 0xb4, 0x6b, 0x1d, 0xab, 0xdb, 0x74, 0xd5, 0x9a, 0xbd, 0x80, 0x67, 0x11, 0xde, 0x62, 0x64,
	0xd7, 0x3b, 0x56, 0xb7, 0xe5, 0xea, 0x0d, 0x6b, 0x43, 0x1d, 0x3f, 0x0d, 0xed, 0x39, 0x85, 0xd1,
	0x92, 0x10, 0x11, 0x46, 0x76, 0x43, 0x89, 0xa4, 0x25, 0x5b, 0x83, 0x79, 0x8c, 0x45, 0x82, 0x23,
	0xbb, 0xa9, 0xc0, 0x62, 0xc7, 0x36, 0xa1, 0x11, 0xf1, 0x64, 0x90, 0xf3, 0x01, 0xda, 0xa0, 0x04,
	0x8c, 0xf7, 0xec, 0x2d, 0x30, 0x3f, 0x0a, 0x31, 0x91, 0x5e, 0x24, 0x7c, 0x1e, 0x79, 0x01, 0x97,
	0x3c, 0xb3, 0x17, 0x3a, 0xf5, 0x6e, 0xd3, 0x6d, 0x6b, 0xca, 0x29, 0x11, 0x8e, 0x08, 0x67, 0xeb,
	0xf0, 0x9c, 0xa7, 0xc8, 0xc9, 0x94, 0x45, 0x25, 0x68, 0x9e, 0xb6, 0x27, 0x01, 0x7b, 0x05, 0xe0,
	0xe7, 0x69, 0x8a, 0x89, 0x1f, 0x62, 0x66, 0xb7, 0x3a, 0xf5, 0xee, 0x9c, 0x5b, 0x41, 0xc8, 0xd0,
	0x6b, 0x21, 0x02, 0x7b, 0x49, 0x29, 0xa6, 0xd6, 0x84, 0xdd, 0x11, 0xb6, 0xac, 0x31, 0x5a, 0x93,
	0xf1, 0x99, 0x44, 0x8c, 0xec, 0xb6, 0x02, 0xf5, 0x86, 0xbd, 0x81, 0x56, 0x10, 0x66, 0xe4, 0xb5,
	0xe1, 0x8d, 0x90, 0x22, 0xb3, 0xf3, 0x4e, 0xbd, 0xdb, 0x72, 0x27, 0x41, 0x92, 0x77, 0x83, 0x3c,
	0xb0, 0x99, 0x76, 0x26, 0xad, 0x49, 0xde, 0x50, 0xdc, 0x61, 0x6a, 0xaf, 0x6a, 0x79, 0x6a, 0xc3,
	0xf6, 0x61, 0xb5, 0x38, 0xea, 0xa9, 0xb3, 0xde, 0x75, 0x4a, 0x51, 0xf8, 0xa4, 0xa4, 0xae, 0x14,
	0xa4, 0x73, 0xa2, 0x7c, 0x4d, 0x04, 0xf6, 0x33, 0x68, 0xfb, 0x22, 0x8a, 0xd0, 0x97, 0xa1, 0x48,
	0x3c, 0x5f, 0xe4, 0x89, 0xb4, 0x5f, 0x2a, 0x81, 0xcb, 0x25, 0xde, 0x23, 0x98, 0xed, 0x00, 0x7c,
	0x0c, 0xa3, 0xa8, 0x60, 0x5a, 0x53, 0x4c, 0x4d, 0x42, 0x34, 0xf9, 0x1d, 0x80, 0xcf, 0x33, 0x19,
	0xa1, 0x37, 0x14, 0x99, 0xbd, 0xde, 0xb1, 0xba, 0x0b, 0x07, 0x6c, 0xdf, 0xe4, 0xd6, 0xfe, 0x2d,
	0xfa, 0x52, 0xa4, 0x07, 0x81, 0xdb, 0xd4, 0x5c, 0xe7, 0x22, 0x63, 0x7b, 0xb0, 0x92, 0x61, 0x7a,
	0x8b, 0xa9, 0x97, 0x49, 0x9e, 0x4a, 0x4f, 0x86, 0x31, 0xda, 0xb6, 0xbe, 0x5d, 0x13, 0xfa, 0x84,
	0x5f, 0x86, 0x31, 0x52, 0x7c, 0x7c, 0x1e, 0x0f, 0x29, 0x3e, 0x1b, 0x3a, 0x3e, 0xb4, 0x3d, 0x09,
	0x58, 0x17, 0xda, 0x22, 0x0d, 0x07, 0x61, 0xc2, 0x23, 0xcf, 0x70, 0x6c, 0x2a, 0x8e, 0x25, 0x83,
	0xf7, 0x34, 0xe7, 0x2e, 0xb4, 0x3e, 0x86, 0xc9, 0x20, 0x10, 0xb1, 0x27, 0x43, 0x19, 0xa1, 0xbd,
	0xa5, 0xd8, 0x16, 0x0b, 0xf0, 0x92, 0x30, 0x62, 0x4a, 0x71, 0x10, 0x66, 0x12, 0x53, 0xad, 0xcf,
	0x76, 0xc7, 0xea, 0xd6, 0xdd, 0x45, 0x03, 0x2a, 0x65, 0xde, 0x02, 0xc3, 0x84, 0x38, 0x4a, 0x79,
	0x31, 0xda, 0x3b, 0x8a, 0xb3, 0xad, 0x28, 0x1f, 0x8c, 0xcc, 0x18, 0x29, 0x83, 0xf0, 0x96, 0x47,
	0x39, 0x27, 0x5f, 0xda, 0xaf, 0x3a, 0x56, 0xb7, 0xe1, 0x56, 0x10, 0xf6, 0x0e, 0x5e, 0x5e, 0x87,
	0x69, 0x26, 0xbd, 0xbf, 0x88, 0x30, 0xf1, 0x06, 0x79, 0x18, 0x05, 0x5a, 0xe0, 0x6b, 0x25, 0x90,
	0x29, 0xe2, 0xb7, 0x22, 0x4c, 0x8e, 0x89, 0x64, 0x14, 0xf0, 0x53, 0xe4, 0x12, 0x3d, 0xee, 0xab,
	0x78, 0x78, 0x01, 0x1f, 0xd9, 0x1d, 0x65, 0x4f, 0x5b, 0x53, 0x0e, 0x35, 0xe1, 0x88, 0x8f, 0xd8,
	0x06, 0x34, 0x32, 0x7e, 0x8d, 0x1e, 0x15, 0xd5, 0x17, 0xca, 0xbd, 0xcf, 0x69, 0xff, 0xa7, 0x30,
	0xa2, 0x1a, 0x56, 0x24, 0x95, 0xc2, 0x8e, 0xae, 0x61, 0x02, 0xbe, 0xa6, 0x94, 0x35, 0x44, 0x95,
	0xcb, 0xbb, 0x25, 0xf1, 0xcf, 0x44, 0xdc, 0x01, 0x50, 0x44, 0x9d, 0xd4, 0x6f, 0x74, 0x3a, 0x10,
	0xd2, 0x27, 0xc0, 0xf9, 0x06, 0x5e, 0x9e, 0x65, 0x83, 0xde, 0xe9, 0xc1, 0x71, 0xdf, 0x45, 0xaa,
	0x7e, 0x17, 0xff, 0x9a, 0x63, 0x26, 0xc7, 0x8d, 0xc1, 0xaa, 0x34, 0x86, 0x2d, 0x68, 0xe6, 0x19,
	0x7a, 0xba, 0xc2, 0x6b, 0xca, 0x41, 0x8d, 0x3c, 0xc3, 0x33, 0xda, 0x3b, 0xdf, 0xc0, 0xaa, 0x69,
	0x41, 0x46, 0xd2, 0x30, 0x1a, 0xcd, 0x94, 0xb3, 0x03, 0x80, 0x69, 0x2a, 0x52, 0xcf, 0x17, 0x01,
	0xda, 0x7e, 0xc7, 0xea, 0x3e, 0x73, 0x9b, 0x0a, 0xe9, 0x89, 0x00, 0x9d, 0x0d, 0x58, 0x37, 0x3a,
	0x7d, 0x40, 0x1c, 0x9e, 0x86, 0xb7, 0x46, 0x2b, 0x67, 0x5d, 0xa9, 0xab, 0x2e, 0x29, 0x49, 0xc3,
	0x68, 0xe4, 0x7c, 0x59, 0x36, 0xc0, 0xbe, 0x4a, 0x49, 0xf2, 0x7f, 0xd1, 0x00, 0x5f, 0xc3, 0x42,
	0x91, 0xbf, 0x2a, 0x5c, 0x96, 0x0a, 0x17, 0x64, 0x63, 0x36, 0xe7, 0x37, 0xb0, 0x66, 0x0e, 0x1f,
	0xf1, 0x91, 0x8b, 0x19, 0xca, 0xe2, 0xe8, 0x0e, 0x40, 0x24, 0x06, 0x61, 0x42, 0x71, 0xcb, 0xd4,
	0xc9, 0x96, 0xdb, 0x54, 0xc8, 0x11, 0x1f, 0x65, 0xce, 0x0f, 0xb0, 0xac, 0xdb, 0xed, 0xa1, 0x94,
	0x69, 0x78, 0x95, 0x4b, 0x24, 0x7b, 0xe5, 0x68, 0x88, 0x05, 0xaf, 0x5a, 0xab, 0xc0, 0xe6, 0x57,
	0x9e, 0xc2, 0x6b, 0x0a, 0x7f, 0x9e, 0xe5, 0x57, 0x97, 0x44, 0x7a, 0x01, 0xcf, 0x28, 0xc3, 0x50,
	0xf5, 0xda, 0x39, 0x57, 0x6f, 0x9c, 0x4b, 0xe5, 0x81, 0x4a, 0x3b, 0x2f, 0xe5, 0xff, 0x16, 0x80,
	0x9b, 0x0d, 0x69, 0x54, 0xef, 0x2e, 0x1c, 0x6c, 0x94, 0xf5, 0x3b, 0xc5, 0xee, 0x56, 0x98, 0x9d,
	0x6f, 0xe1, 0xc5, 0x94, 0xd4, 0x73, 0x6a, 0xaa, 0x6c, 0x09, 0x6a, 0x7c, 0x58, 0x28, 0x5c, 0xe3,
	0x43, 0xe6, 0x40, 0x2b, 0xe2, 0x99, 0xf4, 0x78, 0x50, 0x24, 0x78, 0x4d, 0x79, 0x6c, 0x81, 0xc0,
	0xc3, 0x40, 0x65, 0xb6, 0xf3, 0x15, 0xbc, 0x32, 0x31, 0xea, 0xa3, 0x3c, 0x2d, 0x9a, 0x39, 0x99,
	0x64, 0x12, 0x68, 0x97, 0xa4, 0x68, 0xd8, 0xab, 0x78, 0x64, 0x31, 0xaa, 0xf0, 0x3a, 0xbf, 0x83,
	0xed, 0x32, 0x6c, 0x53, 0x62, 0x28, 0x7b, 0x1e, 0xc9, 0x94, 0x18, 0xde, 0x18, 0x2d, 0xbe, 0x1f,
	0x06, 0x5c, 0x62, 0x6f, 0x72, 0x5e, 0x18, 0x5d, 0xde, 0x55, 0x82, 0xb2, 0x74, 0xb0, 0x53, 0xba,
	0x6b, 0x8a, 0x5f, 0x5d, 0xac, 0x63, 0xc6, 0x60, 0x8e, 0x26, 0x91, 0x19, 0x8c, 0xb4, 0x76, 0x8e,
	0x26, 0x8c, 0x3e, 0xaa, 0x74, 0x69, 0x73, 0x91, 0x03, 0x8b, 0xd5, 0x91, 0x60, 0x6c, 0xae, 0x62,
	0xce, 0xc5, 0x84, 0xcd, 0x93, 0x52, 0x8a, 0x8a, 0x51, 0x53, 0xc4, 0xaa, 0x4c, 0x91, 0x47, 0xfc,
	0xf0, 0x3d, 0xec, 0x3e, 0xa0, 0x98, 0x1a, 0x1f, 0x46, 0xbb, 0x07, 0xa6, 0x8e, 0x56, 0xf2, 0xfe,
	0xd4, 0x71, 0x7e, 0x80, 0x2f, 0x1e, 0xd0, 0xb4, 0x10, 0xfb, 0x7f, 0xaa, 0x7b, 0xa0, 0x5a, 0x85,
	0x2e, 0xf0, 0x30, 0x8a, 0x8c, 0x7a, 0x9f, 0x7b, 0xa8, 0x38, 0xff, 0xb4, 0x60, 0x65, 0x5c, 0xfa,
	0xea, 0x10, 0x5d, 0xde, 0x83, 0x65, 0x35, 0xec, 0x78, 0x1a, 0x8f, 0x8a, 0x89, 0x67, 0xa9, 0x91,
	0xb6, 0x55, 0xc6, 0x98, 0xb8, 0x0f, 0xd3, 0x78, 0xa4, 0xe6, 0xdf, 0x49, 0x72, 0x2d, 0xdc, 0xd6,
	0xc7, 0x2a, 0x34, 0x79, 0x6f, 0x6d, 0xea, 0x81, 0xf4, 0x88, 0x29, 0x87, 0xe0, 0x18, 0x53, 0x2e,
	0x72, 0x4c, 0x47, 0xba, 0xb0, 0x4e, 0x45, 0x1a, 0xa8, 0x9b, 0x9e, 0x62, 0x99, 0x80, 0x8e, 0x31,
	0x6c, 0xa6, 0x08, 0xb2, 0xf3, 0x2d, 0xcc, 0x85, 0xc9, 0xb5, 0x28, 0x8c, 0xb3, 0xa7, 0xeb, 0x7d,
	0xcc, 0xac, 0xb8, 0x1e, 0xd3, 0xf9, 0xf7, 0xf0, 0xda, 0xe8, 0xfc, 0x9e, 0x4b, 0x19, 0x61, 0x5f,
	0x72, 0x19, 0x66, 0x32, 0xf4, 0xb3, 0x27, 0x29, 0xfc, 0x2f, 0x0b, 0x76, 0x8c, 0xc6, 0xf7, 0x05,
	0x90, 0xba, 0xc7, 0xb0, 0x72, 0xa5, 0x08, 0xf4, 0x62, 0x28, 0x28, 0x85, 0xee, 0x9b, 0xa5, 0xee,
	0xf7, 0xce, 0xb6, 0xaf, 0xa6, 0x90, 0x1f, 0x15, 0x9a, 0x0b, 0x65, 0xa6, 0xee, 0xea, 0xd3, 0xa9,
	0x5b, 0xb4, 0xf7, 0xff, 0xb5, 0x20, 0xfe, 0x08, 0x9b, 0xb3, 0x44, 0x16, 0xd2, 0x9e, 0x52, 0xfc,
	0xff, 0xb6, 0xca, 0x81, 0x7b, 0x8c, 0xf1, 0xa5, 0x70, 0x31, 0x13, 0x79, 0xea, 0x23, 0x3b, 0x81,
	0x66, 0x5a, 0xac, 0x4d, 0x5f, 0xff, 0x79, 0xe9, 0xab, 0x99, 0x67, 0xf6, 0xdf, 0xe7, 0x23, 0xb3,
	0x76, 0xcb, 0xd3, 0x9b, 0x1f, 0x60, 0xa1, 0x42, 0x61, 0x7b, 0x13, 0xdd, 0x6f, 0xad, 0xd2, 0xfd,
	0xf4, 0xf3, 0x78, 0x54, 0x69, 0x7b, 0x6d, 0xa8, 0x27, 0x79, 0x5c, 0xb8, 0x9a, 0x96, 0xce, 0x97,
	0xa5, 0xcd, 0x13, 0x97, 0x3f, 0xa9, 0x41, 0xff, 0x0a, 0x36, 0x8c, 0xe6, 0xbd, 0x1b, 0x9e, 0x0c,
	0x90, 0xde, 0x78, 0x26, 0xc9, 0x2a, 0x6f, 0x45, 0xab, 0xfa, 0x56, 0x74, 0x2e, 0xca, 0xf1, 0x57,
	0x3d, 0x45, 0xf7, 0x3d, 0x74, 0xe6, 0x31, 0x45, 0xfe, 0x0e, 0x4c, 0x97, 0xca, 0x79, 0x2a, 0x86,
	0x98, 0xca, 0x11, 0x95, 0x0b, 0xfb, 0xf5, 0x84, 0x67, 0x9c, 0xe9, 0xb2, 0x32, 0xbc, 0x3a, 0xbe,
	0x15, 0x2f, 0x3d, 0x75, 0xa0, 0xd7, 0xcd, 0x40, 0x3f, 0x2f, 0x7b, 0xfe, 0x2c, 0xd1, 0xec, 0x17,
	0x13, 0xf5, 0xbd, 0xfd, 0x90, 0x22, 0x65, 0x8d, 0x3b, 0x7f, 0x50, 0x35, 0xa8, 0x73, 0x82, 0xc7,
	0xf8, 0xd5, 0xf8, 0x9d, 0x6a, 0xbc, 0x3b, 0xf9, 0x9c, 0xb5, 0xa6, 0x9f, 0xb3, 0xce, 0x3f, 0x2c,
	0xd8, 0x1a, 0x07, 0x76, 0x4a, 0x02, 0x79, 0x7a, 0x0f, 0xe6, 0xf9, 0x1d, 0x4f, 0x03, 0x93, 0x8c,
	0x95, 0x9f, 0x84, 0x71, 0x0a, 0x14, 0x1c, 0x53, 0x77, 0xd5, 0xee, 0x3d, 0x9d, 0x3f, 0x1f, 0x9c,
	0xbd, 0xbf, 0xc1, 0xea, 0x8c, 0x41, 0xcc, 0xb6, 0xc1, 0x9e, 0x01, 0x7b, 0xdf, 0x89, 0x04, 0xdb,
	0x3f, 0x61, 0x7b, 0xf0, 0xd3, 0x59, 0xd4, 0x9e, 0xfa, 0x6d, 0xe9, 0xdf, 0x88, 0x3b, 0x17, 0x7d,
	0x91, 0x06, 0x98, 0xb6, 0x2d, 0xb6, 0x05, 0xeb, 0xb3, 0x78, 0xcf, 0xf8, 0xa7, 0x76, 0xed, 0x6a,
	0x5e, 0xd9, 0xf5, 0xcb, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x67, 0x17, 0x25, 0x6d, 0x0f,
	0x00, 0x00,
}
