// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mall.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 商品数据
type MallGoodsInfo struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	EndTime int64  `protobuf:"varint,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (m *MallGoodsInfo) Reset()                    { *m = MallGoodsInfo{} }
func (m *MallGoodsInfo) String() string            { return proto.CompactTextString(m) }
func (*MallGoodsInfo) ProtoMessage()               {}
func (*MallGoodsInfo) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{0} }

func (m *MallGoodsInfo) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MallGoodsInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

// 商城全部可用goods_id通知
type MsgGS2CLAllMallNotice struct {
	Goods []*MallGoodsInfo `protobuf:"bytes,1,rep,name=goods" json:"goods,omitempty"`
}

func (m *MsgGS2CLAllMallNotice) Reset()                    { *m = MsgGS2CLAllMallNotice{} }
func (m *MsgGS2CLAllMallNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLAllMallNotice) ProtoMessage()               {}
func (*MsgGS2CLAllMallNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{1} }

func (m *MsgGS2CLAllMallNotice) GetGoods() []*MallGoodsInfo {
	if m != nil {
		return m.Goods
	}
	return nil
}

// 上架一个goods_id
type MsgGS2CLAddMallNotice struct {
	Goods *MallGoodsInfo `protobuf:"bytes,1,opt,name=goods" json:"goods,omitempty"`
	IsPop bool           `protobuf:"varint,2,opt,name=is_pop,json=isPop" json:"is_pop,omitempty"`
}

func (m *MsgGS2CLAddMallNotice) Reset()                    { *m = MsgGS2CLAddMallNotice{} }
func (m *MsgGS2CLAddMallNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLAddMallNotice) ProtoMessage()               {}
func (*MsgGS2CLAddMallNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{2} }

func (m *MsgGS2CLAddMallNotice) GetGoods() *MallGoodsInfo {
	if m != nil {
		return m.Goods
	}
	return nil
}

func (m *MsgGS2CLAddMallNotice) GetIsPop() bool {
	if m != nil {
		return m.IsPop
	}
	return false
}

// 下架一个goods_id
type MsgGS2CLRemoveMallNotice struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
}

func (m *MsgGS2CLRemoveMallNotice) Reset()                    { *m = MsgGS2CLRemoveMallNotice{} }
func (m *MsgGS2CLRemoveMallNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLRemoveMallNotice) ProtoMessage()               {}
func (*MsgGS2CLRemoveMallNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{3} }

func (m *MsgGS2CLRemoveMallNotice) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

// 领取首充奖励
type MsgCL2GSFirstChargeRewardRequest struct {
}

func (m *MsgCL2GSFirstChargeRewardRequest) Reset()         { *m = MsgCL2GSFirstChargeRewardRequest{} }
func (m *MsgCL2GSFirstChargeRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSFirstChargeRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSFirstChargeRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{4}
}

// 领取首充奖励回复
type MsgCL2GSFirstChargeRewardReply struct {
	Awards    []*Resource `protobuf:"bytes,1,rep,name=awards" json:"awards,omitempty"`
	ErrorCode int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSFirstChargeRewardReply) Reset()                    { *m = MsgCL2GSFirstChargeRewardReply{} }
func (m *MsgCL2GSFirstChargeRewardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSFirstChargeRewardReply) ProtoMessage()               {}
func (*MsgCL2GSFirstChargeRewardReply) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{5} }

func (m *MsgCL2GSFirstChargeRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSFirstChargeRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 商城充值通用reply
type MsgCL2GSChargeCommonReply struct {
	GoodsId   uint32      `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	Awards    []*Resource `protobuf:"bytes,2,rep,name=awards" json:"awards,omitempty"`
	ErrorCode int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSChargeCommonReply) Reset()                    { *m = MsgCL2GSChargeCommonReply{} }
func (m *MsgCL2GSChargeCommonReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSChargeCommonReply) ProtoMessage()               {}
func (*MsgCL2GSChargeCommonReply) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{6} }

func (m *MsgCL2GSChargeCommonReply) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MsgCL2GSChargeCommonReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSChargeCommonReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 所有商城信息
type MsgGS2CLMallAllDataNotice struct {
	CommonData   *MallCommonData       `protobuf:"bytes,1,opt,name=common_data,json=commonData" json:"common_data,omitempty"`
	FirstCharge  *MallFirstChargeData  `protobuf:"bytes,2,opt,name=first_charge,json=firstCharge" json:"first_charge,omitempty"`
	EverydayHero *MallEverydayHeroData `protobuf:"bytes,3,opt,name=everyday_hero,json=everydayHero" json:"everyday_hero,omitempty"`
	ChooseGift   *MallChooseGiftData   `protobuf:"bytes,4,opt,name=choose_gift,json=chooseGift" json:"choose_gift,omitempty"`
	TotalCharge  *MallTotalChargeData  `protobuf:"bytes,5,opt,name=total_charge,json=totalCharge" json:"total_charge,omitempty"`
	MoneySell    *MallMoneySellData    `protobuf:"bytes,6,opt,name=money_sell,json=moneySell" json:"money_sell,omitempty"`
	TimeCard     *MallTimeCardData     `protobuf:"bytes,7,opt,name=time_card,json=timeCard" json:"time_card,omitempty"`
	GrowthFund   *MallGrowthFundData   `protobuf:"bytes,8,opt,name=growth_fund,json=growthFund" json:"growth_fund,omitempty"`
	PopOutGift   *MallPopOutGiftData   `protobuf:"bytes,9,opt,name=pop_out_gift,json=popOutGift" json:"pop_out_gift,omitempty"`
	MysteryData  *MallMysteryData      `protobuf:"bytes,10,opt,name=mystery_data,json=mysteryData" json:"mystery_data,omitempty"`
	PiggySavings *MallPiggySavings     `protobuf:"bytes,11,opt,name=piggy_savings,json=piggySavings" json:"piggy_savings,omitempty"`
}

func (m *MsgGS2CLMallAllDataNotice) Reset()                    { *m = MsgGS2CLMallAllDataNotice{} }
func (m *MsgGS2CLMallAllDataNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMallAllDataNotice) ProtoMessage()               {}
func (*MsgGS2CLMallAllDataNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{7} }

func (m *MsgGS2CLMallAllDataNotice) GetCommonData() *MallCommonData {
	if m != nil {
		return m.CommonData
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetFirstCharge() *MallFirstChargeData {
	if m != nil {
		return m.FirstCharge
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetEverydayHero() *MallEverydayHeroData {
	if m != nil {
		return m.EverydayHero
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetChooseGift() *MallChooseGiftData {
	if m != nil {
		return m.ChooseGift
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetTotalCharge() *MallTotalChargeData {
	if m != nil {
		return m.TotalCharge
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetMoneySell() *MallMoneySellData {
	if m != nil {
		return m.MoneySell
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetTimeCard() *MallTimeCardData {
	if m != nil {
		return m.TimeCard
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetGrowthFund() *MallGrowthFundData {
	if m != nil {
		return m.GrowthFund
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetPopOutGift() *MallPopOutGiftData {
	if m != nil {
		return m.PopOutGift
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetMysteryData() *MallMysteryData {
	if m != nil {
		return m.MysteryData
	}
	return nil
}

func (m *MsgGS2CLMallAllDataNotice) GetPiggySavings() *MallPiggySavings {
	if m != nil {
		return m.PiggySavings
	}
	return nil
}

// 普通商城数据
type MsgGS2CLMallOrderDataNotice struct {
	Order *MallOrder `protobuf:"bytes,1,opt,name=order" json:"order,omitempty"`
}

func (m *MsgGS2CLMallOrderDataNotice) Reset()                    { *m = MsgGS2CLMallOrderDataNotice{} }
func (m *MsgGS2CLMallOrderDataNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMallOrderDataNotice) ProtoMessage()               {}
func (*MsgGS2CLMallOrderDataNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{8} }

func (m *MsgGS2CLMallOrderDataNotice) GetOrder() *MallOrder {
	if m != nil {
		return m.Order
	}
	return nil
}

// 商城首充信息
type MsgGS2CLMallFirstChargeNotice struct {
	Data *MallFirstChargeData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2CLMallFirstChargeNotice) Reset()                    { *m = MsgGS2CLMallFirstChargeNotice{} }
func (m *MsgGS2CLMallFirstChargeNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMallFirstChargeNotice) ProtoMessage()               {}
func (*MsgGS2CLMallFirstChargeNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{9} }

func (m *MsgGS2CLMallFirstChargeNotice) GetData() *MallFirstChargeData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 商城累充通知
type MsgGS2CLMallTotalChargeNotice struct {
	Data *MallTotalChargeData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2CLMallTotalChargeNotice) Reset()                    { *m = MsgGS2CLMallTotalChargeNotice{} }
func (m *MsgGS2CLMallTotalChargeNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMallTotalChargeNotice) ProtoMessage()               {}
func (*MsgGS2CLMallTotalChargeNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{10} }

func (m *MsgGS2CLMallTotalChargeNotice) GetData() *MallTotalChargeData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 商城每日英雄限购通知
type MsgGS2CLMallEverydayHeroNotice struct {
	PlaceGoodsId map[uint32]uint32 `protobuf:"bytes,1,rep,name=place_goods_id,json=placeGoodsId" json:"place_goods_id,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *MsgGS2CLMallEverydayHeroNotice) Reset()         { *m = MsgGS2CLMallEverydayHeroNotice{} }
func (m *MsgGS2CLMallEverydayHeroNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLMallEverydayHeroNotice) ProtoMessage()    {}
func (*MsgGS2CLMallEverydayHeroNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{11}
}

func (m *MsgGS2CLMallEverydayHeroNotice) GetPlaceGoodsId() map[uint32]uint32 {
	if m != nil {
		return m.PlaceGoodsId
	}
	return nil
}

// 领取每日英雄限购免费礼包
type MsgCL2GSEverydayHeroFreeRequest struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
}

func (m *MsgCL2GSEverydayHeroFreeRequest) Reset()         { *m = MsgCL2GSEverydayHeroFreeRequest{} }
func (m *MsgCL2GSEverydayHeroFreeRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSEverydayHeroFreeRequest) ProtoMessage()    {}
func (*MsgCL2GSEverydayHeroFreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{12}
}

func (m *MsgCL2GSEverydayHeroFreeRequest) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

// 领取每日英雄限购免费礼包回复
type MsgCL2GSEverydayHeroFreeReply struct {
	Awards    []*Resource `protobuf:"bytes,1,rep,name=awards" json:"awards,omitempty"`
	GoodsId   uint32      `protobuf:"varint,2,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	ErrorCode int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSEverydayHeroFreeReply) Reset()                    { *m = MsgCL2GSEverydayHeroFreeReply{} }
func (m *MsgCL2GSEverydayHeroFreeReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSEverydayHeroFreeReply) ProtoMessage()               {}
func (*MsgCL2GSEverydayHeroFreeReply) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{13} }

func (m *MsgCL2GSEverydayHeroFreeReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSEverydayHeroFreeReply) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MsgCL2GSEverydayHeroFreeReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取累充奖励
type MsgCL2GSTotalChargeRewardRequest struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
}

func (m *MsgCL2GSTotalChargeRewardRequest) Reset()         { *m = MsgCL2GSTotalChargeRewardRequest{} }
func (m *MsgCL2GSTotalChargeRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSTotalChargeRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSTotalChargeRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{14}
}

func (m *MsgCL2GSTotalChargeRewardRequest) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

// 领取累充奖励回复
type MsgCL2GSTotalChargeRewardReply struct {
	Awards    []*Resource `protobuf:"bytes,1,rep,name=awards" json:"awards,omitempty"`
	GoodsId   uint32      `protobuf:"varint,2,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	ErrorCode int32       `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSTotalChargeRewardReply) Reset()         { *m = MsgCL2GSTotalChargeRewardReply{} }
func (m *MsgCL2GSTotalChargeRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSTotalChargeRewardReply) ProtoMessage()    {}
func (*MsgCL2GSTotalChargeRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{15}
}

func (m *MsgCL2GSTotalChargeRewardReply) GetAwards() []*Resource {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *MsgCL2GSTotalChargeRewardReply) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MsgCL2GSTotalChargeRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取周月卡奖励
type MsgCL2GSTimeCardRewardRequest struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
}

func (m *MsgCL2GSTimeCardRewardRequest) Reset()                    { *m = MsgCL2GSTimeCardRewardRequest{} }
func (m *MsgCL2GSTimeCardRewardRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSTimeCardRewardRequest) ProtoMessage()               {}
func (*MsgCL2GSTimeCardRewardRequest) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{16} }

func (m *MsgCL2GSTimeCardRewardRequest) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

// 领取周月卡回复
type MsgCL2GSTimeCardRewardReply struct {
	TimeCard  *MallTimeCard `protobuf:"bytes,1,opt,name=time_card,json=timeCard" json:"time_card,omitempty"`
	Rewards   *ResourceSet  `protobuf:"bytes,2,opt,name=rewards" json:"rewards,omitempty"`
	ErrorCode int32         `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSTimeCardRewardReply) Reset()                    { *m = MsgCL2GSTimeCardRewardReply{} }
func (m *MsgCL2GSTimeCardRewardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSTimeCardRewardReply) ProtoMessage()               {}
func (*MsgCL2GSTimeCardRewardReply) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{17} }

func (m *MsgCL2GSTimeCardRewardReply) GetTimeCard() *MallTimeCard {
	if m != nil {
		return m.TimeCard
	}
	return nil
}

func (m *MsgCL2GSTimeCardRewardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgCL2GSTimeCardRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type MsgGS2CLBuyTimeCardNotice struct {
	TimeCard *MallTimeCard `protobuf:"bytes,1,opt,name=time_card,json=timeCard" json:"time_card,omitempty"`
	Rewards  *ResourceSet  `protobuf:"bytes,2,opt,name=rewards" json:"rewards,omitempty"`
}

func (m *MsgGS2CLBuyTimeCardNotice) Reset()                    { *m = MsgGS2CLBuyTimeCardNotice{} }
func (m *MsgGS2CLBuyTimeCardNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLBuyTimeCardNotice) ProtoMessage()               {}
func (*MsgGS2CLBuyTimeCardNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{18} }

func (m *MsgGS2CLBuyTimeCardNotice) GetTimeCard() *MallTimeCard {
	if m != nil {
		return m.TimeCard
	}
	return nil
}

func (m *MsgGS2CLBuyTimeCardNotice) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

// 领取成长基金奖励
type MsgCL2GSGrowthFundRewardRequest struct {
	GoodsId uint32 `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	Level   uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}

func (m *MsgCL2GSGrowthFundRewardRequest) Reset()         { *m = MsgCL2GSGrowthFundRewardRequest{} }
func (m *MsgCL2GSGrowthFundRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSGrowthFundRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSGrowthFundRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{19}
}

func (m *MsgCL2GSGrowthFundRewardRequest) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MsgCL2GSGrowthFundRewardRequest) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

// 领取成长基金回复
type MsgCL2GSGrowthFundRewardReply struct {
	GoodsId   uint32       `protobuf:"varint,1,opt,name=goods_id,json=goodsId" json:"goods_id,omitempty"`
	Level     uint32       `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Rewards   *ResourceSet `protobuf:"bytes,3,opt,name=rewards" json:"rewards,omitempty"`
	ErrorCode int32        `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSGrowthFundRewardReply) Reset()                    { *m = MsgCL2GSGrowthFundRewardReply{} }
func (m *MsgCL2GSGrowthFundRewardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSGrowthFundRewardReply) ProtoMessage()               {}
func (*MsgCL2GSGrowthFundRewardReply) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{20} }

func (m *MsgCL2GSGrowthFundRewardReply) GetGoodsId() uint32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *MsgCL2GSGrowthFundRewardReply) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MsgCL2GSGrowthFundRewardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgCL2GSGrowthFundRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 领取小猪储蓄罐奖励
type MsgCL2GSPiggySavingsRewardRequest struct {
}

func (m *MsgCL2GSPiggySavingsRewardRequest) Reset()         { *m = MsgCL2GSPiggySavingsRewardRequest{} }
func (m *MsgCL2GSPiggySavingsRewardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSPiggySavingsRewardRequest) ProtoMessage()    {}
func (*MsgCL2GSPiggySavingsRewardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{21}
}

// 领取小猪储蓄罐回复
type MsgCL2GSPiggySavingsRewardReply struct {
	Rewards   *ResourceSet `protobuf:"bytes,1,opt,name=rewards" json:"rewards,omitempty"`
	ErrorCode int32        `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSPiggySavingsRewardReply) Reset()         { *m = MsgCL2GSPiggySavingsRewardReply{} }
func (m *MsgCL2GSPiggySavingsRewardReply) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSPiggySavingsRewardReply) ProtoMessage()    {}
func (*MsgCL2GSPiggySavingsRewardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor28, []int{22}
}

func (m *MsgCL2GSPiggySavingsRewardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgCL2GSPiggySavingsRewardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 同步小猪储钱罐信息
type MsgGS2CLPiggySavingsNotice struct {
	Data *MallPiggySavings `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2CLPiggySavingsNotice) Reset()                    { *m = MsgGS2CLPiggySavingsNotice{} }
func (m *MsgGS2CLPiggySavingsNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLPiggySavingsNotice) ProtoMessage()               {}
func (*MsgGS2CLPiggySavingsNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{23} }

func (m *MsgGS2CLPiggySavingsNotice) GetData() *MallPiggySavings {
	if m != nil {
		return m.Data
	}
	return nil
}

type MsgGS2CLBuyGrowthFundNotice struct {
	GrowthFund *MallGrowthFund `protobuf:"bytes,1,opt,name=growth_fund,json=growthFund" json:"growth_fund,omitempty"`
	Rewards    *ResourceSet    `protobuf:"bytes,2,opt,name=rewards" json:"rewards,omitempty"`
}

func (m *MsgGS2CLBuyGrowthFundNotice) Reset()                    { *m = MsgGS2CLBuyGrowthFundNotice{} }
func (m *MsgGS2CLBuyGrowthFundNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLBuyGrowthFundNotice) ProtoMessage()               {}
func (*MsgGS2CLBuyGrowthFundNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{24} }

func (m *MsgGS2CLBuyGrowthFundNotice) GetGrowthFund() *MallGrowthFund {
	if m != nil {
		return m.GrowthFund
	}
	return nil
}

func (m *MsgGS2CLBuyGrowthFundNotice) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

type MsgGS2CLMysteryMallNotice struct {
	Data *MallMysteryData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2CLMysteryMallNotice) Reset()                    { *m = MsgGS2CLMysteryMallNotice{} }
func (m *MsgGS2CLMysteryMallNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMysteryMallNotice) ProtoMessage()               {}
func (*MsgGS2CLMysteryMallNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{25} }

func (m *MsgGS2CLMysteryMallNotice) GetData() *MallMysteryData {
	if m != nil {
		return m.Data
	}
	return nil
}

// 同步服务器开服时间
type MsgGS2CLServerStartTimeNotice struct {
	StartTime int64 `protobuf:"varint,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
}

func (m *MsgGS2CLServerStartTimeNotice) Reset()                    { *m = MsgGS2CLServerStartTimeNotice{} }
func (m *MsgGS2CLServerStartTimeNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLServerStartTimeNotice) ProtoMessage()               {}
func (*MsgGS2CLServerStartTimeNotice) Descriptor() ([]byte, []int) { return fileDescriptor28, []int{26} }

func (m *MsgGS2CLServerStartTimeNotice) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*MallGoodsInfo)(nil), "protomsg.MallGoodsInfo")
	proto.RegisterType((*MsgGS2CLAllMallNotice)(nil), "protomsg.MsgGS2CLAllMallNotice")
	proto.RegisterType((*MsgGS2CLAddMallNotice)(nil), "protomsg.MsgGS2CLAddMallNotice")
	proto.RegisterType((*MsgGS2CLRemoveMallNotice)(nil), "protomsg.MsgGS2CLRemoveMallNotice")
	proto.RegisterType((*MsgCL2GSFirstChargeRewardRequest)(nil), "protomsg.MsgCL2GSFirstChargeRewardRequest")
	proto.RegisterType((*MsgCL2GSFirstChargeRewardReply)(nil), "protomsg.MsgCL2GSFirstChargeRewardReply")
	proto.RegisterType((*MsgCL2GSChargeCommonReply)(nil), "protomsg.MsgCL2GSChargeCommonReply")
	proto.RegisterType((*MsgGS2CLMallAllDataNotice)(nil), "protomsg.MsgGS2CLMallAllDataNotice")
	proto.RegisterType((*MsgGS2CLMallOrderDataNotice)(nil), "protomsg.MsgGS2CLMallOrderDataNotice")
	proto.RegisterType((*MsgGS2CLMallFirstChargeNotice)(nil), "protomsg.MsgGS2CLMallFirstChargeNotice")
	proto.RegisterType((*MsgGS2CLMallTotalChargeNotice)(nil), "protomsg.MsgGS2CLMallTotalChargeNotice")
	proto.RegisterType((*MsgGS2CLMallEverydayHeroNotice)(nil), "protomsg.MsgGS2CLMallEverydayHeroNotice")
	proto.RegisterType((*MsgCL2GSEverydayHeroFreeRequest)(nil), "protomsg.MsgCL2GSEverydayHeroFreeRequest")
	proto.RegisterType((*MsgCL2GSEverydayHeroFreeReply)(nil), "protomsg.MsgCL2GSEverydayHeroFreeReply")
	proto.RegisterType((*MsgCL2GSTotalChargeRewardRequest)(nil), "protomsg.MsgCL2GSTotalChargeRewardRequest")
	proto.RegisterType((*MsgCL2GSTotalChargeRewardReply)(nil), "protomsg.MsgCL2GSTotalChargeRewardReply")
	proto.RegisterType((*MsgCL2GSTimeCardRewardRequest)(nil), "protomsg.MsgCL2GSTimeCardRewardRequest")
	proto.RegisterType((*MsgCL2GSTimeCardRewardReply)(nil), "protomsg.MsgCL2GSTimeCardRewardReply")
	proto.RegisterType((*MsgGS2CLBuyTimeCardNotice)(nil), "protomsg.MsgGS2CLBuyTimeCardNotice")
	proto.RegisterType((*MsgCL2GSGrowthFundRewardRequest)(nil), "protomsg.MsgCL2GSGrowthFundRewardRequest")
	proto.RegisterType((*MsgCL2GSGrowthFundRewardReply)(nil), "protomsg.MsgCL2GSGrowthFundRewardReply")
	proto.RegisterType((*MsgCL2GSPiggySavingsRewardRequest)(nil), "protomsg.MsgCL2GSPiggySavingsRewardRequest")
	proto.RegisterType((*MsgCL2GSPiggySavingsRewardReply)(nil), "protomsg.MsgCL2GSPiggySavingsRewardReply")
	proto.RegisterType((*MsgGS2CLPiggySavingsNotice)(nil), "protomsg.MsgGS2CLPiggySavingsNotice")
	proto.RegisterType((*MsgGS2CLBuyGrowthFundNotice)(nil), "protomsg.MsgGS2CLBuyGrowthFundNotice")
	proto.RegisterType((*MsgGS2CLMysteryMallNotice)(nil), "protomsg.MsgGS2CLMysteryMallNotice")
	proto.RegisterType((*MsgGS2CLServerStartTimeNotice)(nil), "protomsg.MsgGS2CLServerStartTimeNotice")
}

func init() { proto.RegisterFile("mall.proto", fileDescriptor28) }

var fileDescriptor28 = []byte{
	// 1025 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x8f, 0xdb, 0x44,
	0x10, 0x97, 0x2f, 0xcd, 0x5d, 0x32, 0x49, 0x50, 0x31, 0x1c, 0xf8, 0x52, 0xae, 0x04, 0xf3, 0x72,
	0x20, 0x11, 0xc4, 0x55, 0x08, 0x38, 0xf5, 0x0f, 0x6d, 0xb8, 0x4b, 0x8b, 0xee, 0xe8, 0x69, 0xd3,
	0x57, 0x64, 0x8c, 0x3d, 0xf1, 0x59, 0xb5, 0xb3, 0xee, 0x7a, 0x9d, 0xca, 0x8f, 0x3c, 0x80, 0xc4,
	0xb7, 0x40, 0x7c, 0x15, 0x3e, 0x01, 0xdf, 0x08, 0xed, 0xae, 0x1d, 0xaf, 0x73, 0x6e, 0xee, 0x2a,
	0xaa, 0x3e, 0x25, 0xb3, 0x99, 0xf9, 0xed, 0xfc, 0x66, 0x67, 0x7f, 0xb3, 0x01, 0x88, 0xdd, 0x28,
	0x1a, 0x27, 0x8c, 0x72, 0x6a, 0x76, 0xe4, 0x47, 0x9c, 0x06, 0xc3, 0xdd, 0x38, 0x0d, 0x1c, 0x8f,
	0xc6, 0x31, 0x5d, 0x38, 0x95, 0xc3, 0xf0, 0x66, 0xb5, 0xac, 0x56, 0xec, 0x63, 0x18, 0x9c, 0xb9,
	0x51, 0x34, 0xa5, 0xd4, 0x4f, 0x9f, 0x2c, 0xe6, 0xd4, 0xdc, 0x83, 0x4e, 0x20, 0x0c, 0x27, 0xf4,
	0x2d, 0x63, 0x64, 0x1c, 0x0c, 0xc8, 0x8e, 0xb4, 0x9f, 0xf8, 0xe2, 0x27, 0x5c, 0xf8, 0x0e, 0x0f,
	0x63, 0xb4, 0xb6, 0x46, 0xc6, 0x41, 0x8b, 0xec, 0xe0, 0xc2, 0x7f, 0x16, 0xc6, 0x68, 0x9f, 0xc0,
	0xee, 0x59, 0x1a, 0x4c, 0x67, 0x87, 0x93, 0xd3, 0x87, 0x51, 0x24, 0x10, 0x7f, 0xa2, 0x3c, 0xf4,
	0xd0, 0xfc, 0x02, 0xda, 0x32, 0xdc, 0x32, 0x46, 0xad, 0x83, 0xde, 0xe1, 0x87, 0xe3, 0x32, 0xc5,
	0x71, 0x6d, 0x5b, 0xa2, 0xbc, 0xec, 0x9f, 0x35, 0x1c, 0xdf, 0x6f, 0xc6, 0x31, 0xae, 0xc6, 0x31,
	0x77, 0x61, 0x3b, 0x4c, 0x9d, 0x84, 0x26, 0x32, 0xd1, 0x0e, 0x69, 0x87, 0xe9, 0x39, 0x4d, 0xec,
	0xaf, 0xc1, 0x2a, 0xe1, 0x09, 0xc6, 0x74, 0x89, 0xda, 0x0e, 0xaf, 0x26, 0x6e, 0xdb, 0x30, 0x3a,
	0x4b, 0x83, 0xc9, 0xe9, 0xe1, 0x74, 0x76, 0x12, 0xb2, 0x94, 0x4f, 0x2e, 0x5c, 0x16, 0x20, 0xc1,
	0x97, 0x2e, 0xf3, 0x09, 0xbe, 0xc8, 0x30, 0xe5, 0xf6, 0x73, 0xb8, 0xbd, 0xc1, 0x27, 0x89, 0x72,
	0xf3, 0x73, 0xd8, 0x76, 0x85, 0x55, 0xd6, 0xc2, 0xac, 0x38, 0x10, 0x4c, 0x69, 0xc6, 0x3c, 0x24,
	0x85, 0x87, 0xb9, 0x0f, 0x80, 0x8c, 0x51, 0xe6, 0x78, 0xd4, 0x47, 0xcb, 0x1b, 0x19, 0x07, 0x6d,
	0xd2, 0x95, 0x2b, 0x13, 0xea, 0xa3, 0xfd, 0x9b, 0x01, 0x7b, 0xe5, 0x6e, 0x6a, 0xa3, 0x89, 0x3c,
	0x54, 0xb5, 0xd1, 0x86, 0x23, 0xac, 0x72, 0xd8, 0xfa, 0xbf, 0x39, 0xfc, 0xdb, 0x96, 0x39, 0xc8,
	0x62, 0x8a, 0x32, 0x3e, 0x8c, 0xa2, 0x1f, 0x5c, 0xee, 0x16, 0xd5, 0xfc, 0x0e, 0x7a, 0x45, 0xfb,
	0xf9, 0x2e, 0x77, 0x8b, 0x53, 0xb3, 0xea, 0xa7, 0xa6, 0x72, 0x16, 0x41, 0x04, 0xbc, 0xd5, 0x77,
	0xf3, 0x7b, 0xe8, 0xcf, 0x45, 0x05, 0x1d, 0x4f, 0x32, 0x93, 0x27, 0xd8, 0x3b, 0xdc, 0xaf, 0xc7,
	0x6a, 0x35, 0x96, 0x00, 0xbd, 0x79, 0xb5, 0x60, 0x4e, 0x60, 0x80, 0x4b, 0x64, 0xb9, 0xef, 0xe6,
	0xce, 0x05, 0x32, 0x6a, 0xb5, 0x24, 0xc4, 0xed, 0x3a, 0xc4, 0x71, 0xe1, 0xf2, 0x18, 0x19, 0x95,
	0x18, 0x7d, 0xd4, 0x56, 0xcc, 0x7b, 0xd0, 0xf3, 0x2e, 0x28, 0x4d, 0xd1, 0x09, 0xc2, 0x39, 0xb7,
	0x6e, 0x48, 0x88, 0x8f, 0xd6, 0x18, 0x48, 0x87, 0x69, 0x38, 0xe7, 0x05, 0x8b, 0x95, 0x2d, 0x58,
	0x70, 0xca, 0xdd, 0xa8, 0x64, 0xd1, 0x6e, 0x62, 0xf1, 0x4c, 0x78, 0xe8, 0x2c, 0x78, 0xb5, 0x60,
	0x1e, 0x01, 0xc4, 0x74, 0x81, 0xb9, 0x93, 0x62, 0x14, 0x59, 0xdb, 0x32, 0xfe, 0x56, 0x3d, 0xfe,
	0x4c, 0xfc, 0x3e, 0x43, 0x55, 0x79, 0xd2, 0x8d, 0x4b, 0xd3, 0xfc, 0x06, 0xba, 0xe2, 0x9a, 0x3a,
	0x9e, 0xcb, 0x7c, 0x6b, 0x47, 0x86, 0x0e, 0xd7, 0xb6, 0x0e, 0x63, 0x9c, 0xb8, 0xcc, 0x97, 0x91,
	0x1d, 0x5e, 0x58, 0x82, 0x75, 0xc0, 0xe8, 0x4b, 0x7e, 0xe1, 0xcc, 0xb3, 0x85, 0x6f, 0x75, 0x9a,
	0x58, 0x4f, 0xa5, 0xc3, 0x49, 0xb6, 0x50, 0xc1, 0x10, 0xac, 0x6c, 0xf3, 0x3e, 0xf4, 0x13, 0x9a,
	0x38, 0x34, 0xe3, 0xaa, 0x6a, 0xdd, 0xa6, 0xf8, 0x73, 0x9a, 0x3c, 0xcd, 0x78, 0x55, 0xb5, 0x64,
	0x65, 0x9b, 0x77, 0xa1, 0x1f, 0xe7, 0x29, 0x47, 0x96, 0xab, 0xbe, 0x01, 0x19, 0xbf, 0xb7, 0xc6,
	0x5a, 0x79, 0xa8, 0x8a, 0xc5, 0x95, 0x61, 0x3e, 0x80, 0x41, 0x12, 0x06, 0x41, 0xee, 0xa4, 0xee,
	0x32, 0x5c, 0x04, 0xa9, 0xd5, 0x6b, 0x62, 0x7e, 0x2e, 0x5c, 0x66, 0xca, 0x83, 0xf4, 0x13, 0xcd,
	0xb2, 0x1f, 0xc3, 0x2d, 0xbd, 0xa5, 0x9f, 0x32, 0x1f, 0x99, 0xd6, 0xd4, 0x9f, 0x41, 0x9b, 0x8a,
	0xa5, 0xa2, 0x9d, 0xdf, 0xab, 0xe3, 0x4a, 0x6f, 0xa2, 0x3c, 0x6c, 0x02, 0xfb, 0x3a, 0x92, 0xd6,
	0xae, 0x05, 0xd6, 0x57, 0x70, 0x43, 0xbb, 0x19, 0x57, 0x74, 0xb7, 0x74, 0x5d, 0xc7, 0xd4, 0x9a,
	0xe7, 0x3a, 0x98, 0xeb, 0xbd, 0xa6, 0x30, 0xff, 0x31, 0xa4, 0x6e, 0xad, 0x40, 0xf5, 0x4b, 0x51,
	0xa0, 0xfe, 0x02, 0xef, 0x24, 0x91, 0xeb, 0xa1, 0xa3, 0x89, 0x8a, 0xd0, 0x8e, 0x23, 0x0d, 0x7f,
	0x23, 0xc2, 0xf8, 0x5c, 0x84, 0x2b, 0x8d, 0xf6, 0x8f, 0x17, 0x9c, 0xe5, 0xa4, 0x9f, 0x68, 0x4b,
	0xc3, 0x07, 0xf0, 0xee, 0x25, 0x17, 0xf3, 0x26, 0xb4, 0x9e, 0x63, 0x5e, 0x08, 0x98, 0xf8, 0x6a,
	0xbe, 0x0f, 0xed, 0xa5, 0x1b, 0x65, 0x4a, 0x11, 0x06, 0x44, 0x19, 0x47, 0x5b, 0xdf, 0x1a, 0xf6,
	0x5d, 0xf8, 0xb8, 0x94, 0x43, 0x7d, 0xfb, 0x13, 0x86, 0x58, 0xe8, 0xf3, 0x26, 0x79, 0xff, 0xdd,
	0x90, 0x85, 0x7d, 0x45, 0xf8, 0xeb, 0x4a, 0xb7, 0xbe, 0xd1, 0x56, 0x5d, 0x7d, 0xaf, 0x50, 0xd4,
	0x7b, 0xd5, 0x98, 0xd1, 0x0e, 0xab, 0x36, 0x66, 0x36, 0xd1, 0xf8, 0xc3, 0xa8, 0x46, 0x50, 0x43,
	0xfc, 0xdb, 0xe3, 0x71, 0x54, 0x95, 0xb3, 0x54, 0x99, 0x6b, 0x93, 0xf8, 0xdb, 0x90, 0x57, 0xb0,
	0x31, 0x58, 0x30, 0xb8, 0xa3, 0x0b, 0x9b, 0xea, 0xf3, 0x0f, 0x9a, 0x85, 0x4d, 0x13, 0xb5, 0x2f,
	0x61, 0x87, 0x61, 0x39, 0xf6, 0x44, 0xc8, 0xee, 0x65, 0xde, 0x33, 0xe4, 0xa4, 0xf4, 0xba, 0xe6,
	0xf8, 0x95, 0x2d, 0xff, 0x28, 0xcb, 0xcb, 0x1d, 0x8b, 0xfb, 0xf2, 0x56, 0x52, 0xb4, 0x49, 0xd5,
	0xf2, 0x95, 0x1e, 0x5f, 0xb7, 0xcc, 0xe2, 0x2a, 0x45, 0xb8, 0xc4, 0xa8, 0xbc, 0x4a, 0xd2, 0xb0,
	0xff, 0xd2, 0x2e, 0xc2, 0x65, 0xd0, 0x2b, 0x9e, 0x16, 0x8d, 0x90, 0x3a, 0xaf, 0xd6, 0x9b, 0x28,
	0xfd, 0xa7, 0xf0, 0x49, 0x99, 0x61, 0x4d, 0xc7, 0x6b, 0x6f, 0xb1, 0x17, 0x55, 0x6d, 0x9a, 0x9c,
	0x04, 0x11, 0x2d, 0x2f, 0xe3, 0x4d, 0xe4, 0x75, 0x0a, 0xc3, 0xb2, 0x23, 0xf4, 0x2d, 0x8b, 0x96,
	0x18, 0xd7, 0x84, 0x79, 0xd3, 0x3c, 0x52, 0xaa, 0xfc, 0xa7, 0x51, 0x0d, 0xa2, 0x47, 0x59, 0x5e,
	0x9d, 0x45, 0xf5, 0xba, 0xd2, 0xa7, 0x74, 0xe3, 0xeb, 0x4a, 0x3b, 0x40, 0x7d, 0x42, 0xbf, 0x76,
	0xa3, 0xfd, 0xa8, 0x3d, 0xf3, 0xd4, 0xac, 0xad, 0x3d, 0xcb, 0x75, 0x62, 0x1b, 0xe6, 0xb4, 0xe2,
	0x75, 0xbf, 0x9a, 0x60, 0x33, 0x64, 0x4b, 0x64, 0x33, 0xee, 0x32, 0x2e, 0xae, 0x43, 0x81, 0xb7,
	0x0f, 0x90, 0x8a, 0x25, 0xf5, 0x27, 0xc3, 0x90, 0x7f, 0x32, 0xba, 0x69, 0xe9, 0xf4, 0xeb, 0xb6,
	0xc4, 0xbf, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x86, 0x93, 0xf3, 0xf5, 0x0c, 0x00,
	0x00,
}
