// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_server_guild.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *************************** 公会相关 ***************************
type MsgGuild2GSJoinNotice struct {
	PlayerId uint64           `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Info     *PlayerGuildInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGuild2GSJoinNotice) Reset()                    { *m = MsgGuild2GSJoinNotice{} }
func (m *MsgGuild2GSJoinNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSJoinNotice) ProtoMessage()               {}
func (*MsgGuild2GSJoinNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{0} }

func (m *MsgGuild2GSJoinNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSJoinNotice) GetInfo() *PlayerGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MsgGuild2GSQuitNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	GuildId  uint64 `protobuf:"varint,2,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
}

func (m *MsgGuild2GSQuitNotice) Reset()                    { *m = MsgGuild2GSQuitNotice{} }
func (m *MsgGuild2GSQuitNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSQuitNotice) ProtoMessage()               {}
func (*MsgGuild2GSQuitNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{1} }

func (m *MsgGuild2GSQuitNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSQuitNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

// GS通知公会服务器清除玩家公会申请记录
type MsgGS2GuildRemoveApplyRecordNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgGS2GuildRemoveApplyRecordNotice) Reset()         { *m = MsgGS2GuildRemoveApplyRecordNotice{} }
func (m *MsgGS2GuildRemoveApplyRecordNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2GuildRemoveApplyRecordNotice) ProtoMessage()    {}
func (*MsgGS2GuildRemoveApplyRecordNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{2}
}

func (m *MsgGS2GuildRemoveApplyRecordNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type MsgGuild2GSPositionNotice struct {
	PlayerId uint64        `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Position GuildPosition `protobuf:"varint,2,opt,name=position,enum=protomsg.GuildPosition" json:"position,omitempty"`
}

func (m *MsgGuild2GSPositionNotice) Reset()                    { *m = MsgGuild2GSPositionNotice{} }
func (m *MsgGuild2GSPositionNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSPositionNotice) ProtoMessage()               {}
func (*MsgGuild2GSPositionNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{3} }

func (m *MsgGuild2GSPositionNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSPositionNotice) GetPosition() GuildPosition {
	if m != nil {
		return m.Position
	}
	return GuildPosition_kGuildPositionNone
}

// 通知GS玩家官位更改
type MsgGuild2GSOfficialNotice struct {
	PlayerId uint64        `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Official GuildOfficial `protobuf:"varint,2,opt,name=official,enum=protomsg.GuildOfficial" json:"official,omitempty"`
}

func (m *MsgGuild2GSOfficialNotice) Reset()                    { *m = MsgGuild2GSOfficialNotice{} }
func (m *MsgGuild2GSOfficialNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSOfficialNotice) ProtoMessage()               {}
func (*MsgGuild2GSOfficialNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{4} }

func (m *MsgGuild2GSOfficialNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSOfficialNotice) GetOfficial() GuildOfficial {
	if m != nil {
		return m.Official
	}
	return GuildOfficial_kGuildOfficialNone
}

// 更新玩家基础信息
type MsgGS2GuildSearchPlayerInfoNotice struct {
	PlayerId uint64            `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Data     *SearchPlayerInfo `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2GuildSearchPlayerInfoNotice) Reset()         { *m = MsgGS2GuildSearchPlayerInfoNotice{} }
func (m *MsgGS2GuildSearchPlayerInfoNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2GuildSearchPlayerInfoNotice) ProtoMessage()    {}
func (*MsgGS2GuildSearchPlayerInfoNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{5}
}

func (m *MsgGS2GuildSearchPlayerInfoNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2GuildSearchPlayerInfoNotice) GetData() *SearchPlayerInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// 改名通知
type MsgGS2GuildRenameNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *MsgGS2GuildRenameNotice) Reset()                    { *m = MsgGS2GuildRenameNotice{} }
func (m *MsgGS2GuildRenameNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildRenameNotice) ProtoMessage()               {}
func (*MsgGS2GuildRenameNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{6} }

func (m *MsgGS2GuildRenameNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2GuildRenameNotice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 战斗力变化通知
type MsgGS2GuildBattlePowerNotice struct {
	PlayerId    uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	BattlePower uint64 `protobuf:"varint,3,opt,name=battle_power,json=battlePower" json:"battle_power,omitempty"`
}

func (m *MsgGS2GuildBattlePowerNotice) Reset()                    { *m = MsgGS2GuildBattlePowerNotice{} }
func (m *MsgGS2GuildBattlePowerNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildBattlePowerNotice) ProtoMessage()               {}
func (*MsgGS2GuildBattlePowerNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{7} }

func (m *MsgGS2GuildBattlePowerNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2GuildBattlePowerNotice) GetBattlePower() uint64 {
	if m != nil {
		return m.BattlePower
	}
	return 0
}

// 击杀通知
type MsgGS2GuildKillCountNotice struct {
	PlayerId  uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	KillCount uint64 `protobuf:"varint,2,opt,name=kill_count,json=killCount" json:"kill_count,omitempty"`
}

func (m *MsgGS2GuildKillCountNotice) Reset()                    { *m = MsgGS2GuildKillCountNotice{} }
func (m *MsgGS2GuildKillCountNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildKillCountNotice) ProtoMessage()               {}
func (*MsgGS2GuildKillCountNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{8} }

func (m *MsgGS2GuildKillCountNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2GuildKillCountNotice) GetKillCount() uint64 {
	if m != nil {
		return m.KillCount
	}
	return 0
}

// 更新公会名字
type MsgGuild2GSUpdateGuildNameNotice struct {
	PlayerId  uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,3,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
}

func (m *MsgGuild2GSUpdateGuildNameNotice) Reset()         { *m = MsgGuild2GSUpdateGuildNameNotice{} }
func (m *MsgGuild2GSUpdateGuildNameNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSUpdateGuildNameNotice) ProtoMessage()    {}
func (*MsgGuild2GSUpdateGuildNameNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{9}
}

func (m *MsgGuild2GSUpdateGuildNameNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSUpdateGuildNameNotice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgGuild2GSUpdateGuildNameNotice) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

// 更新公会图标通知
type MsgGuild2GSUpdateGuildIconNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Icon     uint32 `protobuf:"varint,2,opt,name=icon" json:"icon,omitempty"`
}

func (m *MsgGuild2GSUpdateGuildIconNotice) Reset()         { *m = MsgGuild2GSUpdateGuildIconNotice{} }
func (m *MsgGuild2GSUpdateGuildIconNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSUpdateGuildIconNotice) ProtoMessage()    {}
func (*MsgGuild2GSUpdateGuildIconNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{10}
}

func (m *MsgGuild2GSUpdateGuildIconNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSUpdateGuildIconNotice) GetIcon() uint32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

// 工会广播通知
type MsgGuild2GSBroadcastNotice struct {
	PlayerId uint64               `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	MsgId    uint32               `protobuf:"varint,2,opt,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	Content  *google_protobuf.Any `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *MsgGuild2GSBroadcastNotice) Reset()                    { *m = MsgGuild2GSBroadcastNotice{} }
func (m *MsgGuild2GSBroadcastNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSBroadcastNotice) ProtoMessage()               {}
func (*MsgGuild2GSBroadcastNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{11} }

func (m *MsgGuild2GSBroadcastNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSBroadcastNotice) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MsgGuild2GSBroadcastNotice) GetContent() *google_protobuf.Any {
	if m != nil {
		return m.Content
	}
	return nil
}

// 通知公会服务器玩家上线
type MsgGS2GuildPlayerLoginNotice struct {
	PlayerId uint64            `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Data     *SearchPlayerInfo `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *MsgGS2GuildPlayerLoginNotice) Reset()                    { *m = MsgGS2GuildPlayerLoginNotice{} }
func (m *MsgGS2GuildPlayerLoginNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildPlayerLoginNotice) ProtoMessage()               {}
func (*MsgGS2GuildPlayerLoginNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{12} }

func (m *MsgGS2GuildPlayerLoginNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGS2GuildPlayerLoginNotice) GetData() *SearchPlayerInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

// 战斗力变化通知
type MsgGuild2GSExpAndLevelNotice struct {
	GuildId uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Exp     uint32 `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	Level   uint32 `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
}

func (m *MsgGuild2GSExpAndLevelNotice) Reset()                    { *m = MsgGuild2GSExpAndLevelNotice{} }
func (m *MsgGuild2GSExpAndLevelNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSExpAndLevelNotice) ProtoMessage()               {}
func (*MsgGuild2GSExpAndLevelNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{13} }

func (m *MsgGuild2GSExpAndLevelNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MsgGuild2GSExpAndLevelNotice) GetExp() uint32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *MsgGuild2GSExpAndLevelNotice) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type MsgGS2GuildPlayerLogoutNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgGS2GuildPlayerLogoutNotice) Reset()                    { *m = MsgGS2GuildPlayerLogoutNotice{} }
func (m *MsgGS2GuildPlayerLogoutNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildPlayerLogoutNotice) ProtoMessage()               {}
func (*MsgGS2GuildPlayerLogoutNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{14} }

func (m *MsgGS2GuildPlayerLogoutNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 玩家加载数据完成，进入cache
type MsgGS2GuildPlayerLoadedNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgGS2GuildPlayerLoadedNotice) Reset()                    { *m = MsgGS2GuildPlayerLoadedNotice{} }
func (m *MsgGS2GuildPlayerLoadedNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildPlayerLoadedNotice) ProtoMessage()               {}
func (*MsgGS2GuildPlayerLoadedNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{15} }

func (m *MsgGS2GuildPlayerLoadedNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

// 玩家释放，离开cache
type MsgGS2GuildPlayerReleaseNotice struct {
	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *MsgGS2GuildPlayerReleaseNotice) Reset()         { *m = MsgGS2GuildPlayerReleaseNotice{} }
func (m *MsgGS2GuildPlayerReleaseNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2GuildPlayerReleaseNotice) ProtoMessage()    {}
func (*MsgGS2GuildPlayerReleaseNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{16}
}

func (m *MsgGS2GuildPlayerReleaseNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type MsgGS2GuildDestroyNotice struct {
	GuildId uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
}

func (m *MsgGS2GuildDestroyNotice) Reset()                    { *m = MsgGS2GuildDestroyNotice{} }
func (m *MsgGS2GuildDestroyNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2GuildDestroyNotice) ProtoMessage()               {}
func (*MsgGS2GuildDestroyNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{17} }

func (m *MsgGS2GuildDestroyNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

// 公会服务器通知GS玩家更新公会更新记录
type MsgGuild2GSApplyRecordNotice struct {
	PlayerId        uint64              `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ApplyingRecords []*GuildApplyRecord `protobuf:"bytes,2,rep,name=applying_records,json=applyingRecords" json:"applying_records,omitempty"`
}

func (m *MsgGuild2GSApplyRecordNotice) Reset()                    { *m = MsgGuild2GSApplyRecordNotice{} }
func (m *MsgGuild2GSApplyRecordNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSApplyRecordNotice) ProtoMessage()               {}
func (*MsgGuild2GSApplyRecordNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{18} }

func (m *MsgGuild2GSApplyRecordNotice) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSApplyRecordNotice) GetApplyingRecords() []*GuildApplyRecord {
	if m != nil {
		return m.ApplyingRecords
	}
	return nil
}

type MsgGuild2GSUpdateGuildInfoRequest struct {
	PlayerId uint64           `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Info     *PlayerGuildInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGuild2GSUpdateGuildInfoRequest) Reset()         { *m = MsgGuild2GSUpdateGuildInfoRequest{} }
func (m *MsgGuild2GSUpdateGuildInfoRequest) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSUpdateGuildInfoRequest) ProtoMessage()    {}
func (*MsgGuild2GSUpdateGuildInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{19}
}

func (m *MsgGuild2GSUpdateGuildInfoRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSUpdateGuildInfoRequest) GetInfo() *PlayerGuildInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MsgGS2GuildUpdateGuildInfoReply struct {
}

func (m *MsgGS2GuildUpdateGuildInfoReply) Reset()         { *m = MsgGS2GuildUpdateGuildInfoReply{} }
func (m *MsgGS2GuildUpdateGuildInfoReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2GuildUpdateGuildInfoReply) ProtoMessage()    {}
func (*MsgGS2GuildUpdateGuildInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{20}
}

type MsgGuild2GSGuildDisbandNotice struct {
	GuildId uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
}

func (m *MsgGuild2GSGuildDisbandNotice) Reset()                    { *m = MsgGuild2GSGuildDisbandNotice{} }
func (m *MsgGuild2GSGuildDisbandNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2GSGuildDisbandNotice) ProtoMessage()               {}
func (*MsgGuild2GSGuildDisbandNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{21} }

func (m *MsgGuild2GSGuildDisbandNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

// /////////////////////////公会搜索////////////////////////////////////
// 同步公会数据
type MsgGuild2GuildSearchSyncDataNotice struct {
	Datas []*GuildBriefData `protobuf:"bytes,1,rep,name=datas" json:"datas,omitempty"`
}

func (m *MsgGuild2GuildSearchSyncDataNotice) Reset()         { *m = MsgGuild2GuildSearchSyncDataNotice{} }
func (m *MsgGuild2GuildSearchSyncDataNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GuildSearchSyncDataNotice) ProtoMessage()    {}
func (*MsgGuild2GuildSearchSyncDataNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{22}
}

func (m *MsgGuild2GuildSearchSyncDataNotice) GetDatas() []*GuildBriefData {
	if m != nil {
		return m.Datas
	}
	return nil
}

type DeleteGuildInfo struct {
	GuildId   uint64 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	ShortName string `protobuf:"bytes,3,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
}

func (m *DeleteGuildInfo) Reset()                    { *m = DeleteGuildInfo{} }
func (m *DeleteGuildInfo) String() string            { return proto.CompactTextString(m) }
func (*DeleteGuildInfo) ProtoMessage()               {}
func (*DeleteGuildInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{23} }

func (m *DeleteGuildInfo) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *DeleteGuildInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeleteGuildInfo) GetShortName() string {
	if m != nil {
		return m.ShortName
	}
	return ""
}

// 删除公会通知
type MsgGuild2GuildSearchDeleteGuildNotice struct {
	DeleteGuilds []*DeleteGuildInfo `protobuf:"bytes,1,rep,name=delete_guilds,json=deleteGuilds" json:"delete_guilds,omitempty"`
}

func (m *MsgGuild2GuildSearchDeleteGuildNotice) Reset()         { *m = MsgGuild2GuildSearchDeleteGuildNotice{} }
func (m *MsgGuild2GuildSearchDeleteGuildNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GuildSearchDeleteGuildNotice) ProtoMessage()    {}
func (*MsgGuild2GuildSearchDeleteGuildNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{24}
}

func (m *MsgGuild2GuildSearchDeleteGuildNotice) GetDeleteGuilds() []*DeleteGuildInfo {
	if m != nil {
		return m.DeleteGuilds
	}
	return nil
}

// GuildServer通知GuildSearchServer数据加载完成
type MsgGuild2GuildSearchLoadDataCompleteNotice struct {
	Count uint32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *MsgGuild2GuildSearchLoadDataCompleteNotice) Reset() {
	*m = MsgGuild2GuildSearchLoadDataCompleteNotice{}
}
func (m *MsgGuild2GuildSearchLoadDataCompleteNotice) String() string {
	return proto.CompactTextString(m)
}
func (*MsgGuild2GuildSearchLoadDataCompleteNotice) ProtoMessage() {}
func (*MsgGuild2GuildSearchLoadDataCompleteNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{25}
}

func (m *MsgGuild2GuildSearchLoadDataCompleteNotice) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GuildAssistExecutor struct {
	Item  *GuildAssistItem `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
	Count uint32           `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *GuildAssistExecutor) Reset()                    { *m = GuildAssistExecutor{} }
func (m *GuildAssistExecutor) String() string            { return proto.CompactTextString(m) }
func (*GuildAssistExecutor) ProtoMessage()               {}
func (*GuildAssistExecutor) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{26} }

func (m *GuildAssistExecutor) GetItem() *GuildAssistItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GuildAssistExecutor) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 通知GS玩家，执行公会帮助
type MsgGuild2GSGuildAssistExecuteHelpNotice struct {
	Executors []*GuildAssistExecutor `protobuf:"bytes,1,rep,name=executors" json:"executors,omitempty"`
	Logon     bool                   `protobuf:"varint,2,opt,name=logon" json:"logon,omitempty"`
}

func (m *MsgGuild2GSGuildAssistExecuteHelpNotice) Reset() {
	*m = MsgGuild2GSGuildAssistExecuteHelpNotice{}
}
func (m *MsgGuild2GSGuildAssistExecuteHelpNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSGuildAssistExecuteHelpNotice) ProtoMessage()    {}
func (*MsgGuild2GSGuildAssistExecuteHelpNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{27}
}

func (m *MsgGuild2GSGuildAssistExecuteHelpNotice) GetExecutors() []*GuildAssistExecutor {
	if m != nil {
		return m.Executors
	}
	return nil
}

func (m *MsgGuild2GSGuildAssistExecuteHelpNotice) GetLogon() bool {
	if m != nil {
		return m.Logon
	}
	return false
}

// 通知GS玩家，公会交互帮助信息更新
type MsgGuild2GSGuildAssistUpdateNotice struct {
	Detail *GuildAssistDetail `protobuf:"bytes,1,opt,name=detail" json:"detail,omitempty"`
}

func (m *MsgGuild2GSGuildAssistUpdateNotice) Reset()         { *m = MsgGuild2GSGuildAssistUpdateNotice{} }
func (m *MsgGuild2GSGuildAssistUpdateNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSGuildAssistUpdateNotice) ProtoMessage()    {}
func (*MsgGuild2GSGuildAssistUpdateNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{28}
}

func (m *MsgGuild2GSGuildAssistUpdateNotice) GetDetail() *GuildAssistDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

// 通知GS玩家，公会敌对信息更新
type MsgGuild2GSGuildHostilityNotice struct {
	HostilityGuildIds []uint64 `protobuf:"varint,1,rep,packed,name=hostility_guild_ids,json=hostilityGuildIds" json:"hostility_guild_ids,omitempty"`
}

func (m *MsgGuild2GSGuildHostilityNotice) Reset()         { *m = MsgGuild2GSGuildHostilityNotice{} }
func (m *MsgGuild2GSGuildHostilityNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2GSGuildHostilityNotice) ProtoMessage()    {}
func (*MsgGuild2GSGuildHostilityNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{29}
}

func (m *MsgGuild2GSGuildHostilityNotice) GetHostilityGuildIds() []uint64 {
	if m != nil {
		return m.HostilityGuildIds
	}
	return nil
}

type MsgGuild2MSGuildEventNotice struct {
	GuildId   uint64     `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EventData *EventData `protobuf:"bytes,2,opt,name=event_data,json=eventData" json:"event_data,omitempty"`
}

func (m *MsgGuild2MSGuildEventNotice) Reset()                    { *m = MsgGuild2MSGuildEventNotice{} }
func (m *MsgGuild2MSGuildEventNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGuild2MSGuildEventNotice) ProtoMessage()               {}
func (*MsgGuild2MSGuildEventNotice) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{30} }

func (m *MsgGuild2MSGuildEventNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MsgGuild2MSGuildEventNotice) GetEventData() *EventData {
	if m != nil {
		return m.EventData
	}
	return nil
}

// MapServer通知GuildServer，公会增加建筑设施信息
type MsgMap2GuildAddGuildFacilityNotice struct {
	GuildId    uint64     `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EntityType EntityType `protobuf:"varint,2,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	EntityId   uint64     `protobuf:"varint,3,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Param      uint64     `protobuf:"varint,4,opt,name=param" json:"param,omitempty"`
	Param2     uint64     `protobuf:"varint,5,opt,name=param2" json:"param2,omitempty"`
	Param3     uint32     `protobuf:"varint,6,opt,name=param3" json:"param3,omitempty"`
}

func (m *MsgMap2GuildAddGuildFacilityNotice) Reset()         { *m = MsgMap2GuildAddGuildFacilityNotice{} }
func (m *MsgMap2GuildAddGuildFacilityNotice) String() string { return proto.CompactTextString(m) }
func (*MsgMap2GuildAddGuildFacilityNotice) ProtoMessage()    {}
func (*MsgMap2GuildAddGuildFacilityNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{31}
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetParam() uint64 {
	if m != nil {
		return m.Param
	}
	return 0
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetParam2() uint64 {
	if m != nil {
		return m.Param2
	}
	return 0
}

func (m *MsgMap2GuildAddGuildFacilityNotice) GetParam3() uint32 {
	if m != nil {
		return m.Param3
	}
	return 0
}

// MapServer通知GuildServer，公会移除建筑设施信息
type MsgMap2GuildRemoveGuildFacilityNotice struct {
	GuildId    uint64     `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	EntityType EntityType `protobuf:"varint,2,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	EntityId   uint64     `protobuf:"varint,3,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Param      uint64     `protobuf:"varint,4,opt,name=param" json:"param,omitempty"`
}

func (m *MsgMap2GuildRemoveGuildFacilityNotice) Reset()         { *m = MsgMap2GuildRemoveGuildFacilityNotice{} }
func (m *MsgMap2GuildRemoveGuildFacilityNotice) String() string { return proto.CompactTextString(m) }
func (*MsgMap2GuildRemoveGuildFacilityNotice) ProtoMessage()    {}
func (*MsgMap2GuildRemoveGuildFacilityNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{32}
}

func (m *MsgMap2GuildRemoveGuildFacilityNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MsgMap2GuildRemoveGuildFacilityNotice) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgMap2GuildRemoveGuildFacilityNotice) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *MsgMap2GuildRemoveGuildFacilityNotice) GetParam() uint64 {
	if m != nil {
		return m.Param
	}
	return 0
}

// PM增加/减少公会资源点数量
type MsgGS2GuildPMUpdateResourceFieldCountNotice struct {
	GuildId uint64                 `protobuf:"varint,1,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	Type    GuildResourceFieldType `protobuf:"varint,2,opt,name=type,enum=protomsg.GuildResourceFieldType" json:"type,omitempty"`
	Count   int32                  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *MsgGS2GuildPMUpdateResourceFieldCountNotice) Reset() {
	*m = MsgGS2GuildPMUpdateResourceFieldCountNotice{}
}
func (m *MsgGS2GuildPMUpdateResourceFieldCountNotice) String() string {
	return proto.CompactTextString(m)
}
func (*MsgGS2GuildPMUpdateResourceFieldCountNotice) ProtoMessage() {}
func (*MsgGS2GuildPMUpdateResourceFieldCountNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{33}
}

func (m *MsgGS2GuildPMUpdateResourceFieldCountNotice) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MsgGS2GuildPMUpdateResourceFieldCountNotice) GetType() GuildResourceFieldType {
	if m != nil {
		return m.Type
	}
	return GuildResourceFieldType_kResourceFieldTypeNone
}

func (m *MsgGS2GuildPMUpdateResourceFieldCountNotice) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 公会服务器通知其他服务器buff效果变更
type MsgGuild2OtherBuffEffectUpdateNotice struct {
	GuildEffects *GuildBuffEffectInfo `protobuf:"bytes,1,opt,name=guild_effects,json=guildEffects" json:"guild_effects,omitempty"`
}

func (m *MsgGuild2OtherBuffEffectUpdateNotice) Reset()         { *m = MsgGuild2OtherBuffEffectUpdateNotice{} }
func (m *MsgGuild2OtherBuffEffectUpdateNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGuild2OtherBuffEffectUpdateNotice) ProtoMessage()    {}
func (*MsgGuild2OtherBuffEffectUpdateNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{34}
}

func (m *MsgGuild2OtherBuffEffectUpdateNotice) GetGuildEffects() *GuildBuffEffectInfo {
	if m != nil {
		return m.GuildEffects
	}
	return nil
}

// 通知其他服务器王国buff效果变更
type MsgGuild2OtherKingdomBuffEffectUpdateNotice struct {
	KingdomEffects *KingdomBuffEffectInfo `protobuf:"bytes,1,opt,name=kingdom_effects,json=kingdomEffects" json:"kingdom_effects,omitempty"`
	CurBuffId      uint32                 `protobuf:"varint,2,opt,name=cur_buff_id,json=curBuffId" json:"cur_buff_id,omitempty"`
	ExpireTime     uint64                 `protobuf:"varint,3,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
}

func (m *MsgGuild2OtherKingdomBuffEffectUpdateNotice) Reset() {
	*m = MsgGuild2OtherKingdomBuffEffectUpdateNotice{}
}
func (m *MsgGuild2OtherKingdomBuffEffectUpdateNotice) String() string {
	return proto.CompactTextString(m)
}
func (*MsgGuild2OtherKingdomBuffEffectUpdateNotice) ProtoMessage() {}
func (*MsgGuild2OtherKingdomBuffEffectUpdateNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{35}
}

func (m *MsgGuild2OtherKingdomBuffEffectUpdateNotice) GetKingdomEffects() *KingdomBuffEffectInfo {
	if m != nil {
		return m.KingdomEffects
	}
	return nil
}

func (m *MsgGuild2OtherKingdomBuffEffectUpdateNotice) GetCurBuffId() uint32 {
	if m != nil {
		return m.CurBuffId
	}
	return 0
}

func (m *MsgGuild2OtherKingdomBuffEffectUpdateNotice) GetExpireTime() uint64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

type PlayerGuildExpInfo struct {
	ExpFromBarbarians uint64 `protobuf:"varint,1,opt,name=exp_from_barbarians,json=expFromBarbarians" json:"exp_from_barbarians,omitempty"`
	ExpFromDonate     uint64 `protobuf:"varint,2,opt,name=exp_from_donate,json=expFromDonate" json:"exp_from_donate,omitempty"`
}

func (m *PlayerGuildExpInfo) Reset()                    { *m = PlayerGuildExpInfo{} }
func (m *PlayerGuildExpInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerGuildExpInfo) ProtoMessage()               {}
func (*PlayerGuildExpInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{36} }

func (m *PlayerGuildExpInfo) GetExpFromBarbarians() uint64 {
	if m != nil {
		return m.ExpFromBarbarians
	}
	return 0
}

func (m *PlayerGuildExpInfo) GetExpFromDonate() uint64 {
	if m != nil {
		return m.ExpFromDonate
	}
	return 0
}

type MsgGuild2GSUpdatePlayerGuildExpInfoRequest struct {
	PlayerId uint64              `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	Info     *PlayerGuildExpInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *MsgGuild2GSUpdatePlayerGuildExpInfoRequest) Reset() {
	*m = MsgGuild2GSUpdatePlayerGuildExpInfoRequest{}
}
func (m *MsgGuild2GSUpdatePlayerGuildExpInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*MsgGuild2GSUpdatePlayerGuildExpInfoRequest) ProtoMessage() {}
func (*MsgGuild2GSUpdatePlayerGuildExpInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{37}
}

func (m *MsgGuild2GSUpdatePlayerGuildExpInfoRequest) GetPlayerId() uint64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *MsgGuild2GSUpdatePlayerGuildExpInfoRequest) GetInfo() *PlayerGuildExpInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MsgGS2GuildUpdatePlayerGuildExpInfoReply struct {
}

func (m *MsgGS2GuildUpdatePlayerGuildExpInfoReply) Reset() {
	*m = MsgGS2GuildUpdatePlayerGuildExpInfoReply{}
}
func (m *MsgGS2GuildUpdatePlayerGuildExpInfoReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2GuildUpdatePlayerGuildExpInfoReply) ProtoMessage()    {}
func (*MsgGS2GuildUpdatePlayerGuildExpInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{38}
}

func init() {
	proto.RegisterType((*MsgGuild2GSJoinNotice)(nil), "protomsg.MsgGuild2GSJoinNotice")
	proto.RegisterType((*MsgGuild2GSQuitNotice)(nil), "protomsg.MsgGuild2GSQuitNotice")
	proto.RegisterType((*MsgGS2GuildRemoveApplyRecordNotice)(nil), "protomsg.MsgGS2GuildRemoveApplyRecordNotice")
	proto.RegisterType((*MsgGuild2GSPositionNotice)(nil), "protomsg.MsgGuild2GSPositionNotice")
	proto.RegisterType((*MsgGuild2GSOfficialNotice)(nil), "protomsg.MsgGuild2GSOfficialNotice")
	proto.RegisterType((*MsgGS2GuildSearchPlayerInfoNotice)(nil), "protomsg.MsgGS2GuildSearchPlayerInfoNotice")
	proto.RegisterType((*MsgGS2GuildRenameNotice)(nil), "protomsg.MsgGS2GuildRenameNotice")
	proto.RegisterType((*MsgGS2GuildBattlePowerNotice)(nil), "protomsg.MsgGS2GuildBattlePowerNotice")
	proto.RegisterType((*MsgGS2GuildKillCountNotice)(nil), "protomsg.MsgGS2GuildKillCountNotice")
	proto.RegisterType((*MsgGuild2GSUpdateGuildNameNotice)(nil), "protomsg.MsgGuild2GSUpdateGuildNameNotice")
	proto.RegisterType((*MsgGuild2GSUpdateGuildIconNotice)(nil), "protomsg.MsgGuild2GSUpdateGuildIconNotice")
	proto.RegisterType((*MsgGuild2GSBroadcastNotice)(nil), "protomsg.MsgGuild2GSBroadcastNotice")
	proto.RegisterType((*MsgGS2GuildPlayerLoginNotice)(nil), "protomsg.MsgGS2GuildPlayerLoginNotice")
	proto.RegisterType((*MsgGuild2GSExpAndLevelNotice)(nil), "protomsg.MsgGuild2GSExpAndLevelNotice")
	proto.RegisterType((*MsgGS2GuildPlayerLogoutNotice)(nil), "protomsg.MsgGS2GuildPlayerLogoutNotice")
	proto.RegisterType((*MsgGS2GuildPlayerLoadedNotice)(nil), "protomsg.MsgGS2GuildPlayerLoadedNotice")
	proto.RegisterType((*MsgGS2GuildPlayerReleaseNotice)(nil), "protomsg.MsgGS2GuildPlayerReleaseNotice")
	proto.RegisterType((*MsgGS2GuildDestroyNotice)(nil), "protomsg.MsgGS2GuildDestroyNotice")
	proto.RegisterType((*MsgGuild2GSApplyRecordNotice)(nil), "protomsg.MsgGuild2GSApplyRecordNotice")
	proto.RegisterType((*MsgGuild2GSUpdateGuildInfoRequest)(nil), "protomsg.MsgGuild2GSUpdateGuildInfoRequest")
	proto.RegisterType((*MsgGS2GuildUpdateGuildInfoReply)(nil), "protomsg.MsgGS2GuildUpdateGuildInfoReply")
	proto.RegisterType((*MsgGuild2GSGuildDisbandNotice)(nil), "protomsg.MsgGuild2GSGuildDisbandNotice")
	proto.RegisterType((*MsgGuild2GuildSearchSyncDataNotice)(nil), "protomsg.MsgGuild2GuildSearchSyncDataNotice")
	proto.RegisterType((*DeleteGuildInfo)(nil), "protomsg.DeleteGuildInfo")
	proto.RegisterType((*MsgGuild2GuildSearchDeleteGuildNotice)(nil), "protomsg.MsgGuild2GuildSearchDeleteGuildNotice")
	proto.RegisterType((*MsgGuild2GuildSearchLoadDataCompleteNotice)(nil), "protomsg.MsgGuild2GuildSearchLoadDataCompleteNotice")
	proto.RegisterType((*GuildAssistExecutor)(nil), "protomsg.GuildAssistExecutor")
	proto.RegisterType((*MsgGuild2GSGuildAssistExecuteHelpNotice)(nil), "protomsg.MsgGuild2GSGuildAssistExecuteHelpNotice")
	proto.RegisterType((*MsgGuild2GSGuildAssistUpdateNotice)(nil), "protomsg.MsgGuild2GSGuildAssistUpdateNotice")
	proto.RegisterType((*MsgGuild2GSGuildHostilityNotice)(nil), "protomsg.MsgGuild2GSGuildHostilityNotice")
	proto.RegisterType((*MsgGuild2MSGuildEventNotice)(nil), "protomsg.MsgGuild2MSGuildEventNotice")
	proto.RegisterType((*MsgMap2GuildAddGuildFacilityNotice)(nil), "protomsg.MsgMap2GuildAddGuildFacilityNotice")
	proto.RegisterType((*MsgMap2GuildRemoveGuildFacilityNotice)(nil), "protomsg.MsgMap2GuildRemoveGuildFacilityNotice")
	proto.RegisterType((*MsgGS2GuildPMUpdateResourceFieldCountNotice)(nil), "protomsg.MsgGS2GuildPMUpdateResourceFieldCountNotice")
	proto.RegisterType((*MsgGuild2OtherBuffEffectUpdateNotice)(nil), "protomsg.MsgGuild2OtherBuffEffectUpdateNotice")
	proto.RegisterType((*MsgGuild2OtherKingdomBuffEffectUpdateNotice)(nil), "protomsg.MsgGuild2OtherKingdomBuffEffectUpdateNotice")
	proto.RegisterType((*PlayerGuildExpInfo)(nil), "protomsg.PlayerGuildExpInfo")
	proto.RegisterType((*MsgGuild2GSUpdatePlayerGuildExpInfoRequest)(nil), "protomsg.MsgGuild2GSUpdatePlayerGuildExpInfoRequest")
	proto.RegisterType((*MsgGS2GuildUpdatePlayerGuildExpInfoReply)(nil), "protomsg.MsgGS2GuildUpdatePlayerGuildExpInfoReply")
}

func init() { proto.RegisterFile("msg_server_guild.proto", fileDescriptor60) }

var fileDescriptor60 = []byte{
	// 1317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x86, 0x1c, 0xd9, 0xb1, 0xc6, 0x71, 0x9c, 0xd0, 0x4e, 0x22, 0x3b, 0x27, 0x67, 0xf1, 0xff,
	0xad, 0x91, 0xa2, 0x4a, 0x21, 0x37, 0x37, 0x3d, 0x01, 0x56, 0xac, 0x24, 0x4a, 0xe2, 0x1c, 0xe8,
	0x14, 0x68, 0x7b, 0x51, 0x62, 0x45, 0x0e, 0xe5, 0xad, 0x49, 0x2e, 0x4b, 0xae, 0x5c, 0x09, 0xed,
	0x45, 0xd1, 0x67, 0xe8, 0x63, 0xf4, 0x01, 0xfa, 0x2a, 0x7d, 0x9b, 0x62, 0x0f, 0x14, 0x57, 0xb2,
	0xec, 0x30, 0x45, 0x2f, 0x7a, 0x45, 0xee, 0xec, 0xcc, 0xf7, 0xcd, 0xcc, 0xce, 0xce, 0x2c, 0x5c,
	0x8f, 0xf3, 0x81, 0x97, 0x63, 0x76, 0x82, 0x99, 0x37, 0x18, 0xb2, 0x28, 0x68, 0xa5, 0x19, 0x17,
	0xdc, 0x59, 0x56, 0x9f, 0x38, 0x1f, 0x6c, 0x6d, 0x0e, 0x38, 0x1f, 0x44, 0xf8, 0x40, 0x09, 0xfa,
	0xc3, 0xf0, 0x01, 0x4d, 0xc6, 0x5a, 0x69, 0xeb, 0x8a, 0x34, 0xf6, 0x79, 0x1c, 0xf3, 0xc4, 0x48,
	0xae, 0x97, 0x12, 0x1b, 0x6e, 0x6b, 0xc3, 0x92, 0xc7, 0x34, 0xd5, 0x52, 0xe2, 0xc3, 0xb5, 0x83,
	0x7c, 0xf0, 0x44, 0xea, 0xb5, 0x9f, 0x1c, 0x3e, 0xe3, 0x2c, 0x79, 0xc9, 0x05, 0xf3, 0xd1, 0xb9,
	0x09, 0x8d, 0x34, 0xa2, 0x63, 0xcc, 0x3c, 0x16, 0x34, 0x6b, 0xdb, 0xb5, 0x9d, 0xba, 0xbb, 0xac,
	0x05, 0xbd, 0xc0, 0xf9, 0x18, 0xea, 0x2c, 0x09, 0x79, 0x73, 0x61, 0xbb, 0xb6, 0xb3, 0xd2, 0xde,
	0x6c, 0x15, 0x9e, 0xb6, 0x5e, 0x2b, 0x0d, 0x05, 0xd7, 0x4b, 0x42, 0xee, 0x2a, 0x35, 0xf2, 0x6a,
	0x8a, 0xe4, 0xcd, 0x90, 0x89, 0x2a, 0x24, 0x9b, 0xb0, 0xac, 0xfc, 0x97, 0x7b, 0x0b, 0x6a, 0xef,
	0xa2, 0x5a, 0xf7, 0x02, 0xb2, 0x07, 0x44, 0x02, 0x1e, 0xb6, 0x15, 0xa6, 0x8b, 0x31, 0x3f, 0xc1,
	0xbd, 0x34, 0x8d, 0xc6, 0x2e, 0xfa, 0x3c, 0x0b, 0x2a, 0xa0, 0x93, 0x18, 0x36, 0x2d, 0x9f, 0x5e,
	0xf3, 0x9c, 0x09, 0xc6, 0x2b, 0x05, 0xbf, 0x0b, 0xcb, 0xa9, 0x51, 0x57, 0x7e, 0x5d, 0x6e, 0xdf,
	0x28, 0x13, 0xa0, 0x00, 0x0b, 0x34, 0x77, 0xa2, 0x38, 0x43, 0xf7, 0x2a, 0x0c, 0x99, 0xcf, 0x68,
	0x54, 0x91, 0x8e, 0x1b, 0xf5, 0x33, 0xe8, 0x0a, 0x34, 0x77, 0xa2, 0x48, 0x52, 0xb8, 0x67, 0x25,
	0xe8, 0x10, 0x69, 0xe6, 0x1f, 0xe9, 0xb3, 0x91, 0xc7, 0x52, 0x85, 0xb6, 0x05, 0xf5, 0x80, 0x0a,
	0x6a, 0x8e, 0x78, 0xab, 0xa4, 0x9c, 0x05, 0x73, 0x95, 0x1e, 0x79, 0x06, 0x37, 0xa6, 0x8e, 0x24,
	0xa1, 0x31, 0x56, 0xe1, 0x71, 0xa0, 0x2e, 0x55, 0x9b, 0x17, 0xb6, 0x6b, 0x3b, 0x0d, 0x57, 0xfd,
	0x93, 0xef, 0xe1, 0x96, 0x85, 0xd5, 0xa1, 0x42, 0x44, 0xf8, 0x9a, 0xff, 0x84, 0x59, 0x15, 0xc0,
	0x7b, 0x70, 0xa9, 0xaf, 0x2c, 0xbc, 0x54, 0x9a, 0x28, 0xe0, 0xba, 0xbb, 0xd2, 0x2f, 0x51, 0xc8,
	0x37, 0xb0, 0x65, 0xe1, 0x3f, 0x67, 0x51, 0xf4, 0x88, 0x0f, 0x93, 0x4a, 0x45, 0x79, 0x1b, 0xe0,
	0x98, 0x45, 0x91, 0xe7, 0x4b, 0x03, 0x53, 0x96, 0x8d, 0xe3, 0x02, 0x81, 0x64, 0xb0, 0x6d, 0x1d,
	0xf3, 0xd7, 0x69, 0x40, 0x05, 0xaa, 0xd5, 0xcb, 0xf7, 0x4c, 0xc7, 0x42, 0x99, 0x0e, 0xc9, 0x99,
	0x1f, 0xf1, 0x4c, 0x78, 0x56, 0xa2, 0x1a, 0x4a, 0x22, 0x51, 0xc9, 0xe1, 0x59, 0x9c, 0x3d, 0xbf,
	0x5a, 0x41, 0x3b, 0x50, 0x67, 0xbe, 0x29, 0xe6, 0x55, 0x57, 0xfd, 0x93, 0x5f, 0x6b, 0x3a, 0x47,
	0x06, 0xb5, 0x93, 0x71, 0x1a, 0xf8, 0x34, 0xaf, 0x94, 0xa3, 0x6b, 0xb0, 0x24, 0x7b, 0x8d, 0xb9,
	0xb6, 0xab, 0xee, 0x62, 0x9c, 0x0f, 0x54, 0x45, 0x5d, 0xf4, 0x79, 0x22, 0x30, 0x11, 0x2a, 0x86,
	0x95, 0xf6, 0x46, 0x4b, 0xf7, 0xb5, 0x56, 0xd1, 0xd7, 0x5a, 0x7b, 0xc9, 0xd8, 0x2d, 0x94, 0xc8,
	0xf1, 0x54, 0x15, 0xe8, 0x82, 0x7b, 0xc1, 0x07, 0xd5, 0x3a, 0xd4, 0xfb, 0x96, 0x2f, 0xd5, 0x64,
	0x26, 0xdc, 0xee, 0x28, 0xdd, 0x4b, 0x82, 0x17, 0x78, 0x82, 0xc5, 0x15, 0xb5, 0x9b, 0x51, 0x6d,
	0xaa, 0x19, 0x39, 0x57, 0xe0, 0x02, 0x8e, 0x52, 0x13, 0xab, 0xfc, 0x75, 0x36, 0x60, 0x31, 0x92,
	0xb6, 0x2a, 0xce, 0x55, 0x57, 0x2f, 0xc8, 0x17, 0x70, 0x7b, 0x5e, 0x3c, 0x7c, 0x58, 0x25, 0xa9,
	0x67, 0x58, 0xd3, 0x00, 0x2b, 0x75, 0xbb, 0x2f, 0xe1, 0xce, 0x29, 0x6b, 0x17, 0x23, 0xa4, 0x79,
	0x95, 0xaa, 0x24, 0x0f, 0xa1, 0x69, 0x99, 0xef, 0x63, 0x2e, 0x32, 0x3e, 0x7e, 0x67, 0x66, 0xc8,
	0x6f, 0xb5, 0xa9, 0xac, 0xbe, 0x5f, 0x87, 0x76, 0xba, 0x70, 0x85, 0x4a, 0x0b, 0x96, 0x0c, 0xbc,
	0x4c, 0x59, 0xe5, 0xcd, 0x85, 0xed, 0x0b, 0xd3, 0xc7, 0xa9, 0xb0, 0x2d, 0x60, 0x77, 0xad, 0xb0,
	0xd1, 0xeb, 0x9c, 0x70, 0xdd, 0x0a, 0xe7, 0x5c, 0x0f, 0x79, 0xfa, 0xf8, 0xe3, 0x10, 0x73, 0xf1,
	0xaf, 0x4e, 0xbb, 0x7b, 0x70, 0xd7, 0x4a, 0xd6, 0x29, 0xc2, 0x34, 0x1a, 0x93, 0xcf, 0xf4, 0x61,
	0x1a, 0x9f, 0x74, 0x52, 0x59, 0xde, 0xa7, 0x49, 0xf0, 0xee, 0xa4, 0xbe, 0xd5, 0xb3, 0x4f, 0xdb,
	0x96, 0xdd, 0xfd, 0x70, 0x9c, 0xf8, 0xfb, 0x54, 0x50, 0x03, 0xd0, 0x82, 0x45, 0x59, 0xd7, 0x79,
	0xb3, 0xa6, 0x32, 0xd6, 0x9c, 0xc9, 0x58, 0x27, 0x63, 0x18, 0x4a, 0x75, 0x57, 0xab, 0x11, 0x0f,
	0xd6, 0xf6, 0x31, 0x42, 0xcb, 0xd3, 0xf3, 0x4a, 0xfe, 0x1f, 0x74, 0xa9, 0x01, 0xfc, 0x7f, 0x9e,
	0xdb, 0x16, 0xa9, 0xf1, 0xfc, 0x2b, 0x58, 0x0d, 0x94, 0x50, 0xbf, 0x5e, 0x8a, 0x08, 0xac, 0xb4,
	0xcf, 0x38, 0xea, 0x5e, 0x0a, 0x4a, 0x41, 0x4e, 0x3a, 0x70, 0x7f, 0x1e, 0x91, 0xbc, 0x2b, 0x32,
	0xe0, 0x47, 0x3c, 0x4e, 0xa5, 0xb6, 0x61, 0xdb, 0x80, 0x45, 0xdd, 0xca, 0x6b, 0xfa, 0xaa, 0xaa,
	0x05, 0xf9, 0x0e, 0xd6, 0x75, 0x61, 0xe5, 0x39, 0xcb, 0x45, 0x77, 0x84, 0xfe, 0x50, 0xf0, 0x4c,
	0x15, 0x82, 0xc0, 0x58, 0xe9, 0x4e, 0x79, 0x64, 0x29, 0xf7, 0x04, 0xc6, 0xae, 0x52, 0x2b, 0xb1,
	0x17, 0x6c, 0xec, 0x5f, 0xe0, 0xc3, 0xd9, 0xb3, 0xb7, 0x69, 0xf0, 0x29, 0x46, 0xa9, 0x71, 0xee,
	0x73, 0x68, 0xa0, 0xe1, 0x2e, 0xd2, 0x70, 0x7b, 0x2e, 0x69, 0xe1, 0xa1, 0x5b, 0xea, 0xab, 0x26,
	0xc4, 0x07, 0xa6, 0xad, 0x2f, 0xbb, 0x7a, 0x41, 0xbe, 0xb5, 0xab, 0xc7, 0x66, 0xd7, 0x75, 0x6a,
	0x88, 0x77, 0x61, 0x29, 0x40, 0x41, 0x59, 0x64, 0x42, 0xbd, 0x39, 0x97, 0x75, 0x5f, 0xa9, 0xb8,
	0x46, 0x95, 0xbc, 0xd1, 0x75, 0x6f, 0x43, 0x3f, 0xe5, 0xb9, 0x60, 0x11, 0x13, 0xe3, 0x49, 0x55,
	0xae, 0x1f, 0x15, 0x22, 0xaf, 0x28, 0x2e, 0x1d, 0x5a, 0xdd, 0xbd, 0x3a, 0xd9, 0xd2, 0x47, 0x1b,
	0xe4, 0x24, 0x82, 0x9b, 0x13, 0xc8, 0x03, 0x0d, 0xd9, 0x3d, 0xc1, 0xc9, 0xa4, 0x3e, 0xa7, 0x42,
	0xdb, 0x00, 0x28, 0x35, 0x3d, 0x6b, 0x0a, 0xac, 0x97, 0x51, 0x28, 0x14, 0x55, 0xff, 0x0d, 0x2c,
	0x7e, 0xc9, 0x5f, 0x35, 0x95, 0x9c, 0x03, 0x9a, 0xea, 0xc2, 0xd9, 0x0b, 0x02, 0xf5, 0x7d, 0x4c,
	0x7d, 0x3b, 0x88, 0x73, 0x58, 0x1f, 0xc2, 0x0a, 0x26, 0x42, 0x06, 0x27, 0xc6, 0x29, 0x9a, 0xe7,
	0xda, 0x86, 0x45, 0xab, 0x36, 0xdf, 0x8e, 0x53, 0x74, 0x01, 0x27, 0xff, 0xb2, 0xfb, 0x18, 0x33,
	0x16, 0x98, 0xf7, 0xca, 0xb2, 0x16, 0xf4, 0x02, 0x79, 0x8e, 0x29, 0xcd, 0x68, 0xdc, 0xac, 0xab,
	0x0d, 0xbd, 0x70, 0xae, 0xc3, 0x92, 0xfa, 0x69, 0x37, 0x17, 0x95, 0xd8, 0xac, 0x26, 0xf2, 0xdd,
	0xe6, 0x92, 0x2a, 0x3a, 0xb3, 0x22, 0x7f, 0xd4, 0xd4, 0xfd, 0x9b, 0xc4, 0xa6, 0xdf, 0xcc, 0xff,
	0xd5, 0xf0, 0xc8, 0xef, 0x35, 0xf8, 0xc8, 0x1e, 0x58, 0x07, 0xba, 0x3c, 0x5d, 0xcc, 0xf9, 0x30,
	0xf3, 0xf1, 0x31, 0xc3, 0x28, 0xb0, 0xdf, 0x6c, 0xe7, 0x38, 0xfd, 0x29, 0xd4, 0x2d, 0x6f, 0xb7,
	0x67, 0x2a, 0x79, 0x0a, 0x51, 0x79, 0xae, 0xb4, 0xcb, 0xbb, 0x2b, 0xfd, 0x5d, 0x2c, 0xee, 0xee,
	0x0f, 0xf0, 0xbf, 0x49, 0x3d, 0xbe, 0x12, 0x47, 0x98, 0x75, 0x86, 0x61, 0xd8, 0x0d, 0x43, 0xf4,
	0xa7, 0xef, 0x4f, 0x07, 0x56, 0xb5, 0x3b, 0xa8, 0xf6, 0x72, 0x73, 0x8d, 0x66, 0x2f, 0x6f, 0x69,
	0xad, 0xfb, 0x98, 0xb2, 0xd1, 0x82, 0x9c, 0xfc, 0x69, 0x52, 0x50, 0x92, 0x3d, 0x67, 0xc9, 0x20,
	0xe0, 0xf1, 0x19, 0x9c, 0x4f, 0x61, 0xed, 0x58, 0x2b, 0xcc, 0xb0, 0xde, 0x2d, 0x59, 0x4f, 0x21,
	0x28, 0xde, 0xcb, 0xc6, 0xce, 0x30, 0x3b, 0x77, 0x60, 0xc5, 0x1f, 0x66, 0x5e, 0x7f, 0x18, 0x86,
	0xe5, 0x23, 0xae, 0xe1, 0x0f, 0x55, 0xb4, 0xbd, 0xc0, 0xb9, 0x0b, 0x2b, 0x38, 0x4a, 0x59, 0x86,
	0x9e, 0x60, 0xa6, 0xd5, 0xd7, 0x5d, 0xd0, 0xa2, 0xb7, 0x2c, 0x46, 0x12, 0x81, 0x63, 0x8d, 0xc6,
	0xee, 0x28, 0x55, 0xf3, 0xa4, 0x05, 0xeb, 0x38, 0x4a, 0xbd, 0x30, 0xe3, 0xb1, 0xd7, 0xa7, 0x59,
	0x9f, 0x66, 0x8c, 0x26, 0xb9, 0x39, 0xae, 0xab, 0x38, 0x4a, 0x1f, 0x67, 0x3c, 0xee, 0x4c, 0x36,
	0x9c, 0x0f, 0x60, 0x6d, 0xa2, 0x1f, 0xf0, 0x84, 0x0a, 0x34, 0xef, 0xed, 0x55, 0xa3, 0xbb, 0xaf,
	0x84, 0xe4, 0x67, 0xbb, 0xe1, 0x9b, 0x01, 0x7f, 0x9a, 0xbe, 0xd2, 0xa4, 0xff, 0x64, 0x6a, 0xd2,
	0xdf, 0x9a, 0x3b, 0xe9, 0x0b, 0x3c, 0x3d, 0xec, 0xef, 0xc3, 0xce, 0xa9, 0x61, 0x3f, 0x8f, 0x3c,
	0x8d, 0xc6, 0xfd, 0x25, 0x05, 0xb7, 0xfb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x82, 0x02,
	0x4a, 0xf1, 0x0f, 0x00, 0x00,
}
