// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_common_shop.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ShopType int32

const (
	ShopType_kShopType_Normal         ShopType = 0
	ShopType_kShopType_Refresh        ShopType = 1
	ShopType_kShopType_Mystery        ShopType = 2
	ShopType_kShopType_HeroToken      ShopType = 3
	ShopType_kShopType_GuildShop      ShopType = 4
	ShopType_kShopType_SpecialMystery ShopType = 5
)

var ShopType_name = map[int32]string{
	0: "kShopType_Normal",
	1: "kShopType_Refresh",
	2: "kShopType_Mystery",
	3: "kShopType_HeroToken",
	4: "kShopType_GuildShop",
	5: "kShopType_SpecialMystery",
}
var ShopType_value = map[string]int32{
	"kShopType_Normal":         0,
	"kShopType_Refresh":        1,
	"kShopType_Mystery":        2,
	"kShopType_HeroToken":      3,
	"kShopType_GuildShop":      4,
	"kShopType_SpecialMystery": 5,
}

func (x ShopType) String() string {
	return proto.EnumName(ShopType_name, int32(x))
}
func (ShopType) EnumDescriptor() ([]byte, []int) { return fileDescriptor56, []int{0} }

type DayShopRefreshType int32

const (
	DayShopRefreshType_kDayShopRefreshType_Day   DayShopRefreshType = 0
	DayShopRefreshType_kDayShopRefreshType_Week  DayShopRefreshType = 1
	DayShopRefreshType_kDayShopRefreshType_Month DayShopRefreshType = 2
	DayShopRefreshType_kDayShopRefreshType_Not   DayShopRefreshType = 3
)

var DayShopRefreshType_name = map[int32]string{
	0: "kDayShopRefreshType_Day",
	1: "kDayShopRefreshType_Week",
	2: "kDayShopRefreshType_Month",
	3: "kDayShopRefreshType_Not",
}
var DayShopRefreshType_value = map[string]int32{
	"kDayShopRefreshType_Day":   0,
	"kDayShopRefreshType_Week":  1,
	"kDayShopRefreshType_Month": 2,
	"kDayShopRefreshType_Not":   3,
}

func (x DayShopRefreshType) String() string {
	return proto.EnumName(DayShopRefreshType_name, int32(x))
}
func (DayShopRefreshType) EnumDescriptor() ([]byte, []int) { return fileDescriptor56, []int{1} }

type ShopBuyLimitType int32

const (
	ShopBuyLimitType_ShopBuyLimitType_None       ShopBuyLimitType = 0
	ShopBuyLimitType_ShopBuyLimitType_Castle     ShopBuyLimitType = 1
	ShopBuyLimitType_ShopBuyLimitType_Vip        ShopBuyLimitType = 2
	ShopBuyLimitType_ShopBuyLimitType_GuildLevel ShopBuyLimitType = 3
)

var ShopBuyLimitType_name = map[int32]string{
	0: "ShopBuyLimitType_None",
	1: "ShopBuyLimitType_Castle",
	2: "ShopBuyLimitType_Vip",
	3: "ShopBuyLimitType_GuildLevel",
}
var ShopBuyLimitType_value = map[string]int32{
	"ShopBuyLimitType_None":       0,
	"ShopBuyLimitType_Castle":     1,
	"ShopBuyLimitType_Vip":        2,
	"ShopBuyLimitType_GuildLevel": 3,
}

func (x ShopBuyLimitType) String() string {
	return proto.EnumName(ShopBuyLimitType_name, int32(x))
}
func (ShopBuyLimitType) EnumDescriptor() ([]byte, []int) { return fileDescriptor56, []int{2} }

type MysteryShopManTriggerType int32

const (
	MysteryShopManTriggerType_kMysteryShopManTriggerType_None             MysteryShopManTriggerType = 0
	MysteryShopManTriggerType_kMysteryShopManTriggerType_BuildSoldiersCnt MysteryShopManTriggerType = 1
	MysteryShopManTriggerType_kMysteryShopManTriggerType_BuildLelvel      MysteryShopManTriggerType = 2
)

var MysteryShopManTriggerType_name = map[int32]string{
	0: "kMysteryShopManTriggerType_None",
	1: "kMysteryShopManTriggerType_BuildSoldiersCnt",
	2: "kMysteryShopManTriggerType_BuildLelvel",
}
var MysteryShopManTriggerType_value = map[string]int32{
	"kMysteryShopManTriggerType_None":             0,
	"kMysteryShopManTriggerType_BuildSoldiersCnt": 1,
	"kMysteryShopManTriggerType_BuildLelvel":      2,
}

func (x MysteryShopManTriggerType) String() string {
	return proto.EnumName(MysteryShopManTriggerType_name, int32(x))
}
func (MysteryShopManTriggerType) EnumDescriptor() ([]byte, []int) { return fileDescriptor56, []int{3} }

type MysteryShopMansStatus int32

const (
	MysteryShopMansStatus_MysteryShopMansStatus_None     MysteryShopMansStatus = 0
	MysteryShopMansStatus_MysteryShopMansStatus_Execute  MysteryShopMansStatus = 1
	MysteryShopMansStatus_MysteryShopMansStatus_Complete MysteryShopMansStatus = 2
)

var MysteryShopMansStatus_name = map[int32]string{
	0: "MysteryShopMansStatus_None",
	1: "MysteryShopMansStatus_Execute",
	2: "MysteryShopMansStatus_Complete",
}
var MysteryShopMansStatus_value = map[string]int32{
	"MysteryShopMansStatus_None":     0,
	"MysteryShopMansStatus_Execute":  1,
	"MysteryShopMansStatus_Complete": 2,
}

func (x MysteryShopMansStatus) String() string {
	return proto.EnumName(MysteryShopMansStatus_name, int32(x))
}
func (MysteryShopMansStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor56, []int{4} }

// 商店物品基本数据
type ShopBaseItemData struct {
	Id       uint32    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	BuyCount uint32    `protobuf:"varint,3,opt,name=buy_count,json=buyCount" json:"buy_count,omitempty"`
	Res      *Resource `protobuf:"bytes,4,opt,name=res" json:"res,omitempty"`
}

func (m *ShopBaseItemData) Reset()                    { *m = ShopBaseItemData{} }
func (m *ShopBaseItemData) String() string            { return proto.CompactTextString(m) }
func (*ShopBaseItemData) ProtoMessage()               {}
func (*ShopBaseItemData) Descriptor() ([]byte, []int) { return fileDescriptor56, []int{0} }

func (m *ShopBaseItemData) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopBaseItemData) GetBuyCount() uint32 {
	if m != nil {
		return m.BuyCount
	}
	return 0
}

func (m *ShopBaseItemData) GetRes() *Resource {
	if m != nil {
		return m.Res
	}
	return nil
}

// 普通商店数据
type ShopData struct {
	ShopId              uint32              `protobuf:"varint,1,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Items               []*ShopBaseItemData `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	RefreshCount        uint32              `protobuf:"varint,3,opt,name=refresh_count,json=refreshCount" json:"refresh_count,omitempty"`
	RefreshTime         int64               `protobuf:"varint,4,opt,name=refresh_time,json=refreshTime" json:"refresh_time,omitempty"`
	ExpireTime          int64               `protobuf:"varint,5,opt,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	RateValue           uint32              `protobuf:"varint,6,opt,name=rate_value,json=rateValue" json:"rate_value,omitempty"`
	DayRefreshCount     uint32              `protobuf:"varint,8,opt,name=day_refresh_count,json=dayRefreshCount" json:"day_refresh_count,omitempty"`
	VipFreeRefreshCount uint32              `protobuf:"varint,9,opt,name=vip_free_refresh_count,json=vipFreeRefreshCount" json:"vip_free_refresh_count,omitempty"`
	ShopManId           uint32              `protobuf:"varint,10,opt,name=shop_man_id,json=shopManId" json:"shop_man_id,omitempty"`
}

func (m *ShopData) Reset()                    { *m = ShopData{} }
func (m *ShopData) String() string            { return proto.CompactTextString(m) }
func (*ShopData) ProtoMessage()               {}
func (*ShopData) Descriptor() ([]byte, []int) { return fileDescriptor56, []int{1} }

func (m *ShopData) GetShopId() uint32 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ShopData) GetItems() []*ShopBaseItemData {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ShopData) GetRefreshCount() uint32 {
	if m != nil {
		return m.RefreshCount
	}
	return 0
}

func (m *ShopData) GetRefreshTime() int64 {
	if m != nil {
		return m.RefreshTime
	}
	return 0
}

func (m *ShopData) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *ShopData) GetRateValue() uint32 {
	if m != nil {
		return m.RateValue
	}
	return 0
}

func (m *ShopData) GetDayRefreshCount() uint32 {
	if m != nil {
		return m.DayRefreshCount
	}
	return 0
}

func (m *ShopData) GetVipFreeRefreshCount() uint32 {
	if m != nil {
		return m.VipFreeRefreshCount
	}
	return 0
}

func (m *ShopData) GetShopManId() uint32 {
	if m != nil {
		return m.ShopManId
	}
	return 0
}

type MysteryShopManData struct {
	ShopManId         uint32 `protobuf:"varint,1,opt,name=shop_man_id,json=shopManId" json:"shop_man_id,omitempty"`
	AppearTime        int64  `protobuf:"varint,2,opt,name=appear_time,json=appearTime" json:"appear_time,omitempty"`
	DisappearTime     int64  `protobuf:"varint,3,opt,name=disappear_time,json=disappearTime" json:"disappear_time,omitempty"`
	IsPlayerAnimation uint32 `protobuf:"varint,4,opt,name=is_player_animation,json=isPlayerAnimation" json:"is_player_animation,omitempty"`
	Status            uint32 `protobuf:"varint,5,opt,name=status" json:"status,omitempty"`
}

func (m *MysteryShopManData) Reset()                    { *m = MysteryShopManData{} }
func (m *MysteryShopManData) String() string            { return proto.CompactTextString(m) }
func (*MysteryShopManData) ProtoMessage()               {}
func (*MysteryShopManData) Descriptor() ([]byte, []int) { return fileDescriptor56, []int{2} }

func (m *MysteryShopManData) GetShopManId() uint32 {
	if m != nil {
		return m.ShopManId
	}
	return 0
}

func (m *MysteryShopManData) GetAppearTime() int64 {
	if m != nil {
		return m.AppearTime
	}
	return 0
}

func (m *MysteryShopManData) GetDisappearTime() int64 {
	if m != nil {
		return m.DisappearTime
	}
	return 0
}

func (m *MysteryShopManData) GetIsPlayerAnimation() uint32 {
	if m != nil {
		return m.IsPlayerAnimation
	}
	return 0
}

func (m *MysteryShopManData) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*ShopBaseItemData)(nil), "protomsg.ShopBaseItemData")
	proto.RegisterType((*ShopData)(nil), "protomsg.ShopData")
	proto.RegisterType((*MysteryShopManData)(nil), "protomsg.MysteryShopManData")
	proto.RegisterEnum("protomsg.ShopType", ShopType_name, ShopType_value)
	proto.RegisterEnum("protomsg.DayShopRefreshType", DayShopRefreshType_name, DayShopRefreshType_value)
	proto.RegisterEnum("protomsg.ShopBuyLimitType", ShopBuyLimitType_name, ShopBuyLimitType_value)
	proto.RegisterEnum("protomsg.MysteryShopManTriggerType", MysteryShopManTriggerType_name, MysteryShopManTriggerType_value)
	proto.RegisterEnum("protomsg.MysteryShopMansStatus", MysteryShopMansStatus_name, MysteryShopMansStatus_value)
}

func init() { proto.RegisterFile("msg_common_shop.proto", fileDescriptor56) }

var fileDescriptor56 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdb, 0x4e, 0x1b, 0x49,
	0x10, 0x65, 0x66, 0xc0, 0x6b, 0xca, 0x6b, 0xb6, 0x69, 0x30, 0x18, 0x58, 0x6e, 0x66, 0x77, 0x85,
	0xbc, 0x92, 0x77, 0x05, 0x5f, 0x10, 0x4c, 0x2e, 0x48, 0x80, 0x22, 0xdb, 0x22, 0x8f, 0xa3, 0xc6,
	0x53, 0xd8, 0x2d, 0xcf, 0x4c, 0x8f, 0xba, 0x7b, 0x2c, 0xe6, 0x25, 0x6f, 0x79, 0xca, 0x37, 0x24,
	0x5f, 0x93, 0xef, 0xc8, 0xb7, 0x44, 0xdd, 0x63, 0x63, 0x7c, 0x21, 0x79, 0xb2, 0xea, 0x9c, 0x53,
	0x55, 0xa7, 0x8f, 0xcb, 0x86, 0x4a, 0xa4, 0x7a, 0x7e, 0x57, 0x44, 0x91, 0x88, 0x7d, 0xd5, 0x17,
	0x49, 0x23, 0x91, 0x42, 0x0b, 0x5a, 0xb4, 0x1f, 0x91, 0xea, 0xed, 0x92, 0x89, 0x20, 0xe7, 0x6a,
	0x08, 0xa4, 0xdd, 0x17, 0xc9, 0x05, 0x53, 0x78, 0xa5, 0x31, 0xba, 0x64, 0x9a, 0xd1, 0x35, 0x70,
	0x79, 0x50, 0x75, 0x8e, 0x9c, 0xd3, 0x72, 0xcb, 0xe5, 0x01, 0xdd, 0x83, 0xd5, 0xfb, 0x34, 0xf3,
	0xbb, 0x22, 0x8d, 0x75, 0xd5, 0xb3, 0x70, 0xf1, 0x3e, 0xcd, 0x9a, 0xa6, 0xa6, 0x7f, 0x81, 0x27,
	0x51, 0x55, 0x97, 0x8f, 0x9c, 0xd3, 0xd2, 0x19, 0x6d, 0x8c, 0x57, 0x35, 0x5a, 0xa8, 0x44, 0x2a,
	0xbb, 0xd8, 0x32, 0x74, 0xed, 0xbb, 0x0b, 0x45, 0xb3, 0xc7, 0xce, 0xdf, 0x86, 0xdf, 0x8c, 0x3b,
	0xff, 0x69, 0x49, 0xc1, 0x94, 0x57, 0x01, 0xfd, 0x1f, 0x56, 0xb8, 0xc6, 0x48, 0x55, 0xdd, 0x23,
	0xef, 0xb4, 0x74, 0xb6, 0x3b, 0x99, 0x36, 0xeb, 0xb1, 0x95, 0x0b, 0xe9, 0x09, 0x94, 0x25, 0x3e,
	0x48, 0x54, 0xfd, 0x29, 0x7b, 0xbf, 0x8f, 0xc0, 0xdc, 0xe2, 0x31, 0x8c, 0x6b, 0x5f, 0xf3, 0x08,
	0xad, 0x57, 0xaf, 0x55, 0x1a, 0x61, 0x1d, 0x1e, 0x21, 0x3d, 0x84, 0x12, 0x3e, 0x26, 0x5c, 0x62,
	0xae, 0x58, 0xb1, 0x0a, 0xc8, 0x21, 0x2b, 0xd8, 0x07, 0x90, 0x4c, 0xa3, 0x3f, 0x64, 0x61, 0x8a,
	0xd5, 0x82, 0xdd, 0xb2, 0x6a, 0x90, 0x3b, 0x03, 0xd0, 0x3a, 0xac, 0x07, 0x2c, 0xf3, 0xa7, 0xbd,
	0x14, 0xad, 0xea, 0x8f, 0x80, 0x65, 0xad, 0xe7, 0x76, 0xce, 0x61, 0x6b, 0xc8, 0x13, 0xff, 0x41,
	0x22, 0xce, 0x34, 0xac, 0xda, 0x86, 0x8d, 0x21, 0x4f, 0xde, 0x48, 0xc4, 0xa9, 0xa6, 0x03, 0x28,
	0xd9, 0xcc, 0x22, 0x16, 0x9b, 0xdc, 0x20, 0x37, 0x60, 0xa0, 0x1b, 0x16, 0x5f, 0x05, 0xb5, 0x6f,
	0x0e, 0xd0, 0x9b, 0x4c, 0x69, 0x94, 0x59, 0x3b, 0x07, 0x6d, 0xd4, 0x33, 0x6d, 0xce, 0x4c, 0x9b,
	0x79, 0x37, 0x4b, 0x12, 0x64, 0x32, 0x7f, 0xb7, 0x9b, 0xbf, 0x3b, 0x87, 0xec, 0xbb, 0xff, 0x86,
	0xb5, 0x80, 0xab, 0xe7, 0x1a, 0xcf, 0x6a, 0xca, 0x4f, 0xa8, 0x95, 0x35, 0x60, 0x83, 0x2b, 0x3f,
	0x09, 0x59, 0x86, 0xd2, 0x67, 0x31, 0x8f, 0x98, 0xe6, 0x22, 0xb6, 0x49, 0x97, 0x5b, 0xeb, 0x5c,
	0xbd, 0xb7, 0xcc, 0xab, 0x31, 0x41, 0xb7, 0xa0, 0xa0, 0x34, 0xd3, 0xa9, 0xb2, 0x51, 0x9b, 0x0b,
	0xb0, 0x55, 0xfd, 0xab, 0x93, 0xdf, 0x49, 0x27, 0x4b, 0x90, 0x6e, 0x02, 0x19, 0x8c, 0x0b, 0xff,
	0x56, 0xc8, 0x88, 0x85, 0x64, 0x89, 0x56, 0x60, 0x7d, 0x82, 0x8e, 0x32, 0x22, 0xce, 0x34, 0x3c,
	0x4a, 0x82, 0xb8, 0x74, 0x1b, 0x36, 0x26, 0xf0, 0x3b, 0x94, 0xa2, 0x23, 0x06, 0x18, 0x13, 0x6f,
	0x9a, 0x78, 0x9b, 0xf2, 0x30, 0x30, 0x15, 0x59, 0xa6, 0x7f, 0x42, 0x75, 0x42, 0xb4, 0x13, 0xec,
	0x72, 0x16, 0x8e, 0xe7, 0xad, 0xd4, 0x3f, 0x3b, 0x40, 0x2f, 0x99, 0xcd, 0x78, 0xb4, 0xdb, 0x5a,
	0xdd, 0x83, 0xed, 0xc1, 0x3c, 0xec, 0x5f, 0xb2, 0x8c, 0x2c, 0xd9, 0x89, 0x0b, 0xc8, 0x0f, 0x88,
	0x03, 0xe2, 0xd0, 0x7d, 0xd8, 0x59, 0xc4, 0xde, 0x88, 0x58, 0xf7, 0x89, 0xfb, 0xd2, 0xe4, 0x5b,
	0xa1, 0x89, 0x57, 0xff, 0xe4, 0x8c, 0x7e, 0xbe, 0x69, 0x76, 0xcd, 0x23, 0xae, 0xad, 0x97, 0x1d,
	0xa8, 0xcc, 0x62, 0xfe, 0xad, 0x88, 0x91, 0x2c, 0x99, 0x61, 0x73, 0x54, 0x93, 0x29, 0x1d, 0x22,
	0x71, 0x68, 0x15, 0x36, 0xe7, 0xc8, 0x3b, 0x9e, 0x10, 0x97, 0x1e, 0xc2, 0xde, 0x1c, 0x63, 0x23,
	0xbb, 0xc6, 0x21, 0x86, 0xc4, 0xab, 0x7f, 0x71, 0x60, 0x67, 0xfa, 0xfa, 0x3a, 0x92, 0xf7, 0x7a,
	0x28, 0xad, 0xa1, 0x13, 0x38, 0x1c, 0xbc, 0xc8, 0x8e, 0xad, 0xfd, 0x07, 0xff, 0xfe, 0x44, 0x74,
	0x61, 0xbf, 0x20, 0x11, 0x06, 0x1c, 0xa5, 0x6a, 0xc6, 0x9a, 0x38, 0xb4, 0x0e, 0xff, 0xfc, 0xaa,
	0xe1, 0x1a, 0x43, 0xe3, 0xcf, 0xad, 0x7f, 0x84, 0xca, 0xb4, 0x54, 0xb5, 0xed, 0xbd, 0xd1, 0x03,
	0xd8, 0x5d, 0x48, 0x8c, 0x5d, 0x1d, 0xc3, 0xfe, 0x62, 0xfe, 0xf5, 0x23, 0x76, 0x53, 0x6d, 0x62,
	0xab, 0xc1, 0xc1, 0x62, 0x49, 0x53, 0x44, 0x49, 0x88, 0x1a, 0x89, 0x7b, 0x5f, 0xb0, 0x7f, 0x64,
	0xe7, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x11, 0x93, 0xf0, 0xa1, 0x05, 0x00, 0x00,
}
