// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_common_magic_lamp.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type MagicLampLevel int32

const (
	MagicLampLevel_kMagicLampLevel_None   MagicLampLevel = 0
	MagicLampLevel_kMagicLampLevel_Level1 MagicLampLevel = 1
	MagicLampLevel_kMagicLampLevel_Level2 MagicLampLevel = 2
	MagicLampLevel_kMagicLampLevel_Level3 MagicLampLevel = 3
	MagicLampLevel_kMagicLampLevel_Level4 MagicLampLevel = 4
)

var MagicLampLevel_name = map[int32]string{
	0: "kMagicLampLevel_None",
	1: "kMagicLampLevel_Level1",
	2: "kMagicLampLevel_Level2",
	3: "kMagicLampLevel_Level3",
	4: "kMagicLampLevel_Level4",
}
var MagicLampLevel_value = map[string]int32{
	"kMagicLampLevel_None":   0,
	"kMagicLampLevel_Level1": 1,
	"kMagicLampLevel_Level2": 2,
	"kMagicLampLevel_Level3": 3,
	"kMagicLampLevel_Level4": 4,
}

func (x MagicLampLevel) String() string {
	return proto.EnumName(MagicLampLevel_name, int32(x))
}
func (MagicLampLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptor46, []int{0} }

type MagicLampType int32

const (
	MagicLampType_kMagicLampType_None                     MagicLampType = 0
	MagicLampType_kMagicLampType_MilestoneComplete        MagicLampType = 10027
	MagicLampType_kMagicLampType_TempleFirstOccupat       MagicLampType = 10028
	MagicLampType_kMagicLampType_TempleBeRobbed           MagicLampType = 10029
	MagicLampType_kMagicLampType_PassFirstOccupat         MagicLampType = 10030
	MagicLampType_kMagicLampType_PassBeRobbed             MagicLampType = 10031
	MagicLampType_kMagicLampType_GuildBuildingCreate      MagicLampType = 10032
	MagicLampType_kMagicLampType_GuildBuildingConstruct   MagicLampType = 10033
	MagicLampType_kMagicLampType_GuildBuildingDestroyed   MagicLampType = 10034
	MagicLampType_kMagicLampType_GuildMarchCreate         MagicLampType = 10035
	MagicLampType_kMagicLampType_GuildMarchCancel         MagicLampType = 10036
	MagicLampType_kMagicLampType_PlayerBeAssembled        MagicLampType = 10037
	MagicLampType_kMagicLampType_GuildBuildingBeAssembled MagicLampType = 10038
	MagicLampType_kMagicLampType_TempleBeAssembled        MagicLampType = 10039
	MagicLampType_kMagicLampType_PassBeAssembled          MagicLampType = 10040
	MagicLampType_kMagicLampType_CreateGuild              MagicLampType = 10041
	MagicLampType_kMagicLampType_CreateGuildLabel         MagicLampType = 60022
	MagicLampType_kMagicLampType_RemoveGuildLabel         MagicLampType = 60010
	MagicLampType_kMagicLampType_AppointOfficial          MagicLampType = 10042
	MagicLampType_kMagicLampType_AddGuildGift             MagicLampType = 10043
	MagicLampType_kMagicLampType_JoinGuild                MagicLampType = 10044
	MagicLampType_kMagicLampType_QuitGuild                MagicLampType = 10045
	MagicLampType_kMagicLampType_SetKingdomTitle          MagicLampType = 60515
	MagicLampType_kMagicLampType_SendKingdomGift          MagicLampType = 60517
	MagicLampType_kMagicLampType_PompeiiSnatching         MagicLampType = 70144
	MagicLampType_kMagicLampType_PompeiiOccupied          MagicLampType = 70145
	MagicLampType_kMagicLampType_PompeiiKillBoss          MagicLampType = 70282
	MagicLampType_kMagicLampType_StartTempleWar           MagicLampType = 70283
	MagicLampType_kMagicLampType_SystemBegin              MagicLampType = 1000000
	MagicLampType_kMagicLampType_GM                       MagicLampType = 1000001
)

var MagicLampType_name = map[int32]string{
	0:       "kMagicLampType_None",
	10027:   "kMagicLampType_MilestoneComplete",
	10028:   "kMagicLampType_TempleFirstOccupat",
	10029:   "kMagicLampType_TempleBeRobbed",
	10030:   "kMagicLampType_PassFirstOccupat",
	10031:   "kMagicLampType_PassBeRobbed",
	10032:   "kMagicLampType_GuildBuildingCreate",
	10033:   "kMagicLampType_GuildBuildingConstruct",
	10034:   "kMagicLampType_GuildBuildingDestroyed",
	10035:   "kMagicLampType_GuildMarchCreate",
	10036:   "kMagicLampType_GuildMarchCancel",
	10037:   "kMagicLampType_PlayerBeAssembled",
	10038:   "kMagicLampType_GuildBuildingBeAssembled",
	10039:   "kMagicLampType_TempleBeAssembled",
	10040:   "kMagicLampType_PassBeAssembled",
	10041:   "kMagicLampType_CreateGuild",
	60022:   "kMagicLampType_CreateGuildLabel",
	60010:   "kMagicLampType_RemoveGuildLabel",
	10042:   "kMagicLampType_AppointOfficial",
	10043:   "kMagicLampType_AddGuildGift",
	10044:   "kMagicLampType_JoinGuild",
	10045:   "kMagicLampType_QuitGuild",
	60515:   "kMagicLampType_SetKingdomTitle",
	60517:   "kMagicLampType_SendKingdomGift",
	70144:   "kMagicLampType_PompeiiSnatching",
	70145:   "kMagicLampType_PompeiiOccupied",
	70282:   "kMagicLampType_PompeiiKillBoss",
	70283:   "kMagicLampType_StartTempleWar",
	1000000: "kMagicLampType_SystemBegin",
	1000001: "kMagicLampType_GM",
}
var MagicLampType_value = map[string]int32{
	"kMagicLampType_None":                     0,
	"kMagicLampType_MilestoneComplete":        10027,
	"kMagicLampType_TempleFirstOccupat":       10028,
	"kMagicLampType_TempleBeRobbed":           10029,
	"kMagicLampType_PassFirstOccupat":         10030,
	"kMagicLampType_PassBeRobbed":             10031,
	"kMagicLampType_GuildBuildingCreate":      10032,
	"kMagicLampType_GuildBuildingConstruct":   10033,
	"kMagicLampType_GuildBuildingDestroyed":   10034,
	"kMagicLampType_GuildMarchCreate":         10035,
	"kMagicLampType_GuildMarchCancel":         10036,
	"kMagicLampType_PlayerBeAssembled":        10037,
	"kMagicLampType_GuildBuildingBeAssembled": 10038,
	"kMagicLampType_TempleBeAssembled":        10039,
	"kMagicLampType_PassBeAssembled":          10040,
	"kMagicLampType_CreateGuild":              10041,
	"kMagicLampType_CreateGuildLabel":         60022,
	"kMagicLampType_RemoveGuildLabel":         60010,
	"kMagicLampType_AppointOfficial":          10042,
	"kMagicLampType_AddGuildGift":             10043,
	"kMagicLampType_JoinGuild":                10044,
	"kMagicLampType_QuitGuild":                10045,
	"kMagicLampType_SetKingdomTitle":          60515,
	"kMagicLampType_SendKingdomGift":          60517,
	"kMagicLampType_PompeiiSnatching":         70144,
	"kMagicLampType_PompeiiOccupied":          70145,
	"kMagicLampType_PompeiiKillBoss":          70282,
	"kMagicLampType_StartTempleWar":           70283,
	"kMagicLampType_SystemBegin":              1000000,
	"kMagicLampType_GM":                       1000001,
}

func (x MagicLampType) String() string {
	return proto.EnumName(MagicLampType_name, int32(x))
}
func (MagicLampType) EnumDescriptor() ([]byte, []int) { return fileDescriptor46, []int{1} }

// 走马灯发送类型
type MagicLampSendType int32

const (
	MagicLampSendType_kMagicLampSendType_None    MagicLampSendType = 0
	MagicLampSendType_kMagicLampSendType_Guild   MagicLampSendType = 1
	MagicLampSendType_kMagicLampSendType_Kingdom MagicLampSendType = 2
)

var MagicLampSendType_name = map[int32]string{
	0: "kMagicLampSendType_None",
	1: "kMagicLampSendType_Guild",
	2: "kMagicLampSendType_Kingdom",
}
var MagicLampSendType_value = map[string]int32{
	"kMagicLampSendType_None":    0,
	"kMagicLampSendType_Guild":   1,
	"kMagicLampSendType_Kingdom": 2,
}

func (x MagicLampSendType) String() string {
	return proto.EnumName(MagicLampSendType_name, int32(x))
}
func (MagicLampSendType) EnumDescriptor() ([]byte, []int) { return fileDescriptor46, []int{2} }

type LanguageMessageData struct {
	Language uint32 `protobuf:"varint,1,opt,name=language" json:"language,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *LanguageMessageData) Reset()                    { *m = LanguageMessageData{} }
func (m *LanguageMessageData) String() string            { return proto.CompactTextString(m) }
func (*LanguageMessageData) ProtoMessage()               {}
func (*LanguageMessageData) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{0} }

func (m *LanguageMessageData) GetLanguage() uint32 {
	if m != nil {
		return m.Language
	}
	return 0
}

func (m *LanguageMessageData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type MagicLampGMContent struct {
	Messages []*LanguageMessageData `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	Period   uint32                 `protobuf:"varint,2,opt,name=period" json:"period,omitempty"`
}

func (m *MagicLampGMContent) Reset()                    { *m = MagicLampGMContent{} }
func (m *MagicLampGMContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampGMContent) ProtoMessage()               {}
func (*MagicLampGMContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{1} }

func (m *MagicLampGMContent) GetMessages() []*LanguageMessageData {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *MagicLampGMContent) GetPeriod() uint32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type MagicLampTempleWinContent struct {
	TempleId          uint32    `protobuf:"varint,1,opt,name=temple_id,json=templeId" json:"temple_id,omitempty"`
	GuildName         string    `protobuf:"bytes,2,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	BeAttackGuildName string    `protobuf:"bytes,3,opt,name=be_attack_guild_name,json=beAttackGuildName" json:"be_attack_guild_name,omitempty"`
	Pos               *Vector2D `protobuf:"bytes,4,opt,name=pos" json:"pos,omitempty"`
}

func (m *MagicLampTempleWinContent) Reset()                    { *m = MagicLampTempleWinContent{} }
func (m *MagicLampTempleWinContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampTempleWinContent) ProtoMessage()               {}
func (*MagicLampTempleWinContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{2} }

func (m *MagicLampTempleWinContent) GetTempleId() uint32 {
	if m != nil {
		return m.TempleId
	}
	return 0
}

func (m *MagicLampTempleWinContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampTempleWinContent) GetBeAttackGuildName() string {
	if m != nil {
		return m.BeAttackGuildName
	}
	return ""
}

func (m *MagicLampTempleWinContent) GetPos() *Vector2D {
	if m != nil {
		return m.Pos
	}
	return nil
}

type MagicLampPassWinContent struct {
	PassId            uint32    `protobuf:"varint,1,opt,name=pass_id,json=passId" json:"pass_id,omitempty"`
	GuildName         string    `protobuf:"bytes,2,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	BeAttackGuildName string    `protobuf:"bytes,3,opt,name=be_attack_guild_name,json=beAttackGuildName" json:"be_attack_guild_name,omitempty"`
	Pos               *Vector2D `protobuf:"bytes,4,opt,name=pos" json:"pos,omitempty"`
}

func (m *MagicLampPassWinContent) Reset()                    { *m = MagicLampPassWinContent{} }
func (m *MagicLampPassWinContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampPassWinContent) ProtoMessage()               {}
func (*MagicLampPassWinContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{3} }

func (m *MagicLampPassWinContent) GetPassId() uint32 {
	if m != nil {
		return m.PassId
	}
	return 0
}

func (m *MagicLampPassWinContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampPassWinContent) GetBeAttackGuildName() string {
	if m != nil {
		return m.BeAttackGuildName
	}
	return ""
}

func (m *MagicLampPassWinContent) GetPos() *Vector2D {
	if m != nil {
		return m.Pos
	}
	return nil
}

type MagicLampCancelGuildLabelContent struct {
	LabelId    uint64 `protobuf:"varint,1,opt,name=label_id,json=labelId" json:"label_id,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *MagicLampCancelGuildLabelContent) Reset()         { *m = MagicLampCancelGuildLabelContent{} }
func (m *MagicLampCancelGuildLabelContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampCancelGuildLabelContent) ProtoMessage()    {}
func (*MagicLampCancelGuildLabelContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{4}
}

func (m *MagicLampCancelGuildLabelContent) GetLabelId() uint64 {
	if m != nil {
		return m.LabelId
	}
	return 0
}

func (m *MagicLampCancelGuildLabelContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type MagicLampRelieveCityLordContent struct {
	CityLordId    uint64    `protobuf:"varint,1,opt,name=city_lord_id,json=cityLordId" json:"city_lord_id,omitempty"`
	AppointName   string    `protobuf:"bytes,2,opt,name=appoint_name,json=appointName" json:"appoint_name,omitempty"`
	BeRelieveName string    `protobuf:"bytes,3,opt,name=be_relieve_name,json=beRelieveName" json:"be_relieve_name,omitempty"`
	Pos           *Vector2D `protobuf:"bytes,4,opt,name=pos" json:"pos,omitempty"`
}

func (m *MagicLampRelieveCityLordContent) Reset()         { *m = MagicLampRelieveCityLordContent{} }
func (m *MagicLampRelieveCityLordContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampRelieveCityLordContent) ProtoMessage()    {}
func (*MagicLampRelieveCityLordContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{5}
}

func (m *MagicLampRelieveCityLordContent) GetCityLordId() uint64 {
	if m != nil {
		return m.CityLordId
	}
	return 0
}

func (m *MagicLampRelieveCityLordContent) GetAppointName() string {
	if m != nil {
		return m.AppointName
	}
	return ""
}

func (m *MagicLampRelieveCityLordContent) GetBeRelieveName() string {
	if m != nil {
		return m.BeRelieveName
	}
	return ""
}

func (m *MagicLampRelieveCityLordContent) GetPos() *Vector2D {
	if m != nil {
		return m.Pos
	}
	return nil
}

type MagicLampMilestoneCompleteContent struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
}

func (m *MagicLampMilestoneCompleteContent) Reset()         { *m = MagicLampMilestoneCompleteContent{} }
func (m *MagicLampMilestoneCompleteContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampMilestoneCompleteContent) ProtoMessage()    {}
func (*MagicLampMilestoneCompleteContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{6}
}

func (m *MagicLampMilestoneCompleteContent) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type MagicLampTempleFirstOccupatContent struct {
	ConfigId       uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position       *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	GuildName      string    `protobuf:"bytes,3,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string    `protobuf:"bytes,4,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
}

func (m *MagicLampTempleFirstOccupatContent) Reset()         { *m = MagicLampTempleFirstOccupatContent{} }
func (m *MagicLampTempleFirstOccupatContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampTempleFirstOccupatContent) ProtoMessage()    {}
func (*MagicLampTempleFirstOccupatContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{7}
}

func (m *MagicLampTempleFirstOccupatContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampTempleFirstOccupatContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampTempleFirstOccupatContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampTempleFirstOccupatContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

type MagicLampTempleBeRobbedContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	DefendGuildName      string    `protobuf:"bytes,3,opt,name=defend_guild_name,json=defendGuildName" json:"defend_guild_name,omitempty"`
	DefendGuildShortName string    `protobuf:"bytes,4,opt,name=defend_guild_short_name,json=defendGuildShortName" json:"defend_guild_short_name,omitempty"`
	AttackGuildName      string    `protobuf:"bytes,5,opt,name=attack_guild_name,json=attackGuildName" json:"attack_guild_name,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,6,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
}

func (m *MagicLampTempleBeRobbedContent) Reset()                    { *m = MagicLampTempleBeRobbedContent{} }
func (m *MagicLampTempleBeRobbedContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampTempleBeRobbedContent) ProtoMessage()               {}
func (*MagicLampTempleBeRobbedContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{8} }

func (m *MagicLampTempleBeRobbedContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampTempleBeRobbedContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampTempleBeRobbedContent) GetDefendGuildName() string {
	if m != nil {
		return m.DefendGuildName
	}
	return ""
}

func (m *MagicLampTempleBeRobbedContent) GetDefendGuildShortName() string {
	if m != nil {
		return m.DefendGuildShortName
	}
	return ""
}

func (m *MagicLampTempleBeRobbedContent) GetAttackGuildName() string {
	if m != nil {
		return m.AttackGuildName
	}
	return ""
}

func (m *MagicLampTempleBeRobbedContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

type MagicLampPassFirstOccupatContent struct {
	ConfigId       uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position       *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	GuildName      string    `protobuf:"bytes,3,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string    `protobuf:"bytes,4,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
}

func (m *MagicLampPassFirstOccupatContent) Reset()         { *m = MagicLampPassFirstOccupatContent{} }
func (m *MagicLampPassFirstOccupatContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPassFirstOccupatContent) ProtoMessage()    {}
func (*MagicLampPassFirstOccupatContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{9}
}

func (m *MagicLampPassFirstOccupatContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampPassFirstOccupatContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampPassFirstOccupatContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampPassFirstOccupatContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

type MagicLampPassBeRobbedContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	DefendGuildName      string    `protobuf:"bytes,3,opt,name=defend_guild_name,json=defendGuildName" json:"defend_guild_name,omitempty"`
	DefendGuildShortName string    `protobuf:"bytes,4,opt,name=defend_guild_short_name,json=defendGuildShortName" json:"defend_guild_short_name,omitempty"`
	AttackGuildName      string    `protobuf:"bytes,5,opt,name=attack_guild_name,json=attackGuildName" json:"attack_guild_name,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,6,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
}

func (m *MagicLampPassBeRobbedContent) Reset()                    { *m = MagicLampPassBeRobbedContent{} }
func (m *MagicLampPassBeRobbedContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampPassBeRobbedContent) ProtoMessage()               {}
func (*MagicLampPassBeRobbedContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{10} }

func (m *MagicLampPassBeRobbedContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampPassBeRobbedContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampPassBeRobbedContent) GetDefendGuildName() string {
	if m != nil {
		return m.DefendGuildName
	}
	return ""
}

func (m *MagicLampPassBeRobbedContent) GetDefendGuildShortName() string {
	if m != nil {
		return m.DefendGuildShortName
	}
	return ""
}

func (m *MagicLampPassBeRobbedContent) GetAttackGuildName() string {
	if m != nil {
		return m.AttackGuildName
	}
	return ""
}

func (m *MagicLampPassBeRobbedContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

type MagicLampGuildBuildingCreateContent struct {
	ConfigId uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
}

func (m *MagicLampGuildBuildingCreateContent) Reset()         { *m = MagicLampGuildBuildingCreateContent{} }
func (m *MagicLampGuildBuildingCreateContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildBuildingCreateContent) ProtoMessage()    {}
func (*MagicLampGuildBuildingCreateContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{11}
}

func (m *MagicLampGuildBuildingCreateContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampGuildBuildingCreateContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

type MagicLampGuildBuildingConstructContent struct {
	ConfigId uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
}

func (m *MagicLampGuildBuildingConstructContent) Reset() {
	*m = MagicLampGuildBuildingConstructContent{}
}
func (m *MagicLampGuildBuildingConstructContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildBuildingConstructContent) ProtoMessage()    {}
func (*MagicLampGuildBuildingConstructContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{12}
}

func (m *MagicLampGuildBuildingConstructContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampGuildBuildingConstructContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

type MagicLampGuildBuildingDestroyedContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	DefendGuildName      string    `protobuf:"bytes,3,opt,name=defend_guild_name,json=defendGuildName" json:"defend_guild_name,omitempty"`
	DefendGuildShortName string    `protobuf:"bytes,4,opt,name=defend_guild_short_name,json=defendGuildShortName" json:"defend_guild_short_name,omitempty"`
	AttackGuildName      string    `protobuf:"bytes,5,opt,name=attack_guild_name,json=attackGuildName" json:"attack_guild_name,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,6,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
}

func (m *MagicLampGuildBuildingDestroyedContent) Reset() {
	*m = MagicLampGuildBuildingDestroyedContent{}
}
func (m *MagicLampGuildBuildingDestroyedContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildBuildingDestroyedContent) ProtoMessage()    {}
func (*MagicLampGuildBuildingDestroyedContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{13}
}

func (m *MagicLampGuildBuildingDestroyedContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampGuildBuildingDestroyedContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampGuildBuildingDestroyedContent) GetDefendGuildName() string {
	if m != nil {
		return m.DefendGuildName
	}
	return ""
}

func (m *MagicLampGuildBuildingDestroyedContent) GetDefendGuildShortName() string {
	if m != nil {
		return m.DefendGuildShortName
	}
	return ""
}

func (m *MagicLampGuildBuildingDestroyedContent) GetAttackGuildName() string {
	if m != nil {
		return m.AttackGuildName
	}
	return ""
}

func (m *MagicLampGuildBuildingDestroyedContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

type MagicLampGuildMarchCreateContent struct {
	AttackPlayerName     string     `protobuf:"bytes,1,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
	EntityType           EntityType `protobuf:"varint,2,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	ConfigId             uint32     `protobuf:"varint,3,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	DefendPlayerName     string     `protobuf:"bytes,4,opt,name=defend_player_name,json=defendPlayerName" json:"defend_player_name,omitempty"`
	DefendGuildShortName string     `protobuf:"bytes,5,opt,name=defend_guild_short_name,json=defendGuildShortName" json:"defend_guild_short_name,omitempty"`
}

func (m *MagicLampGuildMarchCreateContent) Reset()         { *m = MagicLampGuildMarchCreateContent{} }
func (m *MagicLampGuildMarchCreateContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildMarchCreateContent) ProtoMessage()    {}
func (*MagicLampGuildMarchCreateContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{14}
}

func (m *MagicLampGuildMarchCreateContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

func (m *MagicLampGuildMarchCreateContent) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MagicLampGuildMarchCreateContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampGuildMarchCreateContent) GetDefendPlayerName() string {
	if m != nil {
		return m.DefendPlayerName
	}
	return ""
}

func (m *MagicLampGuildMarchCreateContent) GetDefendGuildShortName() string {
	if m != nil {
		return m.DefendGuildShortName
	}
	return ""
}

type MagicLampGuildMarchCancelContent struct {
	AttackPlayerName string `protobuf:"bytes,1,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
}

func (m *MagicLampGuildMarchCancelContent) Reset()         { *m = MagicLampGuildMarchCancelContent{} }
func (m *MagicLampGuildMarchCancelContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildMarchCancelContent) ProtoMessage()    {}
func (*MagicLampGuildMarchCancelContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{15}
}

func (m *MagicLampGuildMarchCancelContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

type MagicLampPlayerBeAssembledContent struct {
	DefendPlayerName     string `protobuf:"bytes,1,opt,name=defend_player_name,json=defendPlayerName" json:"defend_player_name,omitempty"`
	AttackGuildShortName string `protobuf:"bytes,2,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
	AttackPlayerName     string `protobuf:"bytes,3,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
}

func (m *MagicLampPlayerBeAssembledContent) Reset()         { *m = MagicLampPlayerBeAssembledContent{} }
func (m *MagicLampPlayerBeAssembledContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPlayerBeAssembledContent) ProtoMessage()    {}
func (*MagicLampPlayerBeAssembledContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{16}
}

func (m *MagicLampPlayerBeAssembledContent) GetDefendPlayerName() string {
	if m != nil {
		return m.DefendPlayerName
	}
	return ""
}

func (m *MagicLampPlayerBeAssembledContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

func (m *MagicLampPlayerBeAssembledContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

type MagicLampGuildBuildingBeAssembledContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,3,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
	AttackPlayerName     string    `protobuf:"bytes,4,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
}

func (m *MagicLampGuildBuildingBeAssembledContent) Reset() {
	*m = MagicLampGuildBuildingBeAssembledContent{}
}
func (m *MagicLampGuildBuildingBeAssembledContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampGuildBuildingBeAssembledContent) ProtoMessage()    {}
func (*MagicLampGuildBuildingBeAssembledContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{17}
}

func (m *MagicLampGuildBuildingBeAssembledContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampGuildBuildingBeAssembledContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampGuildBuildingBeAssembledContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

func (m *MagicLampGuildBuildingBeAssembledContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

type MagicLampTempleBeAssembledContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,3,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
	AttackPlayerName     string    `protobuf:"bytes,4,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
}

func (m *MagicLampTempleBeAssembledContent) Reset()         { *m = MagicLampTempleBeAssembledContent{} }
func (m *MagicLampTempleBeAssembledContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampTempleBeAssembledContent) ProtoMessage()    {}
func (*MagicLampTempleBeAssembledContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{18}
}

func (m *MagicLampTempleBeAssembledContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampTempleBeAssembledContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampTempleBeAssembledContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

func (m *MagicLampTempleBeAssembledContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

type MagicLampPassBeAssembledContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,3,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
	AttackPlayerName     string    `protobuf:"bytes,4,opt,name=attack_player_name,json=attackPlayerName" json:"attack_player_name,omitempty"`
}

func (m *MagicLampPassBeAssembledContent) Reset()         { *m = MagicLampPassBeAssembledContent{} }
func (m *MagicLampPassBeAssembledContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPassBeAssembledContent) ProtoMessage()    {}
func (*MagicLampPassBeAssembledContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{19}
}

func (m *MagicLampPassBeAssembledContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampPassBeAssembledContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampPassBeAssembledContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

func (m *MagicLampPassBeAssembledContent) GetAttackPlayerName() string {
	if m != nil {
		return m.AttackPlayerName
	}
	return ""
}

type MagicLampCreateGuildContent struct {
	PlayerName     string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	GuildName      string `protobuf:"bytes,2,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string `protobuf:"bytes,3,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
}

func (m *MagicLampCreateGuildContent) Reset()                    { *m = MagicLampCreateGuildContent{} }
func (m *MagicLampCreateGuildContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampCreateGuildContent) ProtoMessage()               {}
func (*MagicLampCreateGuildContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{20} }

func (m *MagicLampCreateGuildContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampCreateGuildContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampCreateGuildContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

type MagicLampCreateGuildLabelContent struct {
	PlayerName string        `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	Official   GuildOfficial `protobuf:"varint,2,opt,name=official,enum=protomsg.GuildOfficial" json:"official,omitempty"`
	LabelId    uint32        `protobuf:"varint,3,opt,name=label_id,json=labelId" json:"label_id,omitempty"`
}

func (m *MagicLampCreateGuildLabelContent) Reset()         { *m = MagicLampCreateGuildLabelContent{} }
func (m *MagicLampCreateGuildLabelContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampCreateGuildLabelContent) ProtoMessage()    {}
func (*MagicLampCreateGuildLabelContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{21}
}

func (m *MagicLampCreateGuildLabelContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampCreateGuildLabelContent) GetOfficial() GuildOfficial {
	if m != nil {
		return m.Official
	}
	return GuildOfficial_kGuildOfficialNone
}

func (m *MagicLampCreateGuildLabelContent) GetLabelId() uint32 {
	if m != nil {
		return m.LabelId
	}
	return 0
}

type MagicLampRemoveGuildLabelContent struct {
	PlayerName string        `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	Official   GuildOfficial `protobuf:"varint,2,opt,name=official,enum=protomsg.GuildOfficial" json:"official,omitempty"`
	LabelId    uint32        `protobuf:"varint,3,opt,name=label_id,json=labelId" json:"label_id,omitempty"`
}

func (m *MagicLampRemoveGuildLabelContent) Reset()         { *m = MagicLampRemoveGuildLabelContent{} }
func (m *MagicLampRemoveGuildLabelContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampRemoveGuildLabelContent) ProtoMessage()    {}
func (*MagicLampRemoveGuildLabelContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{22}
}

func (m *MagicLampRemoveGuildLabelContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampRemoveGuildLabelContent) GetOfficial() GuildOfficial {
	if m != nil {
		return m.Official
	}
	return GuildOfficial_kGuildOfficialNone
}

func (m *MagicLampRemoveGuildLabelContent) GetLabelId() uint32 {
	if m != nil {
		return m.LabelId
	}
	return 0
}

type MagicLampAppointOfficialContent struct {
	PlayerName string        `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	Official   GuildOfficial `protobuf:"varint,2,opt,name=official,enum=protomsg.GuildOfficial" json:"official,omitempty"`
}

func (m *MagicLampAppointOfficialContent) Reset()         { *m = MagicLampAppointOfficialContent{} }
func (m *MagicLampAppointOfficialContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampAppointOfficialContent) ProtoMessage()    {}
func (*MagicLampAppointOfficialContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{23}
}

func (m *MagicLampAppointOfficialContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampAppointOfficialContent) GetOfficial() GuildOfficial {
	if m != nil {
		return m.Official
	}
	return GuildOfficial_kGuildOfficialNone
}

type MagicLampAddGuildGiftContent struct {
	GiftId uint32 `protobuf:"varint,1,opt,name=gift_id,json=giftId" json:"gift_id,omitempty"`
}

func (m *MagicLampAddGuildGiftContent) Reset()                    { *m = MagicLampAddGuildGiftContent{} }
func (m *MagicLampAddGuildGiftContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampAddGuildGiftContent) ProtoMessage()               {}
func (*MagicLampAddGuildGiftContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{24} }

func (m *MagicLampAddGuildGiftContent) GetGiftId() uint32 {
	if m != nil {
		return m.GiftId
	}
	return 0
}

type MagicLampJoinGuildContent struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *MagicLampJoinGuildContent) Reset()                    { *m = MagicLampJoinGuildContent{} }
func (m *MagicLampJoinGuildContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampJoinGuildContent) ProtoMessage()               {}
func (*MagicLampJoinGuildContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{25} }

func (m *MagicLampJoinGuildContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type MagicLampQuitGuildContent struct {
	PlayerName string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *MagicLampQuitGuildContent) Reset()                    { *m = MagicLampQuitGuildContent{} }
func (m *MagicLampQuitGuildContent) String() string            { return proto.CompactTextString(m) }
func (*MagicLampQuitGuildContent) ProtoMessage()               {}
func (*MagicLampQuitGuildContent) Descriptor() ([]byte, []int) { return fileDescriptor46, []int{26} }

func (m *MagicLampQuitGuildContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type MagicLampSetKingdomTitleContent struct {
	PlayerName      string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	TitleId         uint32 `protobuf:"varint,2,opt,name=title_id,json=titleId" json:"title_id,omitempty"`
	BeSetPlayerName string `protobuf:"bytes,3,opt,name=be_set_player_name,json=beSetPlayerName" json:"be_set_player_name,omitempty"`
	BeSetTitle      uint32 `protobuf:"varint,4,opt,name=be_set_title,json=beSetTitle" json:"be_set_title,omitempty"`
}

func (m *MagicLampSetKingdomTitleContent) Reset()         { *m = MagicLampSetKingdomTitleContent{} }
func (m *MagicLampSetKingdomTitleContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampSetKingdomTitleContent) ProtoMessage()    {}
func (*MagicLampSetKingdomTitleContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{27}
}

func (m *MagicLampSetKingdomTitleContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampSetKingdomTitleContent) GetTitleId() uint32 {
	if m != nil {
		return m.TitleId
	}
	return 0
}

func (m *MagicLampSetKingdomTitleContent) GetBeSetPlayerName() string {
	if m != nil {
		return m.BeSetPlayerName
	}
	return ""
}

func (m *MagicLampSetKingdomTitleContent) GetBeSetTitle() uint32 {
	if m != nil {
		return m.BeSetTitle
	}
	return 0
}

type MagicLampSendKingdomGiftContent struct {
	PlayerName       string `protobuf:"bytes,1,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	TitleId          uint32 `protobuf:"varint,2,opt,name=title_id,json=titleId" json:"title_id,omitempty"`
	GiftId           uint32 `protobuf:"varint,3,opt,name=gift_id,json=giftId" json:"gift_id,omitempty"`
	BeSendPlayerName string `protobuf:"bytes,4,opt,name=be_send_player_name,json=beSendPlayerName" json:"be_send_player_name,omitempty"`
}

func (m *MagicLampSendKingdomGiftContent) Reset()         { *m = MagicLampSendKingdomGiftContent{} }
func (m *MagicLampSendKingdomGiftContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampSendKingdomGiftContent) ProtoMessage()    {}
func (*MagicLampSendKingdomGiftContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{28}
}

func (m *MagicLampSendKingdomGiftContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampSendKingdomGiftContent) GetTitleId() uint32 {
	if m != nil {
		return m.TitleId
	}
	return 0
}

func (m *MagicLampSendKingdomGiftContent) GetGiftId() uint32 {
	if m != nil {
		return m.GiftId
	}
	return 0
}

func (m *MagicLampSendKingdomGiftContent) GetBeSendPlayerName() string {
	if m != nil {
		return m.BeSendPlayerName
	}
	return ""
}

// 庞贝的建筑被完全占领时发送
type MagicLampPompeiiBuildOccupiedContent struct {
	ConfigId       uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position       *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	GuildName      string    `protobuf:"bytes,3,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string    `protobuf:"bytes,4,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
	GuildId        uint64    `protobuf:"varint,5,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	ForceId        uint32    `protobuf:"varint,6,opt,name=force_id,json=forceId" json:"force_id,omitempty"`
}

func (m *MagicLampPompeiiBuildOccupiedContent) Reset()         { *m = MagicLampPompeiiBuildOccupiedContent{} }
func (m *MagicLampPompeiiBuildOccupiedContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPompeiiBuildOccupiedContent) ProtoMessage()    {}
func (*MagicLampPompeiiBuildOccupiedContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{29}
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MagicLampPompeiiBuildOccupiedContent) GetForceId() uint32 {
	if m != nil {
		return m.ForceId
	}
	return 0
}

// 庞贝的建筑占领中发送
type MagicLampPompeiiBuildSnatchingContent struct {
	ConfigId       uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position       *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	GuildName      string    `protobuf:"bytes,3,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string    `protobuf:"bytes,4,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
	Time           uint32    `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	GuildId        uint64    `protobuf:"varint,6,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	ForceId        uint32    `protobuf:"varint,7,opt,name=force_id,json=forceId" json:"force_id,omitempty"`
}

func (m *MagicLampPompeiiBuildSnatchingContent) Reset()         { *m = MagicLampPompeiiBuildSnatchingContent{} }
func (m *MagicLampPompeiiBuildSnatchingContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPompeiiBuildSnatchingContent) ProtoMessage()    {}
func (*MagicLampPompeiiBuildSnatchingContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{30}
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MagicLampPompeiiBuildSnatchingContent) GetForceId() uint32 {
	if m != nil {
		return m.ForceId
	}
	return 0
}

type MagicLampPompeiiKillBossContent struct {
	GuildName      string `protobuf:"bytes,1,opt,name=guild_name,json=guildName" json:"guild_name,omitempty"`
	GuildShortName string `protobuf:"bytes,2,opt,name=guild_short_name,json=guildShortName" json:"guild_short_name,omitempty"`
	GuildId        uint64 `protobuf:"varint,3,opt,name=guild_id,json=guildId" json:"guild_id,omitempty"`
	ForceId        uint32 `protobuf:"varint,4,opt,name=force_id,json=forceId" json:"force_id,omitempty"`
	MonsterId      uint32 `protobuf:"varint,5,opt,name=monster_id,json=monsterId" json:"monster_id,omitempty"`
	PlayerName     string `protobuf:"bytes,6,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
	TotalKillCount uint32 `protobuf:"varint,7,opt,name=total_kill_count,json=totalKillCount" json:"total_kill_count,omitempty"`
}

func (m *MagicLampPompeiiKillBossContent) Reset()         { *m = MagicLampPompeiiKillBossContent{} }
func (m *MagicLampPompeiiKillBossContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampPompeiiKillBossContent) ProtoMessage()    {}
func (*MagicLampPompeiiKillBossContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{31}
}

func (m *MagicLampPompeiiKillBossContent) GetGuildName() string {
	if m != nil {
		return m.GuildName
	}
	return ""
}

func (m *MagicLampPompeiiKillBossContent) GetGuildShortName() string {
	if m != nil {
		return m.GuildShortName
	}
	return ""
}

func (m *MagicLampPompeiiKillBossContent) GetGuildId() uint64 {
	if m != nil {
		return m.GuildId
	}
	return 0
}

func (m *MagicLampPompeiiKillBossContent) GetForceId() uint32 {
	if m != nil {
		return m.ForceId
	}
	return 0
}

func (m *MagicLampPompeiiKillBossContent) GetMonsterId() uint32 {
	if m != nil {
		return m.MonsterId
	}
	return 0
}

func (m *MagicLampPompeiiKillBossContent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *MagicLampPompeiiKillBossContent) GetTotalKillCount() uint32 {
	if m != nil {
		return m.TotalKillCount
	}
	return 0
}

type MagicLampStartTempleWarContent struct {
	ConfigId             uint32    `protobuf:"varint,1,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Position             *Vector2D `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	DefendGuildName      string    `protobuf:"bytes,3,opt,name=defend_guild_name,json=defendGuildName" json:"defend_guild_name,omitempty"`
	DefendGuildShortName string    `protobuf:"bytes,4,opt,name=defend_guild_short_name,json=defendGuildShortName" json:"defend_guild_short_name,omitempty"`
	AttackGuildName      string    `protobuf:"bytes,5,opt,name=attack_guild_name,json=attackGuildName" json:"attack_guild_name,omitempty"`
	AttackGuildShortName string    `protobuf:"bytes,6,opt,name=attack_guild_short_name,json=attackGuildShortName" json:"attack_guild_short_name,omitempty"`
}

func (m *MagicLampStartTempleWarContent) Reset()         { *m = MagicLampStartTempleWarContent{} }
func (m *MagicLampStartTempleWarContent) String() string { return proto.CompactTextString(m) }
func (*MagicLampStartTempleWarContent) ProtoMessage()    {}
func (*MagicLampStartTempleWarContent) Descriptor() ([]byte, []int) {
	return fileDescriptor46, []int{32}
}

func (m *MagicLampStartTempleWarContent) GetConfigId() uint32 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *MagicLampStartTempleWarContent) GetPosition() *Vector2D {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *MagicLampStartTempleWarContent) GetDefendGuildName() string {
	if m != nil {
		return m.DefendGuildName
	}
	return ""
}

func (m *MagicLampStartTempleWarContent) GetDefendGuildShortName() string {
	if m != nil {
		return m.DefendGuildShortName
	}
	return ""
}

func (m *MagicLampStartTempleWarContent) GetAttackGuildName() string {
	if m != nil {
		return m.AttackGuildName
	}
	return ""
}

func (m *MagicLampStartTempleWarContent) GetAttackGuildShortName() string {
	if m != nil {
		return m.AttackGuildShortName
	}
	return ""
}

func init() {
	proto.RegisterType((*LanguageMessageData)(nil), "protomsg.LanguageMessageData")
	proto.RegisterType((*MagicLampGMContent)(nil), "protomsg.MagicLampGMContent")
	proto.RegisterType((*MagicLampTempleWinContent)(nil), "protomsg.MagicLampTempleWinContent")
	proto.RegisterType((*MagicLampPassWinContent)(nil), "protomsg.MagicLampPassWinContent")
	proto.RegisterType((*MagicLampCancelGuildLabelContent)(nil), "protomsg.MagicLampCancelGuildLabelContent")
	proto.RegisterType((*MagicLampRelieveCityLordContent)(nil), "protomsg.MagicLampRelieveCityLordContent")
	proto.RegisterType((*MagicLampMilestoneCompleteContent)(nil), "protomsg.MagicLampMilestoneCompleteContent")
	proto.RegisterType((*MagicLampTempleFirstOccupatContent)(nil), "protomsg.MagicLampTempleFirstOccupatContent")
	proto.RegisterType((*MagicLampTempleBeRobbedContent)(nil), "protomsg.MagicLampTempleBeRobbedContent")
	proto.RegisterType((*MagicLampPassFirstOccupatContent)(nil), "protomsg.MagicLampPassFirstOccupatContent")
	proto.RegisterType((*MagicLampPassBeRobbedContent)(nil), "protomsg.MagicLampPassBeRobbedContent")
	proto.RegisterType((*MagicLampGuildBuildingCreateContent)(nil), "protomsg.MagicLampGuildBuildingCreateContent")
	proto.RegisterType((*MagicLampGuildBuildingConstructContent)(nil), "protomsg.MagicLampGuildBuildingConstructContent")
	proto.RegisterType((*MagicLampGuildBuildingDestroyedContent)(nil), "protomsg.MagicLampGuildBuildingDestroyedContent")
	proto.RegisterType((*MagicLampGuildMarchCreateContent)(nil), "protomsg.MagicLampGuildMarchCreateContent")
	proto.RegisterType((*MagicLampGuildMarchCancelContent)(nil), "protomsg.MagicLampGuildMarchCancelContent")
	proto.RegisterType((*MagicLampPlayerBeAssembledContent)(nil), "protomsg.MagicLampPlayerBeAssembledContent")
	proto.RegisterType((*MagicLampGuildBuildingBeAssembledContent)(nil), "protomsg.MagicLampGuildBuildingBeAssembledContent")
	proto.RegisterType((*MagicLampTempleBeAssembledContent)(nil), "protomsg.MagicLampTempleBeAssembledContent")
	proto.RegisterType((*MagicLampPassBeAssembledContent)(nil), "protomsg.MagicLampPassBeAssembledContent")
	proto.RegisterType((*MagicLampCreateGuildContent)(nil), "protomsg.MagicLampCreateGuildContent")
	proto.RegisterType((*MagicLampCreateGuildLabelContent)(nil), "protomsg.MagicLampCreateGuildLabelContent")
	proto.RegisterType((*MagicLampRemoveGuildLabelContent)(nil), "protomsg.MagicLampRemoveGuildLabelContent")
	proto.RegisterType((*MagicLampAppointOfficialContent)(nil), "protomsg.MagicLampAppointOfficialContent")
	proto.RegisterType((*MagicLampAddGuildGiftContent)(nil), "protomsg.MagicLampAddGuildGiftContent")
	proto.RegisterType((*MagicLampJoinGuildContent)(nil), "protomsg.MagicLampJoinGuildContent")
	proto.RegisterType((*MagicLampQuitGuildContent)(nil), "protomsg.MagicLampQuitGuildContent")
	proto.RegisterType((*MagicLampSetKingdomTitleContent)(nil), "protomsg.MagicLampSetKingdomTitleContent")
	proto.RegisterType((*MagicLampSendKingdomGiftContent)(nil), "protomsg.MagicLampSendKingdomGiftContent")
	proto.RegisterType((*MagicLampPompeiiBuildOccupiedContent)(nil), "protomsg.MagicLampPompeiiBuildOccupiedContent")
	proto.RegisterType((*MagicLampPompeiiBuildSnatchingContent)(nil), "protomsg.MagicLampPompeiiBuildSnatchingContent")
	proto.RegisterType((*MagicLampPompeiiKillBossContent)(nil), "protomsg.MagicLampPompeiiKillBossContent")
	proto.RegisterType((*MagicLampStartTempleWarContent)(nil), "protomsg.MagicLampStartTempleWarContent")
	proto.RegisterEnum("protomsg.MagicLampLevel", MagicLampLevel_name, MagicLampLevel_value)
	proto.RegisterEnum("protomsg.MagicLampType", MagicLampType_name, MagicLampType_value)
	proto.RegisterEnum("protomsg.MagicLampSendType", MagicLampSendType_name, MagicLampSendType_value)
}

func init() { proto.RegisterFile("msg_common_magic_lamp.proto", fileDescriptor46) }

var fileDescriptor46 = []byte{
	// 1650 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcb, 0x6f, 0x1c, 0x45,
	0x13, 0xff, 0x66, 0x77, 0xe3, 0x47, 0x39, 0x76, 0xda, 0x1d, 0x2b, 0xeb, 0xd8, 0x71, 0xbc, 0x99,
	0xbc, 0x2c, 0x7f, 0xc1, 0x08, 0x87, 0x08, 0x21, 0x25, 0x07, 0xdb, 0x81, 0x68, 0x89, 0xbd, 0x09,
	0xeb, 0x48, 0xdc, 0x58, 0xcd, 0xce, 0xb4, 0x37, 0x2d, 0xcf, 0x4c, 0x8f, 0x66, 0xda, 0x46, 0xbe,
	0x81, 0x14, 0x29, 0x22, 0x1c, 0xb9, 0x71, 0x26, 0x12, 0x12, 0x21, 0x10, 0x12, 0x42, 0x48, 0x40,
	0x82, 0xbf, 0x81, 0x20, 0xe5, 0xc0, 0x0d, 0xb8, 0x70, 0xe4, 0xc0, 0x19, 0x4d, 0xcf, 0xab, 0x67,
	0x76, 0xc6, 0x8e, 0x21, 0x16, 0x21, 0xca, 0xc5, 0xde, 0xae, 0xaa, 0xe9, 0xfa, 0xd5, 0xa3, 0xbb,
	0xaa, 0x1a, 0xc6, 0x2d, 0xaf, 0xd3, 0xd2, 0x99, 0x65, 0x31, 0xbb, 0x65, 0x69, 0x1d, 0xaa, 0xb7,
	0x4c, 0xcd, 0x72, 0x66, 0x1c, 0x97, 0x71, 0x86, 0xfb, 0xc4, 0x3f, 0xcb, 0xeb, 0x8c, 0xa1, 0x44,
	0x2c, 0xe0, 0x8d, 0x8d, 0xa4, 0x3e, 0x0c, 0xbf, 0x18, 0xdb, 0x27, 0x51, 0x3b, 0x6b, 0xd4, 0x34,
	0x02, 0xba, 0x7a, 0x1e, 0xf6, 0x2e, 0x6a, 0x76, 0x67, 0x4d, 0xeb, 0x90, 0x25, 0xe2, 0x79, 0x5a,
	0x87, 0x9c, 0xd5, 0xb8, 0x86, 0xc7, 0xa0, 0xcf, 0x0c, 0xc9, 0xa3, 0x4a, 0x4d, 0x99, 0x1a, 0x6c,
	0xc6, 0x6b, 0x3c, 0x0a, 0xbd, 0x3a, 0xb3, 0x39, 0xb1, 0xf9, 0x68, 0xa9, 0xa6, 0x4c, 0xf5, 0x37,
	0xa3, 0xa5, 0xda, 0x01, 0xbc, 0xe4, 0x43, 0x5d, 0xd4, 0x2c, 0xe7, 0xdc, 0xd2, 0x42, 0x40, 0xc5,
	0xaf, 0x42, 0x9f, 0x15, 0x6c, 0xed, 0x8d, 0x2a, 0xb5, 0xf2, 0xd4, 0xc0, 0xec, 0xc4, 0x4c, 0x84,
	0x7f, 0x26, 0x47, 0x79, 0x33, 0x16, 0xc7, 0xfb, 0xa0, 0xc7, 0x21, 0x2e, 0x65, 0x86, 0xd0, 0x34,
	0xd8, 0x0c, 0x57, 0xea, 0x4d, 0x05, 0xf6, 0xc7, 0x9a, 0x2e, 0x11, 0xcb, 0x31, 0xc9, 0x5b, 0xd4,
	0x8e, 0x14, 0x8e, 0x43, 0x3f, 0x17, 0xb4, 0x16, 0x35, 0x22, 0xf4, 0x01, 0xa1, 0x6e, 0xe0, 0x09,
	0x00, 0x61, 0x7f, 0xcb, 0xd6, 0x2c, 0x12, 0x1a, 0xd0, 0x2f, 0x28, 0x0d, 0xcd, 0x22, 0xf8, 0x45,
	0x18, 0x69, 0x93, 0x96, 0xc6, 0xb9, 0xa6, 0xaf, 0xb6, 0x24, 0xc1, 0xb2, 0x10, 0x1c, 0x6e, 0x93,
	0x39, 0xc1, 0x3a, 0x17, 0x7f, 0x70, 0x04, 0xca, 0x0e, 0xf3, 0x46, 0x2b, 0x35, 0x65, 0x6a, 0x60,
	0x16, 0x27, 0x86, 0xad, 0x13, 0x9d, 0x33, 0x77, 0xd6, 0x68, 0xfa, 0x6c, 0xf5, 0x13, 0x05, 0xaa,
	0x31, 0xe0, 0x8b, 0x9a, 0xe7, 0x49, 0x70, 0xab, 0xd0, 0xeb, 0x68, 0x9e, 0x97, 0x80, 0xed, 0xf1,
	0x97, 0xff, 0x1a, 0xd4, 0xb7, 0xa1, 0x16, 0x23, 0x5d, 0xd0, 0x6c, 0x9d, 0x98, 0x62, 0x87, 0x45,
	0xad, 0x4d, 0xcc, 0x08, 0xf2, 0x7e, 0x3f, 0x3d, 0xda, 0xc4, 0x8c, 0x30, 0x57, 0x9a, 0xbd, 0x62,
	0x5d, 0x37, 0xf0, 0x24, 0x0c, 0x38, 0xa6, 0xb6, 0x41, 0x5c, 0x19, 0x35, 0x04, 0x24, 0x1f, 0x85,
	0x7a, 0x47, 0x81, 0xc9, 0x58, 0x41, 0x93, 0x98, 0x94, 0xac, 0x93, 0x05, 0xca, 0x37, 0x16, 0x99,
	0x6b, 0x44, 0xfb, 0xd7, 0x60, 0xb7, 0x4e, 0xf9, 0x46, 0xcb, 0x64, 0xae, 0x91, 0xe8, 0x00, 0x3d,
	0x14, 0xab, 0x1b, 0xf8, 0x10, 0xec, 0xd6, 0x1c, 0x87, 0x51, 0x9b, 0xcb, 0x7a, 0x06, 0x42, 0x9a,
	0x30, 0xf7, 0x18, 0xec, 0x69, 0x93, 0x96, 0x1b, 0x68, 0x90, 0x5d, 0x33, 0xd8, 0x26, 0xa1, 0xde,
	0x6d, 0xb8, 0xe5, 0x34, 0x1c, 0x8a, 0x51, 0x2f, 0x51, 0x93, 0x78, 0x9c, 0xd9, 0x64, 0x81, 0xf9,
	0x59, 0xc5, 0x89, 0x14, 0x4a, 0xae, 0x79, 0xab, 0x52, 0x28, 0xfd, 0x65, 0xdd, 0x50, 0xef, 0x2b,
	0xa0, 0x66, 0x12, 0xf6, 0x75, 0xea, 0x7a, 0xfc, 0x82, 0xae, 0xaf, 0x39, 0x1a, 0x97, 0x32, 0x57,
	0x67, 0xf6, 0x0a, 0xed, 0x48, 0x99, 0x1b, 0x10, 0xea, 0x06, 0x9e, 0x81, 0x3e, 0x87, 0x79, 0x94,
	0x53, 0x66, 0x0b, 0x73, 0xf3, 0xc1, 0xc6, 0x32, 0x99, 0xf4, 0x29, 0x67, 0xd3, 0x67, 0x0a, 0x50,
	0xc0, 0xf6, 0x2e, 0x33, 0x37, 0xf4, 0x62, 0x45, 0x08, 0x0d, 0x09, 0xfa, 0xb2, 0x4f, 0x16, 0x11,
	0xbb, 0x5d, 0x82, 0x83, 0x19, 0xf0, 0xf3, 0xa4, 0xc9, 0xda, 0x6d, 0x62, 0xec, 0x08, 0xf0, 0x69,
	0x18, 0x36, 0xc8, 0x0a, 0xb1, 0x8d, 0xee, 0xac, 0xde, 0x13, 0x30, 0x92, 0x9c, 0x3e, 0x05, 0xd5,
	0x94, 0x6c, 0x97, 0x31, 0x23, 0xd2, 0x17, 0xb1, 0x49, 0xbe, 0x8a, 0xee, 0x83, 0xb3, 0x2b, 0x50,
	0xa1, 0x65, 0x8e, 0xcd, 0x29, 0xa8, 0xa6, 0x64, 0x25, 0x15, 0x3d, 0x81, 0x0a, 0xe9, 0x8b, 0xc4,
	0x6b, 0xf7, 0x14, 0xe9, 0x20, 0xf9, 0x47, 0xfe, 0xbf, 0x13, 0xf0, 0x5b, 0x25, 0x38, 0x90, 0x82,
	0xfe, 0x3c, 0xdc, 0x5b, 0x86, 0xdb, 0x85, 0xc3, 0x49, 0xed, 0xf3, 0x59, 0xf3, 0xfe, 0x1f, 0x6a,
	0x77, 0x16, 0x5c, 0xa2, 0x25, 0x37, 0xc4, 0x93, 0xf4, 0x9c, 0xba, 0x06, 0xc7, 0x0a, 0x74, 0x32,
	0xdb, 0xe3, 0xee, 0x9a, 0xbe, 0x23, 0x79, 0xa6, 0x3e, 0x28, 0x15, 0xe9, 0x3d, 0x4b, 0x3c, 0xee,
	0xb2, 0x8d, 0xe7, 0x89, 0xb2, 0x49, 0xa2, 0xbc, 0x5f, 0x92, 0xee, 0x05, 0xc1, 0x5b, 0xd2, 0x5c,
	0xfd, 0x72, 0x3a, 0x4d, 0x4e, 0x00, 0x0e, 0xf7, 0x96, 0x8b, 0xa9, 0x22, 0xb6, 0x45, 0x01, 0xe7,
	0x62, 0x5c, 0x52, 0xf1, 0x29, 0x18, 0x20, 0x36, 0xf7, 0x0b, 0x26, 0xdf, 0x70, 0x82, 0x5a, 0x38,
	0x34, 0x3b, 0x92, 0xf8, 0xf2, 0x35, 0xc1, 0xbc, 0xb4, 0xe1, 0x90, 0x26, 0x90, 0xf8, 0x77, 0x3a,
	0x38, 0xe5, 0x4c, 0x70, 0x4e, 0x00, 0x0e, 0x1d, 0x28, 0x23, 0x08, 0x7c, 0x87, 0x02, 0x4e, 0x0a,
	0x41, 0xa1, 0xbb, 0x77, 0x15, 0xbb, 0x5b, 0xbd, 0x98, 0xef, 0x0a, 0xd1, 0x75, 0xfc, 0x2d, 0x57,
	0xa8, 0x77, 0x15, 0xa9, 0x4e, 0x07, 0xf4, 0x79, 0x32, 0xe7, 0x79, 0xc4, 0x6a, 0x9b, 0x49, 0x5a,
	0xe6, 0x1b, 0xa7, 0x14, 0x1b, 0x57, 0x14, 0xe8, 0x52, 0x71, 0xa0, 0x0b, 0x80, 0x97, 0x0b, 0x80,
	0xff, 0xac, 0xc0, 0x54, 0xfe, 0xa1, 0xca, 0xc1, 0xff, 0x44, 0x8f, 0xd5, 0x26, 0xe6, 0x95, 0xb7,
	0x6d, 0x5e, 0xa5, 0xc0, 0xbc, 0x9f, 0xe4, 0xb8, 0x44, 0x3d, 0xc4, 0x33, 0x60, 0xd7, 0x8f, 0x72,
	0x37, 0x1b, 0x94, 0xca, 0x67, 0xc0, 0xaa, 0xab, 0x0a, 0x8c, 0x27, 0x43, 0x80, 0xb8, 0x99, 0xc4,
	0x7e, 0x91, 0x45, 0x99, 0x26, 0x5f, 0xc9, 0x36, 0xf9, 0x5b, 0x8d, 0x2e, 0x79, 0xad, 0x48, 0x39,
	0xb7, 0x15, 0xf9, 0x50, 0xee, 0xa2, 0x24, 0x24, 0xa9, 0x71, 0x64, 0x4b, 0x38, 0x27, 0xa1, 0x8f,
	0xad, 0xac, 0x50, 0x9d, 0x6a, 0x66, 0x78, 0x3b, 0x56, 0x13, 0x27, 0x8b, 0xfd, 0x2e, 0x84, 0xec,
	0x66, 0x2c, 0x98, 0x1a, 0x72, 0x82, 0xdb, 0x31, 0x1a, 0x72, 0xd2, 0xa8, 0x9a, 0xc4, 0x62, 0xeb,
	0x4f, 0x03, 0xaa, 0x77, 0xa4, 0x54, 0x9c, 0x0b, 0x06, 0xa1, 0x68, 0x83, 0x1d, 0xc5, 0xa4, 0xbe,
	0x22, 0xb5, 0x8b, 0x73, 0x46, 0x70, 0xc9, 0x9f, 0xa3, 0x2b, 0x5c, 0x1a, 0x8b, 0x3a, 0x74, 0x85,
	0x4b, 0x63, 0x91, 0xbf, 0xac, 0x1b, 0xea, 0x69, 0x69, 0x8c, 0x7f, 0x83, 0x51, 0x7b, 0x5b, 0x49,
	0x96, 0xfa, 0xfa, 0xcd, 0x35, 0xca, 0xb7, 0xf7, 0xf5, 0x0d, 0xf9, 0xe4, 0x2e, 0x13, 0x7e, 0x9e,
	0xda, 0x1d, 0x83, 0x59, 0x97, 0x28, 0x37, 0xc9, 0x63, 0xbb, 0x6b, 0x3f, 0xf4, 0x71, 0xff, 0x03,
	0xdf, 0xb4, 0xe0, 0x89, 0xa2, 0x57, 0xac, 0xeb, 0x06, 0xfe, 0x3f, 0xe0, 0x36, 0x69, 0x79, 0x84,
	0xe7, 0x5c, 0xff, 0x7b, 0xda, 0x64, 0x99, 0x70, 0xa9, 0xc4, 0xd4, 0x60, 0x77, 0x28, 0x2c, 0x3e,
	0x17, 0x07, 0x73, 0xb0, 0x09, 0x42, 0x4c, 0x20, 0x52, 0xaf, 0xa7, 0xe1, 0xda, 0x46, 0x88, 0x57,
	0xf6, 0xf3, 0x3f, 0x81, 0x2b, 0xc5, 0xa8, 0x2c, 0xc7, 0x08, 0xbf, 0x00, 0x7b, 0x05, 0xb4, 0xfc,
	0x4e, 0xc0, 0x47, 0x28, 0x17, 0x4b, 0xf5, 0x0f, 0x05, 0x8e, 0x24, 0x17, 0x22, 0xb3, 0x1c, 0x42,
	0xa9, 0xa8, 0x64, 0x62, 0xf2, 0xa1, 0x3b, 0x74, 0x2b, 0x3e, 0xa9, 0xd1, 0xc7, 0xf7, 0x50, 0x20,
	0x49, 0x0d, 0xd1, 0xb9, 0x54, 0x9a, 0xbd, 0x62, 0x5d, 0x37, 0x7c, 0xd6, 0x0a, 0x73, 0x75, 0xe1,
	0xbc, 0x9e, 0xc0, 0x79, 0x62, 0x5d, 0x37, 0xd4, 0xab, 0x25, 0x38, 0x9a, 0x6b, 0xf4, 0xb2, 0xad,
	0x71, 0xfd, 0x72, 0xd0, 0x91, 0x3f, 0xc5, 0x56, 0x63, 0xa8, 0x70, 0x1a, 0xf6, 0x6a, 0x83, 0x4d,
	0xf1, 0x3b, 0xe5, 0x89, 0x9e, 0x62, 0x4f, 0xf4, 0xa6, 0x3d, 0x71, 0xad, 0x24, 0xd7, 0xc3, 0xc0,
	0x13, 0xe7, 0xa9, 0x69, 0xce, 0x33, 0xcf, 0x8b, 0x7c, 0x90, 0x86, 0xad, 0x3c, 0x0e, 0xec, 0xd2,
	0x96, 0xc1, 0x2a, 0x17, 0x43, 0xac, 0xa4, 0x20, 0xfa, 0xea, 0x2d, 0x7f, 0x3e, 0x22, 0x6e, 0x14,
	0xe4, 0xc1, 0x66, 0x7f, 0x48, 0xe9, 0x7e, 0xc0, 0xea, 0xe9, 0x3a, 0x44, 0x53, 0x80, 0x38, 0xe3,
	0x9a, 0xd9, 0x5a, 0xa5, 0xa6, 0xd9, 0xd2, 0xd9, 0x9a, 0xcd, 0x43, 0x2f, 0x0c, 0x09, 0xba, 0x6f,
	0xee, 0x82, 0x4f, 0x4d, 0x3f, 0x9c, 0x2c, 0x73, 0xcd, 0xe5, 0xe1, 0x5b, 0xa5, 0xe6, 0x3e, 0x1f,
	0x90, 0x8a, 0x5a, 0x95, 0xe9, 0x8f, 0x14, 0x18, 0x8a, 0xbd, 0xb6, 0x48, 0xd6, 0x89, 0x89, 0x47,
	0x61, 0x64, 0x35, 0x4d, 0x6a, 0x35, 0x98, 0x4d, 0xd0, 0xff, 0xf0, 0x18, 0xec, 0xcb, 0x72, 0xc4,
	0xdf, 0x97, 0x90, 0x52, 0xc8, 0x9b, 0x45, 0xa5, 0x42, 0xde, 0x49, 0x54, 0x2e, 0xe4, 0xbd, 0x8c,
	0x2a, 0xd3, 0xbf, 0xf6, 0xc1, 0x60, 0xd2, 0xc7, 0xfa, 0x53, 0x54, 0x15, 0xf6, 0xae, 0xa6, 0x28,
	0x11, 0xb4, 0xa3, 0x50, 0xcb, 0x30, 0xba, 0xde, 0x0d, 0xd1, 0xa7, 0x0d, 0x7c, 0x0c, 0x0e, 0x65,
	0xc4, 0xba, 0xdf, 0x07, 0xd1, 0x8d, 0x06, 0x56, 0x61, 0x22, 0x57, 0x2e, 0x7a, 0x9b, 0x41, 0x9f,
	0x35, 0xf0, 0x11, 0x98, 0xcc, 0xc8, 0x64, 0x1f, 0x9e, 0xd0, 0xcd, 0x06, 0xae, 0xc1, 0x78, 0x8e,
	0x54, 0xbc, 0xcf, 0xe7, 0x0d, 0x7c, 0x1c, 0xd4, 0x8c, 0x44, 0xce, 0x93, 0x06, 0xfa, 0xa2, 0x81,
	0xa7, 0xe1, 0xe8, 0xa6, 0x82, 0xd1, 0x3b, 0x04, 0xba, 0xb5, 0xa5, 0x6c, 0xfc, 0x76, 0x80, 0xbe,
	0xcc, 0x33, 0x24, 0x3b, 0x29, 0xa3, 0xdb, 0x5b, 0x48, 0x89, 0x21, 0x12, 0xdd, 0x69, 0xe4, 0xc4,
	0xa1, 0x6b, 0x2e, 0x44, 0x5f, 0x35, 0xf0, 0x09, 0x38, 0xbe, 0x19, 0x3c, 0x59, 0xfa, 0x6e, 0xde,
	0xa6, 0x5d, 0x43, 0x0d, 0xfa, 0xba, 0x81, 0x0f, 0xc3, 0xc1, 0x5c, 0x57, 0x27, 0x42, 0xf7, 0x1a,
	0x78, 0x12, 0xc6, 0x32, 0x42, 0x52, 0xa3, 0x8b, 0xbe, 0xf1, 0x95, 0x4d, 0x16, 0x0b, 0x88, 0x9e,
	0x13, 0xfd, 0xf9, 0xb0, 0x9c, 0x23, 0x96, 0x6d, 0x4d, 0xd1, 0xef, 0x0f, 0xcb, 0x39, 0x98, 0x32,
	0xcd, 0x22, 0xba, 0x9f, 0x97, 0x23, 0x72, 0x63, 0x87, 0x1e, 0x34, 0xf0, 0x04, 0x8c, 0x66, 0x24,
	0xe2, 0x0e, 0x0e, 0x7d, 0x9b, 0xc7, 0x8e, 0x5b, 0x34, 0xf4, 0x9d, 0x1f, 0xba, 0x2c, 0x88, 0x4c,
	0x0b, 0x86, 0x7e, 0x79, 0x54, 0xce, 0x95, 0x4a, 0x75, 0x3e, 0xe8, 0xb7, 0x47, 0x79, 0x76, 0x87,
	0x85, 0x27, 0xae, 0xbe, 0xe8, 0xdd, 0x8f, 0x2b, 0x39, 0x9b, 0x85, 0x62, 0x51, 0x67, 0x82, 0xde,
	0xdb, 0x4c, 0x2a, 0xaa, 0x62, 0xe8, 0xda, 0xf5, 0x0a, 0x3e, 0xdc, 0x75, 0x18, 0xd3, 0xd7, 0x3b,
	0xfa, 0xe0, 0x7a, 0x05, 0xd7, 0xba, 0xe2, 0xba, 0xbc, 0xe1, 0x71, 0x62, 0xcd, 0x93, 0x0e, 0xb5,
	0xd1, 0xf7, 0x57, 0xce, 0xe0, 0x2a, 0x0c, 0x67, 0x73, 0x6e, 0x09, 0xfd, 0x70, 0xe5, 0xcc, 0xb4,
	0x0d, 0xc3, 0xa9, 0x66, 0x2f, 0x7c, 0xaf, 0xa9, 0xae, 0x76, 0x51, 0xa3, 0xdb, 0xe6, 0x80, 0xec,
	0xef, 0x98, 0x19, 0xf8, 0x5b, 0xc1, 0x07, 0x65, 0x28, 0x31, 0x37, 0x74, 0x24, 0x2a, 0xb5, 0x7b,
	0x44, 0x59, 0x39, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x8a, 0x26, 0x98, 0x76, 0x1c,
	0x00, 0x00,
}
