// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scout.proto

package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 客户端请求侦查
type MsgCL2GSScoutRequest struct {
	ScoutIndex uint32        `protobuf:"varint,2,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	Command    *ScoutCommand `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	RegionId   uint64        `protobuf:"varint,4,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgCL2GSScoutRequest) Reset()                    { *m = MsgCL2GSScoutRequest{} }
func (m *MsgCL2GSScoutRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSScoutRequest) ProtoMessage()               {}
func (*MsgCL2GSScoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{0} }

func (m *MsgCL2GSScoutRequest) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgCL2GSScoutRequest) GetCommand() *ScoutCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *MsgCL2GSScoutRequest) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

// 侦查响应
type MsgGS2CLScoutReply struct {
	EntityId  uint64 `protobuf:"varint,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLScoutReply) Reset()                    { *m = MsgGS2CLScoutReply{} }
func (m *MsgGS2CLScoutReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLScoutReply) ProtoMessage()               {}
func (*MsgGS2CLScoutReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{1} }

func (m *MsgGS2CLScoutReply) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *MsgGS2CLScoutReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 撤回
type MsgCL2GSScoutMoveBackRequest struct {
	ScoutIndex uint32 `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	RegionId   uint64 `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgCL2GSScoutMoveBackRequest) Reset()                    { *m = MsgCL2GSScoutMoveBackRequest{} }
func (m *MsgCL2GSScoutMoveBackRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSScoutMoveBackRequest) ProtoMessage()               {}
func (*MsgCL2GSScoutMoveBackRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{2} }

func (m *MsgCL2GSScoutMoveBackRequest) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgCL2GSScoutMoveBackRequest) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

type MsgGS2CLScoutMoveBackReply struct {
	ScoutIndex uint32 `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLScoutMoveBackReply) Reset()                    { *m = MsgGS2CLScoutMoveBackReply{} }
func (m *MsgGS2CLScoutMoveBackReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLScoutMoveBackReply) ProtoMessage()               {}
func (*MsgGS2CLScoutMoveBackReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{3} }

func (m *MsgGS2CLScoutMoveBackReply) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgGS2CLScoutMoveBackReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 客户端请求迷雾数据
type MsgCL2GSMistRequest struct {
}

func (m *MsgCL2GSMistRequest) Reset()                    { *m = MsgCL2GSMistRequest{} }
func (m *MsgCL2GSMistRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSMistRequest) ProtoMessage()               {}
func (*MsgCL2GSMistRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{4} }

type MsgGS2CLMistReply struct {
	Mist      *MistData `protobuf:"bytes,1,opt,name=mist" json:"mist,omitempty"`
	RegionId  uint64    `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode int32     `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLMistReply) Reset()                    { *m = MsgGS2CLMistReply{} }
func (m *MsgGS2CLMistReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMistReply) ProtoMessage()               {}
func (*MsgGS2CLMistReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{5} }

func (m *MsgGS2CLMistReply) GetMist() *MistData {
	if m != nil {
		return m.Mist
	}
	return nil
}

func (m *MsgGS2CLMistReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLMistReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求探索迷雾
type MsgCL2GSMistExploreRequest struct {
	ScoutIndex    uint32      `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	Route         []*Vector2D `protobuf:"bytes,2,rep,name=route" json:"route,omitempty"`
	IsAutoExplore bool        `protobuf:"varint,3,opt,name=is_auto_explore,json=isAutoExplore" json:"is_auto_explore,omitempty"`
}

func (m *MsgCL2GSMistExploreRequest) Reset()                    { *m = MsgCL2GSMistExploreRequest{} }
func (m *MsgCL2GSMistExploreRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSMistExploreRequest) ProtoMessage()               {}
func (*MsgCL2GSMistExploreRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{6} }

func (m *MsgCL2GSMistExploreRequest) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgCL2GSMistExploreRequest) GetRoute() []*Vector2D {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *MsgCL2GSMistExploreRequest) GetIsAutoExplore() bool {
	if m != nil {
		return m.IsAutoExplore
	}
	return false
}

type MsgGS2CLMistExploreReply struct {
	ScoutIndex uint32 `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	RegionId   uint64 `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLMistExploreReply) Reset()                    { *m = MsgGS2CLMistExploreReply{} }
func (m *MsgGS2CLMistExploreReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMistExploreReply) ProtoMessage()               {}
func (*MsgGS2CLMistExploreReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{7} }

func (m *MsgGS2CLMistExploreReply) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgGS2CLMistExploreReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLMistExploreReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 迷雾打开通知
type MsgGS2CLMistOpenNotice struct {
	X        uint32       `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y        uint32       `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	OpenType MistOpenType `protobuf:"varint,3,opt,name=open_type,json=openType,enum=protomsg.MistOpenType" json:"open_type,omitempty"`
	RegionId uint64       `protobuf:"varint,4,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgGS2CLMistOpenNotice) Reset()                    { *m = MsgGS2CLMistOpenNotice{} }
func (m *MsgGS2CLMistOpenNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMistOpenNotice) ProtoMessage()               {}
func (*MsgGS2CLMistOpenNotice) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{8} }

func (m *MsgGS2CLMistOpenNotice) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MsgGS2CLMistOpenNotice) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MsgGS2CLMistOpenNotice) GetOpenType() MistOpenType {
	if m != nil {
		return m.OpenType
	}
	return MistOpenType_kMistOpenType_Scout
}

func (m *MsgGS2CLMistOpenNotice) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

// 所有迷雾清除通知
type MsgGS2CLMistCleanNotice struct {
	RegionId uint64 `protobuf:"varint,1,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgGS2CLMistCleanNotice) Reset()                    { *m = MsgGS2CLMistCleanNotice{} }
func (m *MsgGS2CLMistCleanNotice) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMistCleanNotice) ProtoMessage()               {}
func (*MsgGS2CLMistCleanNotice) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{9} }

func (m *MsgGS2CLMistCleanNotice) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

// 客户端请求自动解除不可达迷雾
type MsgCL2GSMistOpenMistRequest struct {
	Route []*Vector2D `protobuf:"bytes,1,rep,name=route" json:"route,omitempty"`
}

func (m *MsgCL2GSMistOpenMistRequest) Reset()                    { *m = MsgCL2GSMistOpenMistRequest{} }
func (m *MsgCL2GSMistOpenMistRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSMistOpenMistRequest) ProtoMessage()               {}
func (*MsgCL2GSMistOpenMistRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{10} }

func (m *MsgCL2GSMistOpenMistRequest) GetRoute() []*Vector2D {
	if m != nil {
		return m.Route
	}
	return nil
}

type MsgGS2CLMistOpenMistReply struct {
	RegionId  uint64 `protobuf:"varint,1,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLMistOpenMistReply) Reset()                    { *m = MsgGS2CLMistOpenMistReply{} }
func (m *MsgGS2CLMistOpenMistReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLMistOpenMistReply) ProtoMessage()               {}
func (*MsgGS2CLMistOpenMistReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{11} }

func (m *MsgGS2CLMistOpenMistReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLMistOpenMistReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 开启指定关卡/神庙建筑的迷雾
type MsgCL2GSMistOpenBuildingMistRequest struct {
	EntityId uint64 `protobuf:"varint,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
}

func (m *MsgCL2GSMistOpenBuildingMistRequest) Reset()         { *m = MsgCL2GSMistOpenBuildingMistRequest{} }
func (m *MsgCL2GSMistOpenBuildingMistRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSMistOpenBuildingMistRequest) ProtoMessage()    {}
func (*MsgCL2GSMistOpenBuildingMistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{12}
}

func (m *MsgCL2GSMistOpenBuildingMistRequest) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type MsgGS2CLMistOpenBuildingMistReply struct {
	EntityId  uint64 `protobuf:"varint,1,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	RegionId  uint64 `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLMistOpenBuildingMistReply) Reset()         { *m = MsgGS2CLMistOpenBuildingMistReply{} }
func (m *MsgGS2CLMistOpenBuildingMistReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLMistOpenBuildingMistReply) ProtoMessage()    {}
func (*MsgGS2CLMistOpenBuildingMistReply) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{13}
}

func (m *MsgGS2CLMistOpenBuildingMistReply) GetEntityId() uint64 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

func (m *MsgGS2CLMistOpenBuildingMistReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLMistOpenBuildingMistReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// /////////////////////////////////////////////探索//////////////////////////////////
// 客户端请求探索数据
type MsgCL2GSExploreRequest struct {
}

func (m *MsgCL2GSExploreRequest) Reset()                    { *m = MsgCL2GSExploreRequest{} }
func (m *MsgCL2GSExploreRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreRequest) ProtoMessage()               {}
func (*MsgCL2GSExploreRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{14} }

type MsgGS2CLExploreReply struct {
	Info      *PlayerExploreInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	RegionId  uint64             `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode int32              `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLExploreReply) Reset()                    { *m = MsgGS2CLExploreReply{} }
func (m *MsgGS2CLExploreReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreReply) ProtoMessage()               {}
func (*MsgGS2CLExploreReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{15} }

func (m *MsgGS2CLExploreReply) GetInfo() *PlayerExploreInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MsgGS2CLExploreReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLExploreReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 更新村庄状态
type MsgGS2CLExploreUpdateVillageNotice struct {
	VillageId uint64        `protobuf:"varint,1,opt,name=village_id,json=villageId" json:"village_id,omitempty"`
	Status    ExploreStatus `protobuf:"varint,2,opt,name=status,enum=protomsg.ExploreStatus" json:"status,omitempty"`
	RegionId  uint64        `protobuf:"varint,3,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgGS2CLExploreUpdateVillageNotice) Reset()         { *m = MsgGS2CLExploreUpdateVillageNotice{} }
func (m *MsgGS2CLExploreUpdateVillageNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreUpdateVillageNotice) ProtoMessage()    {}
func (*MsgGS2CLExploreUpdateVillageNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{16}
}

func (m *MsgGS2CLExploreUpdateVillageNotice) GetVillageId() uint64 {
	if m != nil {
		return m.VillageId
	}
	return 0
}

func (m *MsgGS2CLExploreUpdateVillageNotice) GetStatus() ExploreStatus {
	if m != nil {
		return m.Status
	}
	return ExploreStatus_kExploreStatus_Hiden
}

func (m *MsgGS2CLExploreUpdateVillageNotice) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

// 更新山洞信息
type MsgGS2CLExploreUpdateCaveNotice struct {
	Cave     *CaveInfo `protobuf:"bytes,1,opt,name=cave" json:"cave,omitempty"`
	RegionId uint64    `protobuf:"varint,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
}

func (m *MsgGS2CLExploreUpdateCaveNotice) Reset()         { *m = MsgGS2CLExploreUpdateCaveNotice{} }
func (m *MsgGS2CLExploreUpdateCaveNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreUpdateCaveNotice) ProtoMessage()    {}
func (*MsgGS2CLExploreUpdateCaveNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{17}
}

func (m *MsgGS2CLExploreUpdateCaveNotice) GetCave() *CaveInfo {
	if m != nil {
		return m.Cave
	}
	return nil
}

func (m *MsgGS2CLExploreUpdateCaveNotice) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

// 更新探索建筑状态
type MsgGS2CLExploreUpdateBuildingNotice struct {
	ObjectId   uint64        `protobuf:"varint,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Status     ExploreStatus `protobuf:"varint,2,opt,name=status,enum=protomsg.ExploreStatus" json:"status,omitempty"`
	RegionId   uint64        `protobuf:"varint,3,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	EntityType uint32        `protobuf:"varint,4,opt,name=entity_type,json=entityType" json:"entity_type,omitempty"`
}

func (m *MsgGS2CLExploreUpdateBuildingNotice) Reset()         { *m = MsgGS2CLExploreUpdateBuildingNotice{} }
func (m *MsgGS2CLExploreUpdateBuildingNotice) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreUpdateBuildingNotice) ProtoMessage()    {}
func (*MsgGS2CLExploreUpdateBuildingNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{18}
}

func (m *MsgGS2CLExploreUpdateBuildingNotice) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func (m *MsgGS2CLExploreUpdateBuildingNotice) GetStatus() ExploreStatus {
	if m != nil {
		return m.Status
	}
	return ExploreStatus_kExploreStatus_Hiden
}

func (m *MsgGS2CLExploreUpdateBuildingNotice) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLExploreUpdateBuildingNotice) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

// 请求领取山洞/村庄奖励
type MsgCL2GSExploreAwardRequest struct {
	EntityType EntityType `protobuf:"varint,1,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	ObjectId   uint64     `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *MsgCL2GSExploreAwardRequest) Reset()                    { *m = MsgCL2GSExploreAwardRequest{} }
func (m *MsgCL2GSExploreAwardRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreAwardRequest) ProtoMessage()               {}
func (*MsgCL2GSExploreAwardRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{19} }

func (m *MsgCL2GSExploreAwardRequest) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgCL2GSExploreAwardRequest) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type MsgGS2CLExploreAwardReply struct {
	EntityType EntityType   `protobuf:"varint,1,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	ObjectId   uint64       `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Rewards    *ResourceSet `protobuf:"bytes,3,opt,name=rewards" json:"rewards,omitempty"`
	RegionId   uint64       `protobuf:"varint,4,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode  int32        `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLExploreAwardReply) Reset()                    { *m = MsgGS2CLExploreAwardReply{} }
func (m *MsgGS2CLExploreAwardReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreAwardReply) ProtoMessage()               {}
func (*MsgGS2CLExploreAwardReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{20} }

func (m *MsgGS2CLExploreAwardReply) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgGS2CLExploreAwardReply) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func (m *MsgGS2CLExploreAwardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgGS2CLExploreAwardReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLExploreAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 一键领取山洞/村庄奖励
type MsgCL2GSExploreBatchAwardRequest struct {
	EntityType EntityType `protobuf:"varint,1,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	ObjectIds  []uint64   `protobuf:"varint,2,rep,packed,name=object_ids,json=objectIds" json:"object_ids,omitempty"`
}

func (m *MsgCL2GSExploreBatchAwardRequest) Reset()         { *m = MsgCL2GSExploreBatchAwardRequest{} }
func (m *MsgCL2GSExploreBatchAwardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreBatchAwardRequest) ProtoMessage()    {}
func (*MsgCL2GSExploreBatchAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{21}
}

func (m *MsgCL2GSExploreBatchAwardRequest) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgCL2GSExploreBatchAwardRequest) GetObjectIds() []uint64 {
	if m != nil {
		return m.ObjectIds
	}
	return nil
}

type MsgGS2CLExploreBatchAwardReply struct {
	EntityType EntityType   `protobuf:"varint,1,opt,name=entity_type,json=entityType,enum=protomsg.EntityType" json:"entity_type,omitempty"`
	ObjectIds  []uint64     `protobuf:"varint,2,rep,packed,name=object_ids,json=objectIds" json:"object_ids,omitempty"`
	Rewards    *ResourceSet `protobuf:"bytes,3,opt,name=rewards" json:"rewards,omitempty"`
	RegionId   uint64       `protobuf:"varint,4,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode  int32        `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLExploreBatchAwardReply) Reset()         { *m = MsgGS2CLExploreBatchAwardReply{} }
func (m *MsgGS2CLExploreBatchAwardReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreBatchAwardReply) ProtoMessage()    {}
func (*MsgGS2CLExploreBatchAwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{22}
}

func (m *MsgGS2CLExploreBatchAwardReply) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType_kEntityType_None
}

func (m *MsgGS2CLExploreBatchAwardReply) GetObjectIds() []uint64 {
	if m != nil {
		return m.ObjectIds
	}
	return nil
}

func (m *MsgGS2CLExploreBatchAwardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgGS2CLExploreBatchAwardReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLExploreBatchAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求领取山洞额外奖励
type MsgCL2GSExploreCaveExtraAwardRequest struct {
	ObjectId uint64 `protobuf:"varint,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *MsgCL2GSExploreCaveExtraAwardRequest) Reset()         { *m = MsgCL2GSExploreCaveExtraAwardRequest{} }
func (m *MsgCL2GSExploreCaveExtraAwardRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreCaveExtraAwardRequest) ProtoMessage()    {}
func (*MsgCL2GSExploreCaveExtraAwardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{23}
}

func (m *MsgCL2GSExploreCaveExtraAwardRequest) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type MsgGS2CLExploreCaveExtraAwardReply struct {
	ObjectId  uint64       `protobuf:"varint,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	Rewards   *ResourceSet `protobuf:"bytes,2,opt,name=rewards" json:"rewards,omitempty"`
	RegionId  uint64       `protobuf:"varint,3,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode int32        `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLExploreCaveExtraAwardReply) Reset()         { *m = MsgGS2CLExploreCaveExtraAwardReply{} }
func (m *MsgGS2CLExploreCaveExtraAwardReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLExploreCaveExtraAwardReply) ProtoMessage()    {}
func (*MsgGS2CLExploreCaveExtraAwardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{24}
}

func (m *MsgGS2CLExploreCaveExtraAwardReply) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func (m *MsgGS2CLExploreCaveExtraAwardReply) GetRewards() *ResourceSet {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func (m *MsgGS2CLExploreCaveExtraAwardReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLExploreCaveExtraAwardReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 派遣斥候访问指定物件
type MsgCL2GSExploreVisitRequest struct {
	ScoutIndex uint32 `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	ObjectId   uint64 `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *MsgCL2GSExploreVisitRequest) Reset()                    { *m = MsgCL2GSExploreVisitRequest{} }
func (m *MsgCL2GSExploreVisitRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreVisitRequest) ProtoMessage()               {}
func (*MsgCL2GSExploreVisitRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{25} }

func (m *MsgCL2GSExploreVisitRequest) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgCL2GSExploreVisitRequest) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type MsgCL2GSExploreVisitReply struct {
	ScoutIndex uint32 `protobuf:"varint,1,opt,name=scout_index,json=scoutIndex" json:"scout_index,omitempty"`
	ObjectId   uint64 `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	RegionId   uint64 `protobuf:"varint,3,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgCL2GSExploreVisitReply) Reset()                    { *m = MsgCL2GSExploreVisitReply{} }
func (m *MsgCL2GSExploreVisitReply) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSExploreVisitReply) ProtoMessage()               {}
func (*MsgCL2GSExploreVisitReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{26} }

func (m *MsgCL2GSExploreVisitReply) GetScoutIndex() uint32 {
	if m != nil {
		return m.ScoutIndex
	}
	return 0
}

func (m *MsgCL2GSExploreVisitReply) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func (m *MsgCL2GSExploreVisitReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgCL2GSExploreVisitReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 解锁已探索建筑
type MsgCL2GSUnlockExploredBuildingRequest struct {
	ObjectId uint64 `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
}

func (m *MsgCL2GSUnlockExploredBuildingRequest) Reset()         { *m = MsgCL2GSUnlockExploredBuildingRequest{} }
func (m *MsgCL2GSUnlockExploredBuildingRequest) String() string { return proto.CompactTextString(m) }
func (*MsgCL2GSUnlockExploredBuildingRequest) ProtoMessage()    {}
func (*MsgCL2GSUnlockExploredBuildingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{27}
}

func (m *MsgCL2GSUnlockExploredBuildingRequest) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

type MsgGS2CLUnlockExploredBuildingReply struct {
	ObjectId   uint64 `protobuf:"varint,2,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	RegionId   uint64 `protobuf:"varint,3,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	EntityType uint32 `protobuf:"varint,4,opt,name=entity_type,json=entityType" json:"entity_type,omitempty"`
	ErrorCode  int32  `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLUnlockExploredBuildingReply) Reset()         { *m = MsgGS2CLUnlockExploredBuildingReply{} }
func (m *MsgGS2CLUnlockExploredBuildingReply) String() string { return proto.CompactTextString(m) }
func (*MsgGS2CLUnlockExploredBuildingReply) ProtoMessage()    {}
func (*MsgGS2CLUnlockExploredBuildingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor71, []int{28}
}

func (m *MsgGS2CLUnlockExploredBuildingReply) GetObjectId() uint64 {
	if m != nil {
		return m.ObjectId
	}
	return 0
}

func (m *MsgGS2CLUnlockExploredBuildingReply) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *MsgGS2CLUnlockExploredBuildingReply) GetEntityType() uint32 {
	if m != nil {
		return m.EntityType
	}
	return 0
}

func (m *MsgGS2CLUnlockExploredBuildingReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 请求是否驻扎
type MsgCL2GSStationRequest struct {
	IsStation bool `protobuf:"varint,1,opt,name=is_station,json=isStation" json:"is_station,omitempty"`
}

func (m *MsgCL2GSStationRequest) Reset()                    { *m = MsgCL2GSStationRequest{} }
func (m *MsgCL2GSStationRequest) String() string            { return proto.CompactTextString(m) }
func (*MsgCL2GSStationRequest) ProtoMessage()               {}
func (*MsgCL2GSStationRequest) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{29} }

func (m *MsgCL2GSStationRequest) GetIsStation() bool {
	if m != nil {
		return m.IsStation
	}
	return false
}

type MsgGS2CLStationgReply struct {
	ErrorCode int32 `protobuf:"varint,99,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *MsgGS2CLStationgReply) Reset()                    { *m = MsgGS2CLStationgReply{} }
func (m *MsgGS2CLStationgReply) String() string            { return proto.CompactTextString(m) }
func (*MsgGS2CLStationgReply) ProtoMessage()               {}
func (*MsgGS2CLStationgReply) Descriptor() ([]byte, []int) { return fileDescriptor71, []int{30} }

func (m *MsgGS2CLStationgReply) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCL2GSScoutRequest)(nil), "protomsg.MsgCL2GSScoutRequest")
	proto.RegisterType((*MsgGS2CLScoutReply)(nil), "protomsg.MsgGS2CLScoutReply")
	proto.RegisterType((*MsgCL2GSScoutMoveBackRequest)(nil), "protomsg.MsgCL2GSScoutMoveBackRequest")
	proto.RegisterType((*MsgGS2CLScoutMoveBackReply)(nil), "protomsg.MsgGS2CLScoutMoveBackReply")
	proto.RegisterType((*MsgCL2GSMistRequest)(nil), "protomsg.MsgCL2GSMistRequest")
	proto.RegisterType((*MsgGS2CLMistReply)(nil), "protomsg.MsgGS2CLMistReply")
	proto.RegisterType((*MsgCL2GSMistExploreRequest)(nil), "protomsg.MsgCL2GSMistExploreRequest")
	proto.RegisterType((*MsgGS2CLMistExploreReply)(nil), "protomsg.MsgGS2CLMistExploreReply")
	proto.RegisterType((*MsgGS2CLMistOpenNotice)(nil), "protomsg.MsgGS2CLMistOpenNotice")
	proto.RegisterType((*MsgGS2CLMistCleanNotice)(nil), "protomsg.MsgGS2CLMistCleanNotice")
	proto.RegisterType((*MsgCL2GSMistOpenMistRequest)(nil), "protomsg.MsgCL2GSMistOpenMistRequest")
	proto.RegisterType((*MsgGS2CLMistOpenMistReply)(nil), "protomsg.MsgGS2CLMistOpenMistReply")
	proto.RegisterType((*MsgCL2GSMistOpenBuildingMistRequest)(nil), "protomsg.MsgCL2GSMistOpenBuildingMistRequest")
	proto.RegisterType((*MsgGS2CLMistOpenBuildingMistReply)(nil), "protomsg.MsgGS2CLMistOpenBuildingMistReply")
	proto.RegisterType((*MsgCL2GSExploreRequest)(nil), "protomsg.MsgCL2GSExploreRequest")
	proto.RegisterType((*MsgGS2CLExploreReply)(nil), "protomsg.MsgGS2CLExploreReply")
	proto.RegisterType((*MsgGS2CLExploreUpdateVillageNotice)(nil), "protomsg.MsgGS2CLExploreUpdateVillageNotice")
	proto.RegisterType((*MsgGS2CLExploreUpdateCaveNotice)(nil), "protomsg.MsgGS2CLExploreUpdateCaveNotice")
	proto.RegisterType((*MsgGS2CLExploreUpdateBuildingNotice)(nil), "protomsg.MsgGS2CLExploreUpdateBuildingNotice")
	proto.RegisterType((*MsgCL2GSExploreAwardRequest)(nil), "protomsg.MsgCL2GSExploreAwardRequest")
	proto.RegisterType((*MsgGS2CLExploreAwardReply)(nil), "protomsg.MsgGS2CLExploreAwardReply")
	proto.RegisterType((*MsgCL2GSExploreBatchAwardRequest)(nil), "protomsg.MsgCL2GSExploreBatchAwardRequest")
	proto.RegisterType((*MsgGS2CLExploreBatchAwardReply)(nil), "protomsg.MsgGS2CLExploreBatchAwardReply")
	proto.RegisterType((*MsgCL2GSExploreCaveExtraAwardRequest)(nil), "protomsg.MsgCL2GSExploreCaveExtraAwardRequest")
	proto.RegisterType((*MsgGS2CLExploreCaveExtraAwardReply)(nil), "protomsg.MsgGS2CLExploreCaveExtraAwardReply")
	proto.RegisterType((*MsgCL2GSExploreVisitRequest)(nil), "protomsg.MsgCL2GSExploreVisitRequest")
	proto.RegisterType((*MsgCL2GSExploreVisitReply)(nil), "protomsg.MsgCL2GSExploreVisitReply")
	proto.RegisterType((*MsgCL2GSUnlockExploredBuildingRequest)(nil), "protomsg.MsgCL2GSUnlockExploredBuildingRequest")
	proto.RegisterType((*MsgGS2CLUnlockExploredBuildingReply)(nil), "protomsg.MsgGS2CLUnlockExploredBuildingReply")
	proto.RegisterType((*MsgCL2GSStationRequest)(nil), "protomsg.MsgCL2GSStationRequest")
	proto.RegisterType((*MsgGS2CLStationgReply)(nil), "protomsg.MsgGS2CLStationgReply")
}

func init() { proto.RegisterFile("scout.proto", fileDescriptor71) }

var fileDescriptor71 = []byte{
	// 944 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xd6, 0x38, 0x6e, 0x6b, 0xbf, 0xd0, 0x02, 0x4b, 0x92, 0x9a, 0x84, 0x50, 0xb3, 0x40, 0xe4,
	0x53, 0x82, 0x5c, 0x51, 0xce, 0x8d, 0x5b, 0x45, 0x96, 0x1a, 0xa8, 0xd6, 0xb4, 0x1c, 0xa8, 0xb4,
	0x9a, 0xee, 0x4e, 0xcc, 0x50, 0x7b, 0x67, 0xbb, 0x33, 0xeb, 0xd8, 0x12, 0x37, 0xa4, 0x5e, 0x11,
	0x07, 0xce, 0xfc, 0x07, 0x48, 0xfc, 0x3f, 0xdc, 0xf8, 0x47, 0xd0, 0xfc, 0xf2, 0xfe, 0x70, 0xb2,
	0x9b, 0xc8, 0xa5, 0xa7, 0x24, 0x6f, 0xdf, 0xbc, 0xf7, 0x7d, 0xdf, 0xbc, 0xef, 0xed, 0x06, 0x36,
	0x79, 0xc0, 0x52, 0x71, 0x18, 0x27, 0x4c, 0x30, 0xa7, 0xa5, 0x7e, 0x4c, 0xf9, 0x78, 0x77, 0x67,
	0xca, 0xc7, 0x7e, 0xc0, 0xa6, 0x53, 0x16, 0xf9, 0xb9, 0x8c, 0xdd, 0xad, 0x5c, 0x7c, 0x8a, 0x63,
	0x13, 0xfd, 0x20, 0x8b, 0xea, 0x88, 0xfb, 0x06, 0xc1, 0xd6, 0x29, 0x1f, 0x0f, 0x9e, 0xf4, 0x4f,
	0x46, 0x23, 0x79, 0xde, 0x23, 0xaf, 0x53, 0xc2, 0x85, 0x73, 0xcf, 0x74, 0xf4, 0x69, 0x14, 0x92,
	0x79, 0xa7, 0xd1, 0x45, 0xbd, 0xdb, 0x1e, 0xa8, 0xd0, 0x50, 0x46, 0x9c, 0xaf, 0xe0, 0x96, 0xac,
	0x84, 0xa3, 0xb0, 0xb3, 0xd1, 0x45, 0xbd, 0xcd, 0xfe, 0xce, 0xa1, 0x45, 0x75, 0xa8, 0x2a, 0x0d,
	0xf4, 0x53, 0xcf, 0xa6, 0x39, 0x7b, 0xd0, 0x4e, 0xc8, 0x98, 0xb2, 0xc8, 0xa7, 0x61, 0xa7, 0xd9,
	0x45, 0xbd, 0xa6, 0xd7, 0xd2, 0x81, 0x61, 0xe8, 0x3e, 0x05, 0xe7, 0x94, 0x8f, 0x4f, 0x46, 0xfd,
	0xc1, 0x13, 0x83, 0x23, 0x9e, 0x2c, 0xe4, 0x11, 0x12, 0x09, 0x2a, 0x16, 0xf2, 0x08, 0xd2, 0x47,
	0x74, 0x60, 0x18, 0x3a, 0xfb, 0x00, 0x24, 0x49, 0x58, 0xe2, 0x07, 0x2c, 0x24, 0x9d, 0xa0, 0x8b,
	0x7a, 0x37, 0xbc, 0xb6, 0x8a, 0x0c, 0x58, 0x48, 0xdc, 0x17, 0xf0, 0x49, 0x81, 0xd9, 0x29, 0x9b,
	0x91, 0x63, 0x1c, 0xbc, 0xba, 0x84, 0x21, 0x5a, 0x61, 0x58, 0xc0, 0xdb, 0x28, 0xe1, 0x7d, 0x01,
	0xbb, 0x05, 0xbc, 0x59, 0x75, 0x89, 0xbb, 0xb6, 0x76, 0x0d, 0xf6, 0x6d, 0xf8, 0xc8, 0x62, 0x3f,
	0xa5, 0xdc, 0x5e, 0x8a, 0x7b, 0x0e, 0x1f, 0xda, 0xa6, 0x3a, 0x2c, 0x7b, 0x1d, 0x40, 0x73, 0x4a,
	0xb9, 0x50, 0x4d, 0x36, 0xfb, 0x4e, 0x76, 0x0b, 0x32, 0xe5, 0x11, 0x16, 0xd8, 0x53, 0xcf, 0x2b,
	0xe9, 0xd4, 0xe1, 0xf9, 0x0d, 0x29, 0xba, 0x4b, 0x40, 0x8f, 0xe7, 0xf1, 0x84, 0x25, 0xe4, 0xca,
	0x52, 0xf6, 0xe0, 0x46, 0xc2, 0x52, 0x41, 0x3a, 0x8d, 0xee, 0x46, 0x11, 0xe4, 0x8c, 0x04, 0x82,
	0x25, 0xfd, 0xd0, 0xd3, 0x09, 0xce, 0x01, 0xbc, 0x4f, 0xb9, 0x8f, 0x53, 0xc1, 0x7c, 0xa2, 0x9b,
	0xa8, 0xf1, 0x6a, 0x79, 0xb7, 0x29, 0x7f, 0x98, 0x0a, 0x66, 0x3a, 0xbb, 0xe7, 0xd0, 0xc9, 0x4b,
	0xb1, 0x04, 0x74, 0x25, 0xf5, 0xd7, 0x91, 0xe2, 0x0d, 0x82, 0x9d, 0x7c, 0xe7, 0xef, 0x62, 0x12,
	0x7d, 0xcb, 0x04, 0x0d, 0x88, 0xf3, 0x1e, 0x20, 0xdb, 0x0d, 0xcd, 0xe5, 0x5f, 0x0b, 0xe3, 0x1b,
	0xb4, 0x70, 0xee, 0x43, 0x9b, 0xc5, 0x24, 0xf2, 0xc5, 0x22, 0xd6, 0x8c, 0xee, 0xe4, 0x0d, 0x63,
	0x0b, 0x7d, 0xbf, 0x88, 0x89, 0xd7, 0x62, 0xe6, 0xb7, 0x6a, 0xc7, 0x3c, 0x80, 0xbb, 0x79, 0x1c,
	0x83, 0x09, 0xc1, 0x16, 0x48, 0xe1, 0x1c, 0x2a, 0x9d, 0x3b, 0x81, 0xbd, 0xfc, 0x55, 0xca, 0xb6,
	0xb9, 0x19, 0xcb, 0xae, 0x0a, 0xd5, 0x5c, 0x95, 0xfb, 0x03, 0x7c, 0x5c, 0x16, 0x22, 0x9b, 0xca,
	0x2a, 0x08, 0x75, 0x12, 0x1f, 0xc3, 0xe7, 0x65, 0x84, 0xc7, 0x29, 0x9d, 0x84, 0x34, 0x1a, 0xe7,
	0x91, 0x56, 0x2d, 0x07, 0xf7, 0x17, 0xf8, 0xac, 0x0c, 0xae, 0x58, 0xa3, 0x76, 0xbd, 0xac, 0x33,
	0x24, 0x1d, 0x35, 0x23, 0x8a, 0x41, 0xd1, 0x2a, 0xee, 0xaf, 0x7a, 0xe1, 0x2a, 0x60, 0x85, 0xa1,
	0x3d, 0x82, 0x26, 0x8d, 0xce, 0x98, 0xb1, 0xf1, 0x5e, 0x26, 0xfb, 0xd3, 0x09, 0x5e, 0x90, 0xc4,
	0xe4, 0x0e, 0xa3, 0x33, 0xe6, 0xa9, 0xc4, 0xb5, 0xf0, 0xfd, 0x8e, 0xc0, 0x2d, 0xa1, 0x78, 0x16,
	0x87, 0x58, 0x90, 0xe7, 0x74, 0x32, 0xc1, 0x63, 0x62, 0xe6, 0x68, 0x1f, 0x60, 0xa6, 0x03, 0x99,
	0x40, 0x6d, 0x13, 0x19, 0x86, 0xce, 0x11, 0xdc, 0xe4, 0x02, 0x8b, 0x94, 0xab, 0xf6, 0x77, 0xfa,
	0x77, 0x33, 0xd0, 0xa6, 0xe8, 0x48, 0x3d, 0xf6, 0x4c, 0x5a, 0x11, 0xf2, 0x46, 0x69, 0x2e, 0xcf,
	0xe0, 0xde, 0x85, 0x90, 0x06, 0x78, 0x66, 0xf1, 0x1c, 0x40, 0x33, 0xc0, 0x33, 0xb2, 0xba, 0xea,
	0x64, 0x8e, 0x96, 0x46, 0x3e, 0xaf, 0xde, 0xdc, 0x7f, 0x23, 0x35, 0x5e, 0xab, 0x8d, 0xec, 0x7c,
	0x64, 0x26, 0x62, 0x2f, 0x7f, 0x26, 0x81, 0xc8, 0x0d, 0x87, 0x0e, 0xbc, 0x6d, 0xea, 0x72, 0x61,
	0x99, 0x39, 0x54, 0xeb, 0xa1, 0xa9, 0x17, 0x96, 0x0e, 0xc9, 0x45, 0xe0, 0xbe, 0xce, 0x3c, 0x6b,
	0xca, 0x3f, 0x3c, 0xc7, 0x49, 0x68, 0x9d, 0xf0, 0x75, 0xf1, 0x3c, 0x52, 0x90, 0xb6, 0x72, 0x90,
	0x96, 0x95, 0xf2, 0x55, 0x8b, 0x0c, 0x1b, 0x45, 0x86, 0xee, 0x3f, 0x28, 0xb3, 0x77, 0xb1, 0xa7,
	0x9c, 0xd6, 0xff, 0xa1, 0xa3, 0x73, 0x04, 0xb7, 0x12, 0x22, 0x5b, 0x70, 0xf3, 0x45, 0xb1, 0x9d,
	0xd5, 0xf3, 0x08, 0x67, 0x69, 0x12, 0x90, 0x11, 0x11, 0x9e, 0xcd, 0xaa, 0x5c, 0x8f, 0x75, 0x0e,
	0x98, 0x43, 0xb7, 0xa4, 0xe8, 0x31, 0x16, 0xc1, 0x4f, 0x6f, 0x43, 0xd6, 0x7d, 0x80, 0x25, 0x49,
	0xae, 0xde, 0x78, 0x4d, 0xaf, 0x6d, 0x59, 0x72, 0xf7, 0x5f, 0x04, 0x9f, 0x96, 0x84, 0xcd, 0xb7,
	0x5e, 0x43, 0xdd, 0xea, 0xc6, 0xef, 0x56, 0xdf, 0x01, 0x7c, 0x51, 0xd2, 0x57, 0x7a, 0xf4, 0xf1,
	0x5c, 0x24, 0xb8, 0xa0, 0x71, 0x95, 0xcb, 0xdc, 0xbf, 0x56, 0xd7, 0x54, 0xb9, 0x8a, 0x59, 0xe3,
	0x55, 0x4e, 0x5d, 0xb2, 0x6e, 0x5c, 0x9f, 0xf5, 0xc6, 0xf5, 0x58, 0xff, 0xb8, 0xe2, 0xd3, 0xe7,
	0x94, 0x53, 0x71, 0x9d, 0x4f, 0xce, 0xcb, 0x1d, 0xf9, 0x87, 0x76, 0xe4, 0x05, 0xd5, 0xaf, 0xfa,
	0xd1, 0x73, 0xb9, 0xf7, 0xd6, 0x21, 0xfd, 0x08, 0xbe, 0xb4, 0xb0, 0x9e, 0x45, 0x13, 0x16, 0xbc,
	0x32, 0xe0, 0x42, 0xbb, 0x50, 0x2f, 0xbc, 0xeb, 0x32, 0xbb, 0x3f, 0x73, 0x6b, 0xf9, 0xb2, 0x32,
	0x2b, 0x97, 0x7d, 0x2d, 0x1a, 0x75, 0x5b, 0xb6, 0x8e, 0xe7, 0x37, 0xd9, 0x4b, 0x5d, 0x2e, 0x77,
	0xca, 0x22, 0x4b, 0x6c, 0x1f, 0x80, 0x72, 0x9f, 0xeb, 0xa0, 0x92, 0xbe, 0xe5, 0xb5, 0x29, 0x37,
	0x59, 0xee, 0x03, 0xd8, 0x5e, 0xfe, 0xaf, 0xa0, 0x43, 0x86, 0x4b, 0x75, 0xc3, 0x97, 0x37, 0xd5,
	0xa0, 0xde, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x68, 0x1e, 0xdf, 0xf9, 0xfc, 0x0d, 0x00, 0x00,
}
