taskkill /IM "activityserver.exe" /F
taskkill /IM "chatserver.exe" /F
taskkill /IM "databaseserver.exe" /F
taskkill /IM "dispatcherserver.exe" /F
taskkill /IM "gameserver.exe" /F
taskkill /IM "guildsearchserver.exe" /F
taskkill /IM "guildserver.exe" /F
taskkill /IM "instanceserver.exe" /F
taskkill /IM "kvkserver.exe" /F
taskkill /IM "localuserserver.exe" /F
taskkill /IM "loginserver.exe" /F
taskkill /IM "mailserver.exe" /F
taskkill /IM "mapserver.exe" /F
taskkill /IM "pathfindserver.exe" /F
taskkill /IM "transferserver.exe" /F
taskkill /IM "userserver.exe" /F
taskkill /IM "globalserver.exe" /F
taskkill /IM "globalactivityserver.exe" /F
taskkill /IM "guildderbyserver.exe" /F
taskkill /IM "reportserver.exe" /F
exit
