package common

const (
	MODE_CONTINUE = 1
	MODE_EXIT     = 2
	MODE_WAIT     = 3
)

const (
	CONSOLE_LOG_DEBUG   = 0x1
	CONSOLE_LOG_INFO    = 0x2
	CONSOLE_LOG_SUCCESS = 0x4
	CONSOLE_LOG_ERROR   = 0x8
	CONSOLE_LOG_ALL     = 0xF
)

const (
	CLIENT_TYPE_GAME_SERVER  = 1
	CLIENT_TYPE_LOGIN_SERVER = 2
	CLIENT_TYPE_CHAT_SERVER  = 3
)
